### ISSUE TITLE
Authenticating and creating

### ISSUE THREAD

**Issue by startupthekid** [feathersjs/feathers-authentication#100]
I propose adding a config option that allows the user to specify if the auth service should automatically create a user if passport authentication fails due to the account not existing.

The authentication call would look something like: 

```
this.app.service(this.options.userEndpoint)
      .find(params)
      .then(users => {
        // Paginated services return the array of results in the data attribute.
        let user = users[0] || users.data && users.data[0];
        // Handle bad username.
        if (!user) {
            if (this.options.createIfNonexistent) {
                this.app.service.create(params).then(newlyCreatedUser => return newlyCreatedUser)
           }
          return done(null, false);
        }

        return user;
      })
```

My example isn't 100% correct but you get the gist of the idea. Right now the way things work you'd first have to make a `POST` call to your user service to create the user, then a call to login which means the create call on the user service has to be an exposed endpoint.

What I want to be able to do is:

```
userService.before({
    create: [
        hooks.disable('external'),
        authHooks.hashPassword()
    ]
});
```

Another idea could be to have a configuration option for a signup route, which would hash the password (if a password is supplied), create a user, then generate a token.

@daffl do you have any thoughts on something like this?

**Comment by ekryski** [comment]
I had thought about this and intentionally left it off because creation is just a POST to `/users`. OAuth does already create a user if they don't exist.

@daffl and I talked about this today in fact. I'm not 100% sold on the idea, not because it isn't good, but because I don't want to bloat feathers-auth when feature is going to be dependent on your business logic a bit.

@startupthekid let me stew on it for a day or so. I'm going to be doing some auth work this weekend most likely so I'll hopefully have some time to spike it out along with the work I've been doing on the password service.

**Comment by startupthekid** [comment]
That does make sense, avoiding bloat is generally a good thing. And to play devil's advocate to my own idea, the less unintended side effects there are the easier it is to understand for the end user. And it's not like you can't lock down the api further using a custom hook and an api key or something similar. 

Now that I think about it, while it might be useful feature, it might not be needed. I like the idea of pure functions i.e. it only does one thing and there are no side effects involved.

**Comment by ekryski** [comment]
@startupthekid It's definitely not a no. I just need a bit of time to think about it and spike it out to see how it would look with the work I'm doing with Password management. So thanks for the suggestion and creating the issue! :smile:

**Comment by ekryski** [comment]
You can now do this with auth v1.x by simply [wrapping your `auth.hooks.authenticate` hook](https://docs.feathersjs.com/hooks/usage.html#customizing-built-in-hooks) and catching the error and creating a user and authenticating again.

Alternatively, you could implement a [custom verifier](https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier) for your auth provider that does this internally as part of the verification process.
