### ISSUE TITLE
Logging out breaks in React Native

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#105]
AsyncStorage requires values to be strings and we are currently setting `null`. See [this line](https://github.com/feathersjs/feathers-authentication/blob/master/src/client/index.js#L73).

We probably need to JSON stringify and parse values or something.

**Comment by catalinmiron** [comment]
Can you also post an example of using `dribbble` auth or any other provider, using React Native?

**Comment by ekryski** [comment]
Yup we'll post something up when it's ready. Like we talked about in Slack (which I think was after you posted this) we have somethings to work out to support OAuth on mobile. It currently supports authenticating if you are able to get the `access_token` already but if you can't then we have some work to do still.
