### ISSUE TITLE
Token encoding is not using the idField option.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#107]
`idField` option (which by default is `_id` and why you don’t need to provide it) is not being respected when ​*encoding*​ the JWT but ​*is*​ when it is decoded.

[This line](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/populate-user.js#L30) is :+1: 

[This line](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/token/index.js#L97) is :-1:

**Comment by ekryski** [comment]
Somewhat related to #103

**Comment by saiichihashimoto** [comment]
I was just about to report this issue!
