### ISSUE TITLE
TypeError: Cannot read property 'service' of undefined (continued)

### ISSUE THREAD

**Issue by thosakwe** [feathersjs/feathers-authentication#108]
Having a similar problem to [#56](https://github.com/feathersjs/feathers-authentication/issues/56).

Here's my app setup right now: [Gist](https://gist.github.com/thosakwe/280e808bcc2175b273f1)

I'm wondering what I messed up with.

Thanks in advance for your help, I appreciate that the Feathers team is responsive. It encourages me to keep using this framework.

**Comment by daffl** [comment]
The Gist looks right so far but how are you using the exported app? The error most likely happens it [app.setup](http://docs.feathersjs.com/api/readme.html#setup) is not called. It gets called automatically when you use [app.listen](http://docs.feathersjs.com/api/readme.html#listen) but if you e.g. use it with a [virtual host or HTTP server](http://docs.feathersjs.com/middleware/mounting.html) you need to call `app.setup` with the server instance.

**Comment by thosakwe** [comment]
@daffl Here's the server file: https://gist.github.com/thosakwe/280e808bcc2175b273f1#file-server-js

I changed it now to use `app.listen(port)`, but now I have a somewhat mysterious new error when trying to authenticate via auth/local. When my credentials are correct, I get this error: "data and hash arguments required."

![data and hash arguments required](http://i.imgur.com/x5GxFc1.png)

**Comment by daffl** [comment]
How doe the request and `AppHooks.Users.create()` look like? It looks like `AuthenticationHooks.hashPassword()` is trying to hash a `password` that is undefined.

**Comment by thosakwe** [comment]
Validator is [feathers-validator](https://github.com/thosakwe/feathers-validator). Long story short, it checks the hook's data for input errors.
```js
function create() {
    return (hook) => {
        let errors = new Validator(hook.data, {
            username: "required|min:5|max:255",
            password: "required|min:6",
            email: "required|min:5|max:255"
        }).errors();

        if (errors.length) throw new Error(errors[0]);
    }
}
```

**Comment by ekryski** [comment]
@thosakwe double check that your password field is there. That's a typical cause for that brypt error. I'm in the process of adding better error messaging for that.

As an aside in your hook you might want to `throw new errors.BadRequest({ errors: errors });` so that you get the proper error code.

You also might want to check out @kulakowka's https://github.com/kulakowka/feathers-validate-hook. Maybe you guys can collaborate :smile:

**Comment by thosakwe** [comment]
@ekryski Cool, I might contact him sooner or later.

Anyways, that just leaves me with one more question. I hooked `hashPassword` onto the update and patch methods as well.

Since the create method is already hooked to deny requests if the password isn't there, I'm wondering if the bcrypt error is because I didn't check for a password on update or patch.

Should I just remove hashPassword from update and patch? That might be the problem.

**Comment by ekryski** [comment]
@thosakwe oh ya that's probably the issue. `hashPassword` should only be called if a password is present, usually just on the `create` method. We are working on a password service that will manage changing passwords if that is what you are after.

**Comment by thosakwe** [comment]
I was doing all the above steps, and was getting nowhere. I looked over my setup again, and I realized that I overlooked the order of the hooks on my update and patch methods. I had verifyToken() after populateUser().

Thanks again for the help.

**Comment by ekryski** [comment]
@thosakwe glad you got it sorted. I have better error messages that will help hopefully make this more clear.
