### ISSUE TITLE
Wrong Status Error

### ISSUE THREAD

**Issue by hnordt** [feathersjs/feathers-authentication#110]
When I use the following auth hooks:

```js
[
  verifyToken(),
  populateUser(),
  requireAuth()
]
```

And don't provide an Authorization header I receive a 500 error:

![untitled_paw_document](https://cloud.githubusercontent.com/assets/1625399/13942535/22d8ddd2-efd2-11e5-9af5-6a0bb9f338e3.png)

Instead I should receive a 401 error.

**Comment by ekryski** [comment]
@hnordt If you look in the log you are receiving that is a 401.

```
NotAuthenticated: Please include a valid auth....
```

Is your `Accept` header set to `application/json`? Otherwise it just renders an html error.
