### ISSUE TITLE
how to authenticate user in the socket.io?

### ISSUE THREAD

**Issue by anguskwan** [feathersjs/feathers-authentication#111]
i used the https://github.com/jfromaniello/passport.socketio to check whether the user is logined in the server socket. 

```js
//With Socket.io >= 1.0
io.use(passportSocketIo.authorize({
  cookieParser: cookieParser,       // the same middleware you registrer in express
  key:          'express.sid',       // the name of the cookie where express/connect stores its session_id
  secret:       'session_secret',    // the session_secret to parse the cookie
  store:        sessionStore,        // we NEED to use a sessionstore. no memorystore please
  success:      onAuthorizeSuccess,  // *optional* callback on success - read more below
  fail:         onAuthorizeFail,     // *optional* callback on fail/error - read more below
}));

```

how to do with feathers-authentication? thanks.

**Comment by ekryski** [comment]
@anguskwan while it's possible to use socket.io directly to authenticate with a Feathers server you are better off using the [feathers-client for authentication](http://docs.feathersjs.com/authentication/readme.html).

At this point we're not looking to support people using third party modules like `passportSocketIo` as that method relies on sessions. So currently, you are on your own for that. If you want to look at how we set up the socket authentication with Feathers you can check out [this function](https://github.com/feathersjs/feathers-authentication/blob/master/src/middleware/index.js#L107).

**Comment by anguskwan** [comment]
thank you so much for your quick  and kind response @ekryski. 
i did not mean to use a third party for socket authentication.
what i want is to do double check user info in the server side socket, the setupSocketIOAuthentication code answer my questions.

thanks again.

**Comment by ekryski** [comment]
@anguskwan awesome :+1:
