### ISSUE TITLE
Move to bcryptjs

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-authentication#112]
There is a [pure js version of bcrypt](https://www.npmjs.com/package/bcryptjs) that we might want to try out because compiling bcrypt is causing a lot of issues (see https://github.com/feathersjs/feathers-chat/issues/1 and https://github.com/feathersjs/feathers/issues/273 for example).

**Comment by marshallswain** [comment]
Yeah.  It can really be a huge pain to get bcrypt to build.  I ran into that with Travis.  Let's just be sure to call it out in the readme of the modules that use it.  If bcrypt being 2.7x slower means they have to use 3x more machines for scaling then they might want to know about other options.

**Comment by daffl** [comment]
Ah yes, that's another specific problem for bcrypt, it only runs on newer versions of GCC that many Linux distributions don't have.

I can't see a huge performance hit here. It's not that you usually create thousands of new users that need their passwords hashed per second.

**Comment by marshallswain** [comment]
Yeah. Seems like now It will only be a few weeks before somebody shows us.  :)

**Comment by ekryski** [comment]
I'm less concerned with the performance but more the memory overhead. The bcrypt algorithm is fixed to a certain amount of time to compare passwords in order to prevent timing attacks and you don't compare passwords enough for performance to really have an impact. We should check to see if switching to the JS one doesn't raise memory a bunch.

Sorry I'm being a stickler but IMHO this a pretty low priority given everything else we have on the go. I don't want to monkey with a bunch of the auth stuff until we have good test coverage in place.

I also think, as a general rule, that just because a couple people have issues doesn't mean we should change something for everyone. We've only had 2 issues created and both were from people that are new to node and on windows.

**Comment by daffl** [comment]
I think it is. Besides those two issues it came up in other conversations before and it does make things much harder to use in Windows.

I already spent at least hour myself trying to figure out why my Travis CI tests didn't pass (it didn't come with the right version of GCC to compile bcrypt) and anybody who is using Travis (or more conservative Linux distributions) for their projects will also run into the same problem.

**Comment by marshallswain** [comment]
We ought to add a section to the FAQ docs on *Working with Travis*

**Comment by ekryski** [comment]
@marshallswain probably not our concern there really. We only use Travis for plugins and I think the generator generally does a good job of scaffolding out stuff. We can always help people if they want to transfer repos to us.

@daffl alright, feel free to add it after I get https://github.com/feathersjs/feathers-authentication/pull/109 merged later today. Personally, I'd like to have at least a rough idea of what the CPU/Memory effects of switching are going to be given how core this module is turning out to be, but if you think it's top priority then _shrug_.

Like I said, it is not a very high priority for me.

**Comment by beeplin** [comment]
I would say that as a windows user it is reeeeeally painful to install the whole bunch of visual studio thing (around 9G) just for get a convenient c++ compiler to build feathers-authentication. Would be nice if this got solved. 


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Eric Kryski <notifications@github.com>
时间：周三 3月23日 00:19
收件人：feathersjs/feathers-authentication <feathers-authentication@noreply.github.com>
主题：Re: [feathers-authentication] Move to bcryptjs (#112)

>@marshallswain probably not our concern there really. We only use Travis for plugins and I think the generator generally does a good job of scaffolding out stuff. We can always help people if they want to transfer repos to us. @daffl alright, feel free to add it after I get #109 merged later today. Personally, I'd like to have at least a rough idea of what the CPU/Memory effects of switching are going to be given how core this module is turning out to be, but if you think it's top priority then shrug. Like I said, it is not a very high priority for me. —You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by ekryski** [comment]
Closed by https://github.com/feathersjs/feathers-authentication/pull/137.
