### ISSUE TITLE
Create a `requireAuth` wrapper for `verifyToken`, `populateUser`, `restrictToAuth`

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#118]
Saving key strokes is what we like doing. :smile:

**Comment by ekryski** [comment]
Dependent on #109 getting merged.

**Comment by marshallswain** [comment]
Do we want to create a general way to allow people to created nested hooks?

**Comment by myknbani** [comment]
I looked at the code for the `restrictToAuth` hook, quite short and it seems to assume that `hook.params.user` has been populated.

I commented out `verifyToken` and `populateUser`,

```js
app.service('api/ducks').before({
  all: [
    // authentication.hooks.verifyToken(),
    // authentication.hooks.populateUser(),
    authentication.hooks.restrictToAuthenticated(),
    (hook) => {
      console.log('================the hook looks like:===================')
      console.log(hook)
      console.log('=======================================================')
    },
  ],
```

and it still seems to work. the hook object looks like:

```
   token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1N2M3ZDEwZTU1ZDc0ODU5MDU0ZTBmMWUiLCJpYXQiOjE0NzI3MTY4NTMsImV4cCI6MTQ3MjgwMzI1MywiaXNzIjoiZmVhdGhlcnMifQ.kFSpBOmlc7UDLARyFbdBDsuNCYYUQTkv085NT_FE-34',
     user: 
      { _id: 57c7d10e55d74859054e0f1e,
        firstName: 'foo',
        lastName: 'bar',
        username: 'baz',
        __v: 0 } },
```

:laughing: Is there something else that populates them?  I'm using socket.io

**Comment by ekryski** [comment]
Closing as those hooks have been re-shuffled into the new authentication chain so you won't need to repeat them.
