### ISSUE TITLE
Feathers Auth Configuration Error

### ISSUE THREAD

**Issue by lokenx** [feathersjs/feathers-authentication#12]
Using the example in the README I get the below error:

```
.configure(feathersAuth({
             ^

TypeError: feathersAuth is not a function
    at Object.<anonymous> (/Users/mdelport/Development/node/plexauth/index.js:17:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Not sure if I'm missing something or if the build is just currently broken.

**Comment by marshallswain** [comment]
Thanks for spotting this.  After updating to ES6 imports, internally, you have to add `.default` to the require()
```
var feathersAuth = require('feathers-authentication').default;
```

**Comment by marshallswain** [comment]
@daffl @ekryski Is there a way to work around having to add `.default` to the require?

**Comment by lokenx** [comment]
Doing that causes it to crash on

```
var hashPassword = feathersAuth.hashPassword;

var userService = app.service('/api/users');

userService.before({
  create: hashPassword()
});

TypeError: hashPassword is not a function
```

**Comment by marshallswain** [comment]
Oh, yep.  Those moved, too.  I'll update the docs.

Do this instead:
```js
var authHooks = require('feathers-authentication').hooks;

var userService = app.service('/api/users');
userService.before({
  // If your password field is just "password", you can do this.
  create: authHooks.hashPassword
  // You can also customize the password field if you need to.
  create: authHooks.hashPassword('pass')
});
```

**Comment by lokenx** [comment]
That seems to work, I'll have to play more tomorrow! Thanks for speedy responses, probably safe to close.

**Comment by daffl** [comment]
@marshallswain I started doing `export default module.exports = xyz;`

**Comment by marshallswain** [comment]
@lokenx Cool.  No problem.  I haven't added documentation for all of the hooks to the README.md, yet, but you can [browse through them](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks.js) in the code.  `feathers-authentication` ONLY takes care of auth. You'll need to use hooks for access control.  I'll get a full example in place sometime soon.  There might be a similar example on feathersjs.com, already.

**Comment by marshallswain** [comment]
@daffl thanks.
