### ISSUE TITLE
Want the default success/fail routes, not the sendFile

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs/feathers-authentication#121]
As of [v0.6.0](https://github.com/feathersjs/feathers-authentication/releases/tag/v0.6.0) the `setUpSuccessRedirect` and `setUpSuccessRedirect` parameters have been removed in favor of [checking if the routes are equal to the defaults](https://github.com/feathersjs/feathers-authentication/blob/900bf023df9e86351b98c05b853e142810fee0fd/src/index.js#L56). So now I can't use `/auth/success` or `/auth/failure` with my own routes and are forced to have it send the `public/auth-success.html` and `public/auth-fail.html` files. There should be an option of using those defaults without being forced to have those specific html files.

**Comment by ekryski** [comment]
Ah :hankey: I knew there was a reason I had that in there but then @daffl made me second guess. My bad. I'll do a patch release for this, along with #122.
