### ISSUE TITLE
Logout should clear the cookie

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs/feathers-authentication#122]
As far as I'm aware, `app.authenticate()` checks the cookie as well as the storage. When you log out, shouldn't the cookie be unset as well as the storage?

**Comment by ekryski** [comment]
Absolutely. Thanks!

**Comment by jasondonnette** [comment]
Why was this reversed? I am running into a bug where if a user logs out (after logging in with oauth2) they get re-logged in when they refresh due to the cookie.
