### ISSUE TITLE
[security] Generated tokens are broadcast to all socket clients (by default)

### ISSUE THREAD

**Issue by t2t2** [feathersjs/feathers-authentication#126]
![feathers-auth-broadcast](https://cloud.githubusercontent.com/assets/1122555/14041338/68cd9e88-f278-11e5-8d5f-51f7baf65a63.png)

**Comment by daffl** [comment]
Oh dear. This can be fixed quickly though via:

```js
app.service('auth/local').filter(() => false);
```

Which should probably be the default for all auth services (we don't need their events anwyay).
We were discussing turning off event dispatching by default so you have to enable it explicitly. It would be the more secure but also more confusing approach.

**Comment by ekryski** [comment]
:+1: @t2t2 thanks for pointing it out. I was aware of this and have a note in the code but forgot to create an issue and completely forgot about it!

We'll get a fix in for this soon. In the mean time anyone can lock down their services by doing what @daffl mentioned.
