### ISSUE TITLE
Update Docs, Guides, Examples for v0.7

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#129]
## Changes in other repos that need to happen

- [x] Update generated hooks in the generator to the new hook names/interfaces
- [x] Update [Authorization section](http://docs.feathersjs.com/authorization/bundled-hooks.html) in docs
- [x] Update [tutorial](http://docs.feathersjs.com/getting-started/user-management.html#authorization)
- [x] Update [chat example repo](https://github.com/feathersjs/feathers-chat)

**Comment by marshallswain** [comment]
I created a new branch for the changes: auth-0.7.0: https://github.com/feathersjs/generator-feathers/tree/auth-0.6.0

**Comment by daffl** [comment]
Note to self, don't forget about #113. 0.7.0 is a good candidate for this as well.

**Comment by ekryski** [comment]
I did put #112 under the milestone.

**Comment by marshallswain** [comment]
Tutorial is updated here: https://github.com/feathersjs/feathers-docs/pull/109

**Comment by marshallswain** [comment]
I have a PR ready for the chat example app.  Can you add me to that repo so I can push it? 
https://github.com/feathersjs/feathers-chat

**Comment by marshallswain** [comment]
I guess I really updated everything for 0.6.0.  If there's anything else, then we can add to those repos.

**Comment by ekryski** [comment]
done and done!

**Comment by marshallswain** [comment]
Hmm.  I still can't create a remote branch.

**Comment by marshallswain** [comment]
Oh.  Looks like you updated it.  That works.

**Comment by beeplin** [comment]
con! Already using 0.7. :)


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Eric Kryski <notifications@github.com>
时间：周四 3月31日 09:22
收件人：feathersjs/feathers-authentication <feathers-authentication@noreply.github.com>
主题：Re: [feathersjs/feathers-authentication] Update Docs, Guides, Examples for v0.7 (#129)

**Comment by ekryski** [comment]
Yup I could have sworn you updated it to 0.6 @marshallswain but I guess I must have done it when I moved to 0.7.
