### ISSUE TITLE
Allow require without `.default`

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#13]
`export default module.exports = xyz;` as per #12

**Comment by marshallswain** [comment]
https://github.com/feathersjs/feathers-knex/issues/16#event-472820904

**Comment by daffl** [comment]
It should probably use the Babel plugin (see https://github.com/feathersjs/feathers-knex/pull/17)

**Comment by marshallswain** [comment]
Looks like using `require('module').default` is the new correct way to do this when using Babel.  http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default Closing

**Comment by ekryski** [comment]
When you are not using ES6, yes.
