### ISSUE TITLE
v6.0.0: How can I return the user object along with the token ?

### ISSUE THREAD

**Issue by djhi** [feathersjs/feathers-authentication#131]
Hi! I'm trying to have a simple local authentication which is working fine. I do receive the jwt token when calling the `app.authenticate` method using rest from `feathers-rest/client`.

However, I'd like to retrieve the user data (id, email, etc.) and I can't figure out how. I understand that the API has changed in v0.5 and that `app.get('user')` is not populated anymore. Is it possible to configure authentication in order to get that feature back ? If not, what is the preferred method to achieve this ?

Here is the code I'm using:
```js
/* globals ADMIN_API_URL */
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import rest from 'feathers-rest/client';
import authentication from 'feathers-authentication/client';
import fetch from 'isomorphic-fetch';

const app = feathers()
    .configure(rest(ADMIN_API_URL).fetch(fetch))
    .configure(hooks())
    .configure(authentication({ storage: window.localStorage }));

function redirect() {
    window.location = '/admin';
}

// check for user already logged in
if (window.localStorage.getItem('token')) {
    redirect();
}

document.getElementById('loginForm').addEventListener('submit', (event) => {
    event.preventDefault(); // stop form from submitting

    app.authenticate({
        type: 'local',
        email: document.getElementById('inputEmail').value,
        password: document.getElementById('inputPassword').value,
    }).then(({ token }) => {
        window.localStorage.setItem('token', token);
        const userService = app.service('users');
        return userService.get();
    }).then(user => {
        console.log({ user });
        window.localStorage.setItem('id', user.id);
        window.localStorage.setItem('email', user.email);
        redirect();
    }).catch(err => {
        console.error({ err });
        document.getElementById('loginError').style.display = 'block';
        document.getElementById('submitButton').disabled = false;
    });
});
```

Thanks !

**Comment by djhi** [comment]
If possible, Id'l like to avoid the call to `userService`

**Comment by ekryski** [comment]
We released v0.6 a couple days ago and haven't documented the breaking changes. I have a couple more changes coming in a v0.7 release later today and will update the docs then. You will get the current user in the response when you authenticate, and it will be available with `app.get('user')`. :smile:

This actually already happens in v0.6.0. You can see the release notes in the README if you want to upgrade or just wait a day or so and we'll have the docs and examples updated.

**Comment by djhi** [comment]
Thanks for answering so quickly :) That was my first attempt but unfortunately, `app.get('user')` returns `undefined`

**Comment by djhi** [comment]
For information, I used the yeoman generator to initialize my app

**Comment by djhi** [comment]
Found it! The `auth` configuration **must** have an `idField` property otherwise the user cannot be retrieved. This might be important to mention in the docs :)

**Comment by ekryski** [comment]
It depends on which DB you are using. By default it sets `_id` as the `idField`.

**Comment by djhi** [comment]
I'm using postgres. Thanks and great lib btw !

**Comment by ekryski** [comment]
Yes so for PG you'd need to set that manually. I'm going to create an issue for the generator to do that for you though.

**Comment by djhi** [comment]
Great! However I really think this should be documented. In my case, I won't be using the generator anymore as it does not play well with my folder structure: [marmelab boilerplate](https://github.com/marmelab/javascript-boilerplate) with feathers replacing the Koa API.

**Comment by longntp** [comment]
Do you have any options to get current user without using feathers client ?

**Comment by daffl** [comment]
[Decode the JWT](https://github.com/auth0/node-jsonwebtoken#jwtdecodetoken--options). Take the user id from the resulting payload and run a `GET /users/<userid>`.

**Comment by longntp** [comment]
@daffl : Can I use successRidirect on "auth" property in config file. Redirect to another path (middleware) and attach user object along with the response back to client ? I think making another request to server is not a good idea :(.

**Comment by daffl** [comment]
Yes, you can also add an `app.service('authentication').after({ create(hook) {} })`  [hook](https://docs.feathersjs.com/hooks/usage.html) that adds the user information to `hook.result`.

**Comment by longntp** [comment]
I will try it and let me know if any further issue. Many many thanks for your instant support :D
