### ISSUE TITLE
Calling logout should revoke/blacklist a JWT

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#133]
This is dependent on https://github.com/feathersjs/feathers-authentication/issues/73.

**Comment by beeplin** [comment]
@ekryski , I just found that even after calling app.logout(), the client can still fetch data from server which are supposed to be restricted to authenticated. this might be the same issue you mentioned here?

**Comment by ekryski** [comment]
@beeplin that one is related to #122. The token is still hanging around in the cookie. This issue will take that further and make sure that token can never be used again by *anyone*.

**Comment by ekryski** [comment]
So I did a bit of digging and reading this weekend and I don't think this is really an issue if we keep the TTL's of tokens really short and implement a refresh token mechanism. I'm going to close this.
