### ISSUE TITLE
Throw errors for deprecated hooks and update documentation

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-authentication#134]
I was running into vague errors when I began adding authentication hooks, e.g.,

```
.../services/signature/hooks.js:44
sAuthentication.hooks.populateUser(), _feathersAuthentication.hooks.requireAut
                                                                    ^
TypeError: undefined is not a function
    at Object.<anonymous> (hooks.js:43:15)
    at Module._compile (module.js:460:26)
```

because I was requiring a deprecated hook:

```js
import { hooks as authHooks } from 'feathers-authentication';

exports.before = {
  create: [
    ...
    authHooks.requireAuth(), // bad
    ...
  ]
}
```

when I really wanted this:

```js
import { hooks as authHooks } from 'feathers-authentication';

exports.before = {
  create: [
    ...
    authHooks.restrictToAuthenticated(), // good
    ...
  ]
}
```

Then I saw the new documentation in the `README` which helped me out, but a clearer message in the console would be preferred. The [authentication hooks documentation](http://docs.feathersjs.com/authorization/bundled-hooks.html) references the deprecated names.

**Comment by ekryski** [comment]
Sorry yes we haven't gotten around to updating the docs just yet. Some new fixes are going in first to avoid doing work twice. #129
