### ISSUE TITLE
Make all hooks optional if used internally

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#138]
Most of the hooks already do this. These ones need to be updated:

- [x] query with current user
- [x] associate with current user
- [x] hash password

**Comment by daffl** [comment]
It is possible for a user to overwrite `params.provider` so you run the risk of exposing unsecured methods to the outside world. Although unlikely we might want to investigate using `Object.defineProperty` so that it doesn't happen accidentally.

**Comment by ekryski** [comment]
Sure. Let's create another issue for that though because that touches all the hooks and I don't want to block shipping in this in order to prevent someone from _possibly_ screwing up their hooks.
