### ISSUE TITLE
bcrypt is hardcoded

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-authentication#146]
There does not seem to be a way to change your hashing strategy except for passing your own bcrypt API compatible object at https://github.com/feathersjs/feathers-authentication/blob/master/src/services/local/index.js#L43.

**Comment by ekryski** [comment]
I think we are still good here. As long as you provide a module has `compare` function with the same interface and returns the same callback args you should be able to use whatever hashing mechanism you want.

```js
// your hashing module
exports default {
  compare: function(plaintext, hashedPassword, callback) {
    // do your hashing

   callback(error, result);
  }
}
```

```js
// auth config

app.configure(authentication({
  bcrypt: myHashingModule
}))
```

The other part is just writing your own `hashPassword` hook.

**Comment by ekryski** [comment]
The only thing we might want to do to make it more clear that this is an option is move line 43 up to [here](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/local/index.js#L13).

**Comment by marshallswain** [comment]
Needs docs is all.

**Comment by ekryski** [comment]
Personally, I'm not sure that I really want to encourage people to use a different hashing algorithm. There is a reason that almost everyone uses bcrypt. It's the one of, if not the most secure, right now.

I could be wrong but I also don't think it's that common to want to use a different hashing algorithm. Only when migrating an app to Feathers and chances are most people are already using bcrypt.

I'm going to close this. We can open a new issue to document this if someone else requires it. We have so many other things to document right now.
