### ISSUE TITLE
restrictToRoles availability inconsistency

### ISSUE THREAD

**Issue by fimdomeio** [feathersjs/feathers-authentication#153]
in the documentation  says `It can be used on all methods`.
http://docs.feathersjs.com/authorization/bundled-hooks.html#restricttoroles

When trying to apply it to a find method I get the following error:
`The 'restrictToRoles' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.`

**Comment by ekryski** [comment]
I just fixed this last night. Update to v0.7.1
