### ISSUE TITLE
Support custom authentication strategies

### ISSUE THREAD

**Issue by quick691fr** [feathersjs/feathers-authentication#157]
Should be cool if you can add your custom authentication strategy like in passport.js.

**Comment by ekryski** [comment]
You can already do this in some cases. We just haven't documented. What sort of authentication did you have in mind?

**Comment by ekryski** [comment]
@quick691fr ^. I do agree there might be some work to do but a couple people have already implemented custom strategies (ie. SAML, their own hashing function, etc.).

**Comment by quick691fr** [comment]
Do you have an example of an external passport strategy plugged into feather ?

**Comment by ekryski** [comment]
@quick691fr I'll try and track down @petermikitsh's SAML gist, or maybe he can link it. We'll look to turn it into a guide.

**Comment by petermikitsh** [comment]
@quick691fr @ekryski Here's the [gist](https://gist.github.com/petermikitsh/11157140bc727acb7623). :)

With the changes to cookies after the security discussion, it may be out of date. This was written for release 0.6.0.

**Comment by quick691fr** [comment]
Thank you guys for your help.

**Comment by ekryski** [comment]
I don't think it's too out of date really so it should give you a decent idea.

**Comment by ekryski** [comment]
I've created an issue to track this in the docs https://github.com/feathersjs/feathers-docs/issues/159
