### ISSUE TITLE
Automatically add the hashPassword hook to local.userEndpoint

### ISSUE THREAD

**Issue by juodumas** [feathersjs/feathers-authentication#158]
Didn't investigate whether this is possible, but feathers-authentication expects a bcrypt'ed hash in the passwordField, so it would make sense to add the hashPassword hook automatically. If this is not possible, the documentation should be more explicit about the need for the hashPassword hook and I believe that all places with the following should be changed:
```
userService.before({
  create: authentication.hooks.hashPassword()
});
```

to

```
userService.before({
  create: authentication.hooks.hashPassword(),
  update: authentication.hooks.hashPassword(),
  patch: authentication.hooks.hashPassword()
});
```

As a side note, I think that more hook aliases like `all` would be nice: `read -> find, get` and `write -> create, update, patch`.

**Comment by ekryski** [comment]
@juodumas update maybe, but for patch no. You might not be sending the user's password (and in most cases you shouldn't be), we have better password management coming as part of auth.

**Comment by juodumas** [comment]
True, setting a password with `patch` calls for a separate password changing service.

**Comment by ekryski** [comment]
Closing. Related to #83.
