### ISSUE TITLE
onBeforeLogin Hook

### ISSUE THREAD

**Issue by ansarizafar** [feathersjs/feathers-authentication#161]
In certain situations, it is necessary to perform some checks before allowing a user to login. I propose an onBeforeLogin hook to allow adding custom logic. This feature is very important for my use case but  currently I have not found any solution to perform some checks before allowing a user to login.

**Comment by gurisko** [comment]
Hey @ansarizafar. You can do this already by adding a before hook to the auth service:
```javascript
const hooks = require('./hooks')
const authTokenService = app.service('/auth/token')
authTokenService.before(hooks.before)
authTokenService.after(hooks.after)
```

**Comment by ekryski** [comment]
Closing because @gurisko already answered this. Thanks @gurisko! 😄
