### ISSUE TITLE
Pass more to local authentication params

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs/feathers-authentication#165]
I'm trying to create an app where there's different areas of the room, somewhat like slack teams. A person may have the same email in different areas. So when someone logs in, I want to retrieve them by username but ALSO by the area. In other words, I need to add to the [params used to retrieve from the user service](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/local/index.js#L22). As it stands, there's no way to do that.

**Comment by ekryski** [comment]
I think the only way would be to add a **before** hook on your user service that adds the params when going through authentication. The problem with the `checkCredentials` function signature is that is dictated by passport, I don't think that we can monkey with it.

Did you have any success @saiichihashimoto?

**Comment by saiichihashimoto** [comment]
A before hook doesn't solve my problem. When check credentials looks up the user via the app service, it only passes the username as a query parameter. I want to use information from the request (in my case, the current subdomain), and have that be one of the query parameters. Regardless of any before hooks we'll always get the same query, currently.

Just like #171, I need to do some logic on the parameters before I pass them in. I'm fine hacking together a solution for my specific case, but I'm having a hard time doing what I want without having to rewrite the whole file for my case.

**Comment by saiichihashimoto** [comment]
Does what I'm saying make sense?
