### ISSUE TITLE
Optionally Include password in the params.query object passed to User.find()

### ISSUE THREAD

**Issue by toddgeist** [feathersjs/feathers-authentication#171]
I have a DB that requires userName and Password to verify the user record.  The user service only receives the userName now.  The password is left off.  I understand that it isn't necessary for most systems. But it is for mine. 

How about a config option to include password in params.query?

If I am not mistaken, a little code could be added right here
https://github.com/feathersjs/feathers-authentication/blob/master/src/services/local/index.js#L22-L26

maybe something like this?
```
const params = {
   query: {
        [this.options.usernameField]: username
    }
};
//optionally add the password to params.query
if(this.options.includePasswordInQuery){
   params.query[this.options.passwordField] = password
}
```
Would you consider a pull request with this?

Thanks

**Comment by daffl** [comment]
I think there already was a feature request somewhere to be able to query for different fields. But there still needs to be a password comparison function. How are you comparing your passwords? I assume they aren't just plain text.

**Comment by toddgeist** [comment]
In this DB The passwords are stored hashed, but I can't access the hash.  All I can do is query the DB with a UserName and Password, if the Password matches I get back the User Record.  If it doesn't I do not.

So I query the DB, if the UserRecord comes back _I hash the password right then_ and stick it on the userObject.  Then the normal comparison function is happy and generates the token.

A bit of hack I'll grant you but what else can I do :-)

**Comment by toddgeist** [comment]
#165 seems related
