### ISSUE TITLE
Facebook Authentication should do a patch not an update.

### ISSUE THREAD

**Issue by DenJohX** [feathersjs/feathers-authentication#174]
Using a feathers-cli generated app with mongodb, if the user model has more fields (other than facebook-id and facebook data), all those fields gets erased when the user authenticates. 

This happens because the authentication proccess updates the social information of the user by sending a full update to the user service, thus eliminating any other field the user may have. I think should be better to patch the user instead of updating it.

**Comment by beevelop** [comment]
I can confirm that using `update` leads to the described side-effects. This bug is very like to be independent of the used database – however I can reproduce it for MySQL too.

**Comment by marshallswain** [comment]
Do one of you want to try changing this line to do patch instead of update?: https://github.com/feathersjs/feathers-authentication/blob/master/src/services/oauth2/index.js#L63

And see if it resolves the issue?  Thanks.

**Comment by beevelop** [comment]
Yeah, I already did so: beevelop/feathers-authentication@a7300f8f1748b22cbe8e2ec2a15e3b3e6f941a3f
I can confirm this results in the excepted behaviour (by not crashing your user entry).

**Comment by marshallswain** [comment]
Cool!  Would you mind making a PR out of that?
