### ISSUE TITLE
restrictToOwner should not throw an error on mass deletions

### ISSUE THREAD

**Issue by thosakwe** [feathersjs/feathers-authentication#175]
Hi guys, really enjoy the work you guys have done. Just one problem.

See, I made this package, [feathers-seeder](https://github.com/thosakwe/feathers-seeder). A key part of its functionality is being able to delete all records from a service if the configuration object dictates to do so.

However, this is prevented by this section of code in `src/hooks/restrict-to-owner.js`:
https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-owner.js#L15-17

```js
if (!hook.id) {
      throw new errors.MethodNotAllowed(`The 'restrictToOwner' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.`);
}
```

So if I call the following, the operation will fail:

```js
service.remove(null, additionalParams);
```

As you can imagine, this renders feathers-seeder more or useless. 

I am going to submit a PR that fixes this. Instead of checking if the hook has an `id`, the code should be changed to see if the `method` matches 'get', 'update', 'patch' or 'remove'.

**Comment by thosakwe** [comment]
Here is the [PR](https://github.com/feathersjs/feathers-authentication/pull/176).

**Comment by ekryski** [comment]
Providing the ability to conditionally run hooks (#210) should solve this problem.

**Comment by ekryski** [comment]
We actually came up with a better solution. You can simply wrap any existing hooks in your own, like so:

```js
import { hooks } from 'feathers-authentication';

exports.hashPassword = function(options) {
  // Add any custom options

  function(hook) {
    return new Promise((resolve, reject) => {
      if (myCondition !== true) {
        return resolve(hook);
      }

      // call the original hook
      hooks.hashPassword(options)(hook)
        .then(hook => {
          // do something custom
          resolve(hook);
        })
        .catch(error => {
          // do any custom error handling
          error.message = 'my custom message';
          reject(error);
        });
    });
  });
}
```

This provides the ultimate flexibility and doesn't require a change to the core hooks.
