### ISSUE TITLE
How do I get the current user id server side?

### ISSUE THREAD

**Issue by codermapuche** [feathersjs/feathers-authentication#178]
Hello, i want a make a simple page that render "Helloo {{USERID}}" if an a user logged or "Hello anonymous" else.

I try with, hook, customs services, and more options but i dont have luck.

` app.get("/hello", function (req, res) {

```
  let userId = ???

  res.send("Hello " + (userId ? userId : "anonymous"));     

});`
```

How i can make its?

Note: if call a find() method of users service i get all users, not the current

**Comment by marshallswain** [comment]
@codermapuche, in this case you're talking about two servers, an SSR server and the API server.  The only way for an SSR server to know who the user is on page load is through a cookie.  So, you'll need to authenticate the user, put the token in a cookie and load the app page.  Then you can read the token out of the `req.cookie`, use something like `jwt-decode` to get the user's `id` from the payload, and then make the `find` request to get the user by `id`.

**Comment by marshallswain** [comment]
The cookie is only for the SSR server to use to make requests.  To avoid CSRF attacks, the API server should not consume the cookie directly.

**Comment by daffl** [comment]
Feathers authentication is using Passport which should be setting `req.user`. Is `req.user` being set?

**Comment by codermapuche** [comment]
@marshallswain, ok, I'll try to change the way the views show, so charge data from the client side

@daffl Not, check all the req and res object and have no property or user info, passport is installed and appears to be used but does not define that property.

**Comment by ekryski** [comment]
@codermapuche check `req.feathers.user`. It should be in there.

**Comment by codermapuche** [comment]
@ekryski  req.feathers is set to: { provider: 'rest', token: undefined } I'm already working on an alternative route, but it would be good that there a way to get this information

**Comment by ekryski** [comment]
@codermapuche did you register your route before authentication was configured or afterward. Just like Express the order matters. Any chance you can put together a gist demonstrating the problem? 😄

**Comment by juodumas** [comment]
I have a similar question, so I have prepared a gist:
https://gist.github.com/juodumas/7aa6de5f1d72d0f419a360a09efe428b

Just save `index.js`, `public/index.html` from the gist, run
* `npm init --yes`
* `npm i feathers-memory body-parser feathers feathers-hooks feathers-rest feathers-authentication`
* `node .`
* Open http://locahost:3031 and click on one of the "Login" buttons.
* Open http://locahost:3031/hello in another tab and check the server console.

What is the easiest path to authenticated server side requests? Or should it work out of the box, as http://docs.feathersjs.com/guides/using-a-view-engine.html seem to indicate?

**Comment by ekryski** [comment]
Thanks @juodumas will take a look this weekend.

**Comment by alisamar** [comment]
I'm still having the authorization issue with cookie. Check the following request:

```
/hello
  req.feathers: { provider: 'rest', token: undefined }
  req.params: {}
  req.user: undefined
  req.headers {
    cookie: 'feathers-jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9....' 
  }
```
Do I need to make an extra settings for cookie verification?

```
  "auth": {
    "token": {
      "secret": "my-secret-code"
    },
    "local": {}
  }
```

**Comment by marshallswain** [comment]
@Luke265 Feathers is going to ignore the cookie.  You need to set it up so that the token in the cookie gets copied to the `Authorization` header.

**Comment by marshallswain** [comment]
@alisamar Same thing applies for the header name.   It needs to be:

```
req.headers {
    cookie: 'feathers-jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9....' 
  }
```

**Comment by alisamar** [comment]
@marshallswain I do not think that such a method would work!


```javascript
    // middleware
    app.use( (req,res,next) => {
        req.headers.Authorization = req.headers.cookie;
        next(); 
    });
```
So, the new question is how do I verify the jwt on the server side for each request and returned to the user data?

**Comment by Luke265** [comment]
@alisamar I did it this way:
`
const jwt = require('jsonwebtoken');
const authConfig = app.get('auth');
function authenticated(req, res) {
    return new Promise((resolve, reject) => {
      let token = req.cookies[authConfig.cookie.name];
      if (!token) {
        reject();
        return;
      }
      jwt.verify(token, authConfig.token.secret, (err, decoded) => {
        if (err) {
          reject();
          return;
        }
        var cookie = authConfig.cookie;
        cookie.expires = new Date(decoded.exp * 1000);
        delete cookie.maxAge;
        res.cookie(cookie.name, token, cookie);
        resolve();
      });
    });
  }`

then you can use it like this:
`this.all('/', (req, res, next) =>
    authenticated(req, res)
      .then(next)
      .catch(() => res.redirect('/login'))
);`

**Comment by ekryski** [comment]
Auth v1.x now automatically shoves the userId in the JWT payload. It is much robust and by default will set it as `userId`. Please see the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) for how to move to the new version.
