### ISSUE TITLE
Make oauth2 more general

### ISSUE THREAD

**Issue by gurisko** [feathersjs/feathers-authentication#179]
The current implementation is not very general:
* assuming `${options.provider}Id` field in a database
* updating a user with all data returned by the passport strategy ([link](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/oauth2/index.js#L46-L66))

This could be solved by allowing to specify a provider field in a database and support a custom hooks.

**Comment by ekryski** [comment]
The second issue is now resolved (yet to be released). I agree, any chance you want to put together a PR for allowing to specify a provider field?

**Comment by gurisko** [comment]
@ekryski Definitely. I will look into this during the weekend.

**Comment by ekryski** [comment]
@gurisko still waiting on that PR :wink: :pray:

**Comment by ekryski** [comment]
This is still on the radar. Steps are being made to make it more general and at a minimum you'll soon be able to extend the service to have your own custom logic without having to rewrite the whole module or all of auth.

**Comment by ekryski** [comment]
This is done and in 0.8-beta. Can be accessed and extended by doing this:

```js
const OAuth2Service = require('feathers-authentication').OAuth2Service

class MyService extends OAuth2Service {

}

app.configure(MyService(options))
```

It is likely that this is moving to it's own repo https://github.com/feathersjs/feathers-authentication-oauth2
