### ISSUE TITLE
REST token revoke

### ISSUE THREAD

**Issue by quick691fr** [feathersjs/feathers-authentication#185]
Hi Guys,

Is there a way to revoke a token using the REST API to perform a logout kind of and prevent the token to be used anymore ?

**Comment by marshallswain** [comment]
Not yet.  We definitely need this.  There's an existing issue, though, so I'll close this one in favor of https://github.com/feathersjs/feathers-authentication/issues/73

**Comment by ekryski** [comment]
@quick691fr Currently left up to you but yes we plan on implementing it in the future.

**Comment by gorork** [comment]
Also interested in this functionality, please update.
