### ISSUE TITLE
Authentication provider for Facebook Account Kit

### ISSUE THREAD

**Issue by ansarizafar** [feathersjs/feathers-authentication#189]
Facebook Account Kit helps you quickly register for apps using just your phone number or email address — no password needed. It's reliable, easy to use and gives you a choice about how you sign up for apps. It would be great If we can use account kit with feathers for authentication.

**Comment by ekryski** [comment]
That'll most likely be a separate module/plugin so that auth doesn't get too bloated.

**Comment by ekryski** [comment]
And what I guess I meant by this is that this is totally open to the community and not something that will get added to core auth (at least not any time soon). We can consider re-opening if more use people need this. Thanks for the suggestion!
