### ISSUE TITLE
Password isn't removed from responses when using a mongoose service for users endpoint 

### ISSUE THREAD

**Issue by corymsmith** [feathersjs/feathers-authentication#19]
Since the user object returned is a Mongoose model, `delete data.password;` doesn't remove the password.

**Comment by ekryski** [comment]
Ah man, this bullshit again... totally fair point. That's such a shitty gotchya though.

**Comment by daffl** [comment]
Should the adapter just always convert the Mongoose models to objects by default for the next version (and hide the old behaviour behind a flag)?

**Comment by ekryski** [comment]
No, because there are times when you want the actual model. I would say it's about 50/50 for wanting the object vs. the model.

Again, maybe we can throw an error possibly??

**Comment by daffl** [comment]
How would you throw an error? I guess the hook in this plugin could just check if you're getting a Mongoose Model and convert it.

**Comment by corymsmith** [comment]
Yeah it's just something that can be converted in the hook, can submit a PR for
it

On Mon, Dec 21, 2015 at 3:44 AM, feathersjs/feathers-authentication
<reply@reply.github.com>
wrote:
How would you throw an error? I guess the hook in this plugin could just check
if you're getting a Mongoose Model and convert it.

—
Reply to this email directly or view it on GitHub
[https://github.com/feathersjs/feathers-authentication/issues/19#issuecomment-166268286] .[https://github.com/notifications/beacon/AAAck1-Wcdq4u2CQ0sQPiYYi0-K7lGl0ks5pR8-egaJpZM4G4yF4.gif]

**Comment by corymsmith** [comment]
Are there other cases with other ORM's that we should handle as well?

**Comment by ekryski** [comment]
@corymsmith nothing that I have seen so far but I haven't tried auth yet with the other ORMs. Mongoose seems to be the only one that returns a collection of models instead of the raw documents.

**Comment by daffl** [comment]
I think Sequelize is returning an array of models, too but you can delete properties so it should be fine.
