### ISSUE TITLE
Authenticated user 

### ISSUE THREAD

**Issue by stjarnstrom** [feathersjs/feathers-authentication#192]
Using the Facebook oath2 settings I've managed to connect and authenticate with Facebook, but every time I authenticate the same user is added to the DB (using NeDB), with the same id, _id and facebookId — over and over.

As if it's not checking if the user exists.

The app was generated with the feathers generate command, and authentication and the like added using the feathers book documentation.

**Comment by marshallswain** [comment]
This is the normal behavior of NeDB.  Here's an example: https://github.com/louischatriot/nedb/issues/410.  See the section on persistence for how to clean it up.  I originally programmed the adapter to automatically compact every 5 seconds, but I'm not sure what it is setup to do right now.

**Comment by marshallswain** [comment]
Please open an issue for the NeDB adapter.  This isn't a problem with the auth plugin.

**Comment by marshallswain** [comment]
And the issue appears to be that the datafile isn't getting compacted often enough.
