### ISSUE TITLE
Check user password

### ISSUE THREAD

**Issue by codermapuche** [feathersjs/feathers-authentication#193]
Hi. I try to build a profile page when the user to update your information is forcet to re-enter your actual password, for this, before update i build a hook to compare the password provided with the current stored:

`    profileUserService.before({`

     patch : [
        auth.verifyToken(),
        auth.populateUser(),
        auth.restrictToAuthenticated(),
	    function(hook) {		  
	      // Only patch current user.
	      hook.id = hook.params.user.id;

	  	  return userService
	  	           .getFull(hook.id)
	  	           .then(function(user) {
		             // How to compare here hook.data.password with user.password???
                             // hook.data.password is not hashed (example: abc123)
                             // user.password is a stored password hash
	  	             throw new errors.BadRequest(`Invalid request`, {
                       errors: [
                         { path: 'password',
                           value: '********',
                           message: `La clave actual es incorrecta`
                         }
                       ]
                     });
	  	           });
	  	}
	  ]
    });

try to hash hook.data.password with hook auth.hashPassword() but every time produces a diferent hash for same password and i can compare it when stored hash.

Any ideas?

**Comment by marshallswain** [comment]
Maybe try using the bcryptjs module directly.

**Comment by daffl** [comment]
As @marshallswain mentioned, you should be able to use [bcryptjs](https://www.npmjs.com/package/bcryptjs) directly:

```js
const bcrypt = require('bcryptjs');

bcrypt.compare(password, user.passwordfield, function(error, result) {
  if (error) {
    // handle crypto error
  } else if (result) {
    // handle success
  } else {
    // wrong password
  }
});
```

I am going to close this. Please reopen if that didn't work for you.
