### ISSUE TITLE
Client side auth should subscribe to user updates so that app.get('user') is fresh

### ISSUE THREAD

**Issue by beevelop** [feathersjs/feathers-authentication#195]
Using the Socket.io adapter, it would be great to automatically subscribe to the user model's changes to reflect those change for `app.get('user')`.

```
// Assuming events are filtered appropriately
app.service('users').on('patched', function(user) {
  app.set('user', user);
});
```

**Comment by ekryski** [comment]
@beevelop I haven't tried this but is it not already possible? Are you thinking server side or client side or both? With feathers-rx this is made a lot easier.

I guess what I'm looking for is:

- Can you not do this?
- What is the use case?

:beers:

**Comment by daffl** [comment]
I was briefly looking into this. I think it is a good idea but the client side authentication currently does not know about the user endpoint so it can't hook into the service events.

**Comment by ekryski** [comment]
@daffl Can it not assume it's `/users` or can we get people to provide an endpoint?

**Comment by beevelop** [comment]
@ekryski This feature would be client-side only and is definitely possible. I use this implementation already, but I think it might be more intuitive to get the latest (patched) user data when calling `app.get('user')` by default or by specifying this behavior explicitly when registering `feathers-authentication` in the frontend.

@daffl: Wouldn't a configuration option to specify the `user` endpoint not meet this problem? You could simply default to `/users`.

**Comment by ekryski** [comment]
I agree. The one thing we'll have to consider is potentially passing a user service, not just an endpoint so that you can potentially be getting user updates from a completely separate backend service, not necessarily the same one as you are authenticating with.

**Comment by ekryski** [comment]
This is going to be left up to the developer because we can't assume that every app will have a user. Therefore:

- we don't want to add more configuration options to enable such functionality on the client at this point.
- and we don't want to be registering socket listeners unnecessarily.
