### ISSUE TITLE
Use feathers-authentication with LDAP / checkPassword() function

### ISSUE THREAD

**Issue by Flos** [feathersjs/feathers-authentication#198]
I try to authenticate to a LDAP server. First I created a Passport "Local" strategy which works and looks like this: 

```
new Strategy(  function(username, password, callback) 
{
    LdapClient.checkPassword(username, password)
      .then(function(user){
        return callback(null, user);
      })
      .fail(function(error){
        return callback(error, false);
      });
  }
)
```

All the ldap code is wrapped in the LdapClient. The LdapClient looks up the user and performs a BIND.
The checkPassword function returns a User if login worked or an error if something failed. 
Now I would like to make the transition to feathers-authentication. 

What I got until now is that the local authentication needs a local user service, which implements a get, and find and requires the passwords to be accessible, which they are mostly not in LDAP. So I cant use the local authentication?

The next I tried was to pass the Strategy to feathers like in the oAuth2 example.

```
var Strategy = require('passport-local').Strategy;

app.configure(authentication({
  ldap: {
    strategy: new Strategy( ... same code as above...
  }
}));
```

But that fails with "provider not defined", 

What is the correct way to realize that?

**Comment by nyaaao** [comment]
You'd want to set the `strategy` property inside `services/authentication/index.js` like this:
```js
'use strict';

const authentication = require('feathers-authentication');

const FacebookStrategy = require('passport-facebook').Strategy;

module.exports = function() {
  const app = this;

  let config = app.get('auth');

  config.facebook.strategy = FacebookStrategy;

  app.set('auth', config);
  app.configure(authentication(config));
};
```

**Comment by Flos** [comment]
Sorry but I don't get the full idea behind it.

Are you recommending me to clone the repository to create the `services/authentication/index.js` file? 
I would prefer a solution which allows me to just uses the repository as it is.

after creating the file: `services/authentication/index.js`
```
use strict';

const authentication = require('feathers-authentication');

const LdapStrategy = require('passport-local').Strategy;

const LdapClient = require ('ldap-client');

module.exports = function() {
  const app = this;

  let config = app.get('auth');

  config.local.strategy = new LdapClient(  function(username, password, callback)
                          {
                            LdapClient.checkPassword(username, password)
                              .then(function(user){
                                return callback(null, user);
                              })
                              .fail(function(error){
                                return callback(error, false);
                              });
                          }
                        )

  app.set('auth', config);
  app.configure(authentication(config));
};
```

How shall I now use that? 
What endpoint should I set in the client to use that?

**Comment by Flos** [comment]
Im busy with this. I cant get it to work. 
I tried to add a ldap authentication method, starting with a copy of the local authentication method. But thats also not the way to do it. Since there are checks only for 'local' and 'token' providers in authentication middleware and if string don't match exception is trown or oauth authentication is expected.

The solution from @nyaaao looks nice, but I don't understand how that should work, and I don't get it working.

Any help is welcome,
Thanks

**Comment by acao** [comment]
I'm going to give this a try, but I think what @nyaaao suggested would look like this with LDAP:

```js
import authentication from 'feathers-authentication';

import { Strategy as LdapStrategy } from 'passport-ldapauth';

export function example() {
  const app = this;

  let config = app.get('auth');

  config.facebook.strategy = {
    ldap: {
       strategy: LdapStrategy,
       server: {
           url: 'ldap://localhost:389',    
        }
        /// other passport-ldapauth options
     }
  };
  app.set('auth', config);
  app.configure(authentication(config));
};
```

**Comment by netzwerch** [comment]
Thanks for your ideas, it looks like good solution, but it is not working this way.
Setting config.ldap or config.facebook does not change anything. One must name it config.local or config.token, but that will only configure the build in auth providers as seen in the docs. Any other name is expected to make use of the build in oauth2 provider. When oauth2 is not configured as expected it will result in an "is not a function error" in https://github.com/feathersjs/feathers-authentication/blob/master/src/index.js#L142

So I see two solutions:
- Use Oauth2 (an Authorization Server in front of LDAP is required)
- Create a new provider (next to local, token and oauth2) in feathers-authentication that allows setting getUser or checkPassword callbacks

We currently get along with a private fork where we patched the /auth/local service with our ldap-backend. It's not the best solution but it works.

**Comment by saulide** [comment]
@netzwerch could you provide some more details of your workaround? If feathersjs doesn't work convenient with ldap, it's a dealbreaker for my new project

**Comment by netzwerch** [comment]
@saulide, I changed src/services/local.js, so it uses our own ldap-connector (based on ldapjs) for password check and retrieving the user profile, that´s being achieved by rewriting `checkCredentials()`.
Additionally I got inspiration from src/services/oauth2.js, because a user needs to be created when it does yet not exist in the local ¨/user¨ service or updated on a following login.

**Comment by netzwerch** [comment]
Seems there is something in the pipeline regarding authentication in general: https://twitter.com/feathersjs/status/784213954042138626

**Comment by psi-4ward** [comment]
Hey, seems its pretty easy to write a LDAP Strategy for version 1.0

```javascript
// feathers-authentication-ldap.js
const debug = require('debug')('feathers-authentication-ldap');
const merge = require('lodash.merge');
const omit = require('lodash.omit');
const LdapStrategy = require('passport-ldapauth').Strategy;

const defaults = {
  name: 'ldap',
  server: {
    url: 'ldap://localhost:389',
    bindDn: 'cn=anonymous',
    bindCredentials: '',
    searchBase: 'dc=de',
    searchFilter: '(uid={{username}})',
    searchAttributes: null
  },
  passReqToCallback: true
};


function defaultVerifier(req, user, done) {
  // no further validation, LDAP Account is valid
  done(null, user);
}

module.exports = function init(options = {}) {
  return function ldapAuth() {
    const app = this;
    if(!app.passport) {
      throw new Error(`Can not find app.passport. Did you initialize feathers-authentication before feathers-authentication-ldap?`);
    }

    let name = options.name || defaults.name;
    let authOptions = app.get('auth') || {};
    let localOptions = authOptions[name] || {};
    const localSettings = merge({}, defaults, localOptions, omit(options, ['Verifier']));

    let verifier = defaultVerifier;
    if(options.Verifier) verifier = options.Verifier;

    app.setup = function() {
      if(!verifier) throw new Error(`Your verifier must be a function: Verifyer(request, user, done)`);

      // Register 'ldap' strategy with passport
      debug('Registering ldap authentication strategy with options:', localSettings);
      app.passport.use(localSettings.name, new LdapStrategy(localSettings, verifier));
      app.passport.options(localSettings.name, localSettings);

      return app.setup.apply(this, arguments);
    }
  };
};
```

```json
// default.json config
"auth": {
    "secret": "super secret",
    "token": {
    },
    "ldap": {
      "server": {
        "url": "ldap://myldap:389",
        "bindDn": "cn=users,ou=people,dc=asd,dc=de",
        "bindCredentials": "secret",
        "searchBase": "dc=asd,dc=de",
        "searchFilter": "(uid={{username}})",
        "searchAttributes": ["uid", "cn", "mail", "mobile", "memberOf"]
      }
    }
  }
```

```javascript
// app.js
  .configure(auth(app.get('auth')))
  .configure(jwt())
  .configure(ldap({
    Verifier: function(req, user, done) {
      // additional checks
      if(user.memberOf.indexOf(memberOf) === -1) {
        return done(new errors.Forbidden('User not in Group: '+memberOf));
      }
      delete user.memberOf;
      done(null, user);
    }
  }))
```

**Comment by ekryski** [comment]
@psi-4ward interested in turning that into a complete plugin? Happy to spin up a repo for ya 😄

**Comment by ekryski** [comment]
With auth v1.x there is now an official LDAP plugin. https://github.com/feathersjs/feathers-authentication-ldap
