### ISSUE TITLE
Login validation

### ISSUE THREAD

**Issue by KristofferHebert** [feathersjs/feathers-authentication#2]
Hello,

On my project. It seems posting to /api/logins give you a token, no matter what. How would you use hooks for validation on the existing api/login route? Is there another way to validate the logins?

**Comment by marshallswain** [comment]
Can you give me some more details on what type of validation you are trying to do?  If you're getting a token even if you post an empty body or random information, that's a bug.  Please let me know if that's the case.

`/api/login` (no 's') is intended to be an endpoint specifically for (1) turning username/password data into a token or (2) exchanging an existing token for a fresh one.  

For (1) above, It's only validating that the user exists and that the password is correct.  If that validation passes, it gives a token back.  That token is then passed in to the socket connection or as the Authentication header in an Ajax call.  The `feathers-authentication` plugin will validate the token and set it up as the user that you can use in conjunction with feathers-hooks.

**Comment by KristofferHebert** [comment]
Doing a empty post request to /api/login returns a valid auth token.
Doing a post request to /api/login with invalid credentials returns a valid
auth token.

I put a authentication hook on my users and I am able to do crud actions
with the bearer token.



If you want to look at my code, here it is.

https://github.com/KristofferHebert/feathers-es6-passport

**Comment by marshallswain** [comment]
Wow. That's such a user friendly login. So trusting! That should be a
simple fix. If you want to give it a shot, I'd love help. Thank you for
reporting. I should have an evening this week to work on it.

**Comment by marshallswain** [comment]
@KristofferHebert It's taking me longer than usual to finish everything thanks to some guy who stole my laptop.  I had a couple minutes to work on it today and just pushed a commit that I think has solved the problem.  I'll be adding tests for it, soon, but if you wouldn't mind trying it out, I'd very much appreciate it.

**Comment by KristofferHebert** [comment]
It looks like api/login has been secured. However I am no longer able to login. Is it just me?

**Comment by marshallswain** [comment]
I'm having pretty good luck with it in its current state.  Have you debugged to see where it is failing?

**Comment by marshallswain** [comment]
@KristofferHebert I'm going to close this since it's working for me.  If you are still having issues, please reopen.
