### ISSUE TITLE
how to use successRedirect with a single page application ?

### ISSUE THREAD

**Issue by quentin-sommer** [feathersjs/feathers-authentication#202]
I'm using AngularJS 1 on the frontend with ui-router as router, and I have no idea how to implement feather's OAuth2.

Normally the app use `host/#/url/path` but with the redirect it becomes `host/auth/success#_=_` and it shows the feathers default success view. How can I redirect to my app so that ui-router is triggered ? for example to `host/#/auth/success`

**Comment by daffl** [comment]
Did you try setting the [sucessRedirect option](http://docs.feathersjs.com/authentication/readme.html#options)? We also show it in the guide [here](http://docs.feathersjs.com/getting-started/user-management.html#signing-up-new-users).

**Comment by quentin-sommer** [comment]
I managed to get it working by using an ui-router friendly url : `"successRedirect": "/#/success"` and then catch it like this with ui-router 
```` javascript
    .state('auth_success', {
      url:'/success'
    });
```
Thanks!

**Comment by quentin-sommer** [comment]
Well I spoke too fast, using `/#/success` to trick angular's router the cookie is set on the path `/#/success`, whereas angular locates itself at `/` and then append `#/success` to it, so the cookie is not reachable. To make it work I used the `/` url and did a dirty-checking on the cookie existence at each page reload.

**Comment by ekryski** [comment]
So sounds like you did manage to get it working @quentin-sommer? Would you mind closing if so?

Usually what we do is have the non-app (ie. a marketing site) have your login button and then when you redirect you go to the actual app and you are already authenticated. Dealing with routing for auth in an app is doable but kind of a pain.

**Comment by quentin-sommer** [comment]
Using a different site to authenticate make sense, didn't thought about it at first! 

I'm closing this issue, I managed to get it working by checking at every page refresh if an Auth cookie is set 

Cheers
