### ISSUE TITLE
OAuth2 Facebook Config

### ISSUE THREAD

**Issue by Synvox** [feathersjs/feathers-authentication#206]
This is more a question than anything, but after doing some searching around, I still have not been able to find a standard way to extract extra information from a Facebook login.

I have `public_profile` and `email` defined on my scope in my permissions and all I want to do is cherry-pick these and include them when the user is created.

Is there documentation on how to do this?

**Comment by ekryski** [comment]
Hey @Synvox! Simply add a `before` hook for updates and creates on your user service to set up your user fields for how you want to store them.

**Comment by Synvox** [comment]
Alright. That makes sense, but how would I read facebook into that hook? Is there any example I can look at?

**Comment by daffl** [comment]
The information is already included in `data.facebook`. To map them to the fields you mentioned can be done in a before `create` and `patch` hook like this:

```js
app.service('users').before({
  create(hook) {
    const facebookInfo = hook.data.facebook;

    hook.data.public_profile = facebookInfo.public_profile;
    hook.data.email = facebookInfo.email;
  },

  patch() {
    const facebookInfo = hook.data.facebook;

    hook.data.public_profile = facebookInfo.public_profile;
    hook.data.email = facebookInfo.email;
  }
});
```

**Comment by Synvox** [comment]
Awesome. That is exactly what I am looking for. Thank you for making such an awesome tool!
