### ISSUE TITLE
Getting 401 Errors while trying to authenticate

### ISSUE THREAD

**Issue by silvestreh** [feathersjs/feathers-authentication#207]
Bare with me, the snippets might get long…

So I'm prototyping a rather small app and only focusing on user authentication for now. I'm using `feathers-cli` to generate the application and its services using MongoDB for data persistence. Apart from the models for the services I've not touched any of the generated code.

I'm using Vue.js for the client (generated using `vue-cli`'s webpack template). For now, I made a [Vue plugin](https://vuejs.org/guide/plugins.html) to share an instance of the `feathers-client` and its services between components. I should probably refactor this using Vuex later on.

```javascript
// feathers.js
import 'babel-polyfill';
import feathers from 'feathers/client';
import socketio from 'feathers-socketio/client';
import authentication from 'feathers-authentication/client';
import hooks from 'feathers-hooks';
import io from 'socket.io-client';

const socket = io(`${(location.protocol || 'http:')}//${location.hostname}:3030`);

const app = feathers()
    .configure(hooks())
    .configure(socketio(socket))
    .configure(authentication({
        storage: window.localStorage
    }));

export default {
    install(Vue) {
        Vue.prototype.feathers = app;
        Vue.prototype.userService = app.service('users');
    }
};
```

I then tell Vue to use this plugin before creating the Vue instance I'll be using…

```javascript
// main.js
import Vue from 'vue';
import feathers from './feathers'; // <- this right here is the previous snippet
import App from './App.vue';

Vue.use(feathers); // <- and I'm registering the plugin

/* eslint-disable no-new */
new Vue({
    el: 'body',
    components: { App }
});
```

And this is what my `App.vue` component looks like (please note that I separated it into two snippets to take advantage of code hightlight, but in reality is a single `.vue` file which Webpack transforms using `vue-loader`) …

```html
<!-- App.vue -->
<div id="app">
    <form>
        <fieldset>
            <legend>Sign in</legend>
            <input type="email" placeholder="E-mail" v-model="email">
            <input type="password" placeholder="Password" v-model="password">
            <button @click.prevent="signIn">Sign in</button>
        </fieldset>
    </form>
    <form>
        <fieldset>
            <legend>Sign up</legend>
            <input type="email" placeholder="E-mail" v-model="email">
            <input type="password" placeholder="Password" v-model="password">
            <button @click.prevent="signUp">Sign up</button>
        </fieldset>
    </form>
    <pre>{{ status | json }}</pre>
</div>
```

```javascript
// App.vue
export default {
    data() {
        return {
            email: '',
            password: '',
            status: ''
        };
    },

    methods: {
        signIn() {
            this.$root.feathers.authenticate({
                type: 'local',
                email: this.email,
                password: this.password
            }).then((result) => {
                this.status = result;
                console.log('Authenticated!', result, this.$root.feathers.get('token'));
            }).catch((error) => {
                this.status = error;
                console.error(error);
            });
        },
        signUp() {
            this.$root.userService.create({
                email: this.email,
                password: this.password
            }).then((result) => {
                this.status = result;
                console.log(result);
            }).catch((error) => {
                this.status = error;
                console.error(error);
            });
        }
    }
};
```

OOOK… as you can see, I'm using web sockets. User creation works as expected and I can populate my database alright. But when it comes to authenticating the very user I just created I keep getting a `401` error:

```json
{
  "name": "NotAuthenticated",
  "message": "Invalid login.",
  "code": 401,
  "className": "not-authenticated",
  "errors": {}
}
```

I tried creating the same user just to check if it really existed and I got the expected dupe error:

```json
{
  "code": 11000,
  "index": 0,
  "errmsg": "E11000 duplicate key error collection: binary.users index: email_1 dup key: { : \"user@host.com\" }",
  "op": {
    "email": "user@host.com",
    "password": "$2a$10$7bh56mp3u25crpxxxwiee.mhfkfkf5b.5zihhlp6018hhqq6ccrek",
    "_id": "573ba2dce3d6027848e3b942",
    "updatedAt": "2016-05-17T23:01:48.163Z",
    "createdAt": "2016-05-17T23:01:48.163Z",
    "__v": 0
  }
}
```

I went ahead and checked in Chrome's Dev Tools if I was sending the data over the socket and, to my (very limited) understanding, I am:

`42["authenticate",{"type":"local","email":"user@host.com","password":"pass"}]`

At this point I thought I was doing something wrong due to my limited understanding of web sockets, so I fired up Postman to do the very same tasks over REST. I `POST`ed to `http://localhost:3030/users` to create a user. No problem, the new user is there.

Now I tried to `POST` to `http://localhost:3030/auth/local` using the same values (I didn't reset the Postman form, I merely changed the `URL` I would be `POST`ing to) and got the `401` error page in the response's body (which I won't copy in a snippet because I'm pretty sure you know it well.)

Like I said, I barely touched the generated Feathers code. My `src/services/authentication/index.js` file looks like this:

```javascript
// src/services/authentication/index.js
'use strict';

const authentication = require('feathers-authentication');


module.exports = function () {
    const app = this;

    let config = app.get('auth');



    app.configure(authentication(config));
};
```

And my `default.json` config file looks like:

```json
{
    "host": "localhost",
    "port": 3030,
    "mongodb": "mongodb://localhost:27017/binary",
    "public": "../public/",
    "auth": {
        "token": {
            "secret": "Pb6YEV7Sc6M8rO1T/7GSMlfzhIjKOAv2/rmoj5oowuZxp4ycnJ9sGdMezYMiwh5LxzU6zc61Xa4ogXp7KPIKmw=="
        },
        "local": {}
    }
}
```

I ran out of ideas and @daffl suggested to move the conversation to GitHub 'cause it was hard to keep track of the problem in Slack. So here I am. Posting an issue.

These are the feathers packages I'm using server-side.

```json
{
    "feathers": "2.0.1",
    "feathers-authentication": "0.7.7",
    "feathers-configuration": "0.2.3",
    "feathers-errors": "2.1.0",
    "feathers-hooks": "1.5.3",
    "feathers-mongoose": "3.3.7",
    "feathers-rest": "1.3.0",
    "feathers-socketio": "1.4.0",
}
```

And on the client

```json
{
    "feathers": "2.0.1",
    "feathers-authentication": "0.7.7",
    "feathers-hooks": "1.5.3",
    "feathers-socketio": "1.4.0",
    "socket.io-client": "1.4.6",
}
```

Thanks and sorry for the lengthy post! 😄

**Comment by marshallswain** [comment]
Can you make a repo that I can clone?

**Comment by daffl** [comment]
What does your user service look like? What is the output if you run the app with the `DEBUG=feathers*` environment variable set (this should get you a bunch of information as mentioned in the [debugging chapter](http://docs.feathersjs.com/debugging/readme.html)).

**Comment by silvestreh** [comment]
@marshallswain here's the repo `git@gitlab.com:silvestre.herrera/feathers-test.git`. It's a clean feathers instance. No code has been modified after being generated by `feathers-cli`. There's a `server/` and a `client/` directory. The `server/` holds Feathers' code and in the `client/` directory is a simple Vuejs app.

@daffl The user service was not touched. I'm pretty sure I'm doing something wrong in the client side as the backend code is a clean feathers instance.

**Comment by silvestreh** [comment]
Oooook… looks like I solved my issue. It was a rather strange one. Vue.js' webpack template offers to set up a proxy table so you can reach your API server. Here's what Vue.js' config looks like:

```javascript
// see http://vuejs-templates.github.io/webpack for documentation.
var path = require('path');

module.exports = {
    build: {
        index: path.resolve(__dirname, 'dist/index.html'),
        assetsRoot: path.resolve(__dirname, 'dist'),
        assetsSubDirectory: 'static',
        assetsPublicPath: '/',
        productionSourceMap: true
    },
    dev: {
        port: 3000,
        proxyTable: {
            '/api': {
                target: 'http://localhost:3030',
                changeOrigin: true,
                pathRewrite: {
                    '^/api': ''
                }
            }
        }
    }
};
```

After commenting out the whole `/api` key in the `proxyTable` object everything went back to normal and I can finally authenticate users.

After fiddling with this for about a day it finally came to mind that I didn't quite need the proxy beacuse of the way I'm using Feathers on the client (connecting directly to the `localhost:3030` through a socket) and thus I removed the above code.

I'm still not sure why it wouldn't work. Again, my understanding of these things is quite limited and I try to push myself forward and learn them.

Anyway, thank you guys for your help!

**Comment by silvestreh** [comment]
Well I be damn… it stopped working again. I'm clueless.

**Comment by silvestreh** [comment]
Must be something on my system as it seems to work just fine elsewhere. So yeah, I'd say you might not want to waste time on this one.
