### ISSUE TITLE
Hooks should support a callback for conditionally running

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#210]
Much [like our other built-in hooks](https://github.com/feathersjs/feathers-hooks/blob/master/src/bundled.js#L16) you should be able to pass a callback to determine whether the hook should be run.

Usage would be very similar. [See docs](http://docs.feathersjs.com/hooks/bundled.html).

**Comment by ekryski** [comment]
We are going to be deprecating the callback functionality in the other hooks as we have come up with a better, more flexible solution. You can simply wrap any existing hooks in your own, like so:

```js
import { hooks } from 'feathers-authentication';

exports.hashPassword = function(options) {
  // Add any custom options

  function(hook) {
    return new Promise((resolve, reject) => {
      if (myCondition !== true) {
        return resolve(hook);
      }

      // call the original hook
      hooks.hashPassword(options)(hook)
        .then(hook => {
          // do something custom
          resolve(hook);
        })
        .catch(error => {
          // do any custom error handling
          error.message = 'my custom message';
          reject(error);
        });
    });
  });
}
```

**Comment by DominikTrenz** [comment]
There is a error in the example.
`function(hook) {`
should be
`return function(hook) {`
