### ISSUE TITLE
Getting token via REST is not documented

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-authentication#216]
It comes up all the time and I couldn't find it either. There is some docs at http://docs.feathersjs.com/authentication/readme.html#authentication-over-rest but it doesn't say anywhere that you have to `POST` to `auth/local` (or the local endpoint).

**Comment by mmwtsn** [comment]
Thanks for pointing me in the right direction earlier.

I'll open a pull request to update the docs in the morning tomorrow.
