### ISSUE TITLE
How to figure out why redirect to /auth/failure?

### ISSUE THREAD

**Issue by dfischer** [feathersjs/feathers-authentication#217]
I'm getting a redirect to http://localhost:3030/auth/failure and I'd like to investigate why. There's nothing in the server logs. What can I do to investigate?

**Comment by dfischer** [comment]
Ran with debug to get what I needed. Thanks Docs! :) `DEBUG=* npm start`

**Comment by ekryski** [comment]
Yeah I don't love the redirect actually as it just catches any error that happens during auth flow but we'll leave it for now and come up with a better solution.

**Comment by jordanbtucker** [comment]
@dfischer Where did you set a break point to determine why it's failing?
