### ISSUE TITLE
Server-side header option does not accept capital letters

### ISSUE THREAD

**Issue by mmwtsn** [feathersjs/feathers-authentication#218]
#### Issue

RESTful authentication fails if the optional `header` key in the [server-side configuration options](http://docs.feathersjs.com/authentication/readme.html#options) includes capital letters.

#### Background

I brought this up in the [Slack channel](https://feathersjs.slack.com/archives/general/p1464967390004911) yesterday and @ekryski asked that I open an issue with steps to reproduce the problem. This happens because internally Node's http module lower cases all headers names to normalize their values. If a user attempts to configure their authentication options with a header that includes capital letters lookup inside [`src/middleware/express.js`](https://github.com/feathersjs/feathers-authentication/blob/master/src/middleware/express.js#L35) fails.

For example, this configuration:

```js
// Application setup
.configure(authentication({ header: 'X-Auth-Token' })
```

Causes the following situation internally wen a POST request is made with a `X-Auth-Token` header:

```js
// Express middleware
console.log(options.header);              // => 'X-Auth-Token'
console.log(req.headers['x-auth-token']); // => token
console.log(req.headers['X-Auth-Token']); // => undefined
```

#### Steps to reproduce

1. Clone the repository locally and `cd` into the project root.

1. Open `example/app.js` in your text editor.

1. Add the optional `header` value with inside `example/app.js`:

  ```diff
diff --git a/example/app.js b/example/app.js
index 444ad12..9c52a6b 100644
--- a/example/app.js
+++ b/example/app.js
@@ -17,7 +17,8 @@ var app = feathers()
   .use(bodyParser.urlencoded({ extended: true }))
   // Configure feathers-authentication
   .configure(authentication({
-    idField: 'id'
+    idField: 'id',
+    header: 'X-Auth-Token'
   }))
   // Initialize a user service
   .use('/users', memory())
```

1. Set up the example server:

  ```bash
$ npm install
$ node example/app.js
Feathers authentication app started on 127.0.0.1:3030
```

1. In a new terminal session, create a new token using the default user:

  ```bash
$ curl -X POST \
-H 'Content-Type: application/json' \
-d '{ "email": "admin@feathersjs.com", "password": "admin" }' \
http://127.0.0.1:3030/auth/local
```

1. Use the token to view a restricted resource:

  ```bash
$ curl -X GET \
-H 'X-Auth-Token:$YOUR_TOKEN_FROM_ABOVE' \
http://127.0.0.1:3030/messages
```

  Despite using the header I configured the app to use this request fails for me.

**Comment by mmwtsn** [comment]
This is a little bit confusing right now because:

- the server-side config uses a lowercase default (`authorization`)
- the client-side config uses an uppercase default (`Authorization`)

As Eric pointed out in Slack the Node default is lowercase header values. I think it makes sense to move forward with and align both the server- and client-side defaults to that standard.

**Comment by marshallswain** [comment]
Stellar issue report, BTW.  I think it makes sense to lowercase everywhere.

**Comment by mmwtsn** [comment]
Sweet.

Do you mind if I push it up to #219 as well?

Here's the diff:

```diff
diff --git a/src/client/hooks.js b/src/client/hooks.js
index 35a4551..ab0b7ad 100644
--- a/src/client/hooks.js
+++ b/src/client/hooks.js
@@ -13,7 +13,7 @@ export function populateHeader(options = {}) {
   return function(hook) {
     if (hook.params.token) {
       hook.params.headers = Object.assign({}, {
-        [options.header || 'Authorization']: hook.params.token
+        [options.header || 'authorization']: hook.params.token
       }, hook.params.headers);
     }
   };
diff --git a/test/integration/rest.test.js b/test/integration/rest.test.js
index b59a7f6..2ddd748 100644
--- a/test/integration/rest.test.js
+++ b/test/integration/rest.test.js
@@ -259,7 +259,7 @@ describe('REST authentication', function() {
             method: 'GET',
             json: true,
             headers: {
-              Authorization: validToken
+              authorization: validToken
             }
           };
         });
```

**Comment by ekryski** [comment]
@mmwtsn Yeah man! Thanks for the stellar issue!

Yeah I think that's just fine to push it up.
