### ISSUE TITLE
Feathers-authentication assumptions

### ISSUE THREAD

**Issue by dfischer** [feathersjs/feathers-authentication#220]
I am trying to leverage the `add to slack` button from Slack's API which is an oauth negotiation to get back some tokens.

This means I don't want to create a user. Right now leveraging the flow through feathers-authentication causes a user to be created. Additionally, I need to grab other things from the payload from Slack but I'm not understanding how to do that. It's in the response but need to do further things with creating another service (i.e Integration). Is there a way to do a callback of some sort?

Is it in feathers-authentication's vision to support bypassing creating a user, or should I drop down to express and leverage vanilla passport?

**Comment by marshallswain** [comment]
@dfischer if you need stuff from the Slack response payload, why not turn the users service into a memory store? You could clear the record from the memory store after you grab the data you want from the Slack payload, so it won't be sitting around.

**Comment by daffl** [comment]
Another option would be to skip the user creation in a [before hook](http://docs.feathersjs.com/hooks/usage.html#before-hooks) if it has the Slack payload:

```js
app.service('users').before({
  create(hook) {
    if(hook.data.slack) {
      hook.result = hook.data;
    }
  }
});
```

**Comment by dfischer** [comment]
@daffl how would I then grab that hook data into, let's say, an integration service that the goal is to save the slack data into that object (Integration object)

**Comment by ekryski** [comment]
Both are pretty solid options there. I'll throw another in the ring. You could have your own custom user service that does whatever custom stuff you wanna do inside of it. It's kind of bastardizing the concept but might do the trick for you.

**Comment by dfischer** [comment]
Thanks guys!
