### ISSUE TITLE
Can I extend buildCredentials function?

### ISSUE THREAD

**Issue by aa403210842** [feathersjs/feathers-authentication#221]
I looked into buildCredentials function source code:

``` js
  buildCredentials(req, username) {
    const usernameField = this.options.usernameField;
    return new Promise(function(resolve) {
      const params = {
        query: {
          [usernameField]: username
        }
      };
      resolve(params);
    });
  }
```

can I use "extend" here?

``` js
let config = app.get('auth')
  app.configure(authentication(config).extend({
    buildCredentials(req, username) {
      //Some customized logic here
    }
}))
```

**Comment by marshallswain** [comment]
@aa403210842 that's what it was designed to do, actually.  Have you tried it out, yet?

**Comment by aa403210842** [comment]
@marshallswain seems `.extend` not working, according to FeatherJs doc, extension function is provided by Uberproto, so I was wandering if we can add Uberproto in to this?

**Comment by ekryski** [comment]
@aa403210842 if you are using ES6 syntax you don't need to use the uber proto style extend but in either case you definitely should be able to extend. I'll have to see what is going on and probably add a test for this.

**Comment by ekryski** [comment]
So I actually had the need to try and extend the local service and it's not really possible with the way that things are structured and the services are initialized. Going to look at how we can refactor to make this more flexible. This is directly related to #226

**Comment by ekryski** [comment]
`buildCredentials` no longer exists in the new version of auth. Instead you can simply [extend the verifier](https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier) for each auth provider if you need to query by different information.
