### ISSUE TITLE
Cannot read property \'service\' of undefined

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers-authentication#222]
There is my code:
https://github.com/kozzztya/share-debt/tree/36cf4897219d4ac218a9a6210ab279de53269445
After test running `./node_modules/.bin/ava test/debt-add.test.js` I have an error on login:
```
Cannot read property \'service\' of undefined
```
Can you look what's wrong?

**Comment by daffl** [comment]
Usually this happens when `app.setup` isn't called. This normally happens when the server is started through something other then `app.listen`.

**Comment by kozzztya** [comment]
I called it without any success https://github.com/kozzztya/share-debt/blob/36cf4897219d4ac218a9a6210ab279de53269445/src/index.js#L6
Also I didn't use sub app like in previous issues with the same error.

**Comment by kozzztya** [comment]
And I didn't see in examples of feathers-auth using `app.configure(services())`. Am I calling all stuff in the right order?

**Comment by daffl** [comment]
It looks like you are configuring authentication twice, once in https://github.com/kozzztya/share-debt/blob/36cf4897219d4ac218a9a6210ab279de53269445/src/app.js#L19 and another time in https://github.com/kozzztya/share-debt/blob/36cf4897219d4ac218a9a6210ab279de53269445/src/services/auth/index.js. If you remove https://github.com/kozzztya/share-debt/blob/36cf4897219d4ac218a9a6210ab279de53269445/src/app.js#L19 everything will probably work.

**Comment by kozzztya** [comment]
I tried to configure auth in different places. That what I forget to delete.
Still have the same issue with `app.configure(authentication())` only in app.js.

**Comment by kozzztya** [comment]
app.setup wasn't called in test env. thanks for help.
