### ISSUE TITLE
Deprecate verifyToken and populateUser hooks in favour of middleware

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#227]
Adding the existing hooks every time is tedious and redundant. Typically you want to verify the token and populate the user on every request anyway.

The middleware will be set up automatically for you and if a token isn't passed in it will just call `next()`. It is still up to the developer to add a hook to `requireUser` (or something) for each service method that should require authentication.

I'm thinking we expose the middleware like so:

``` js
import { validateToken, populateUser } from 'feathers-auth/middleware';
```

so that people can monkey with them or use them standalone outside of feathers-auth. We might want ability to pass a config option to not load the user or have people set up this middleware explicitly in case you don't want to lookup the user every time a request is made.

**Comment by daffl** [comment]
Related: https://github.com/feathersjs/feathers/issues/357

**Comment by ekryski** [comment]
This is coming down the pipe and is implemented in the `passwordless` branch.

**Comment by ekryski** [comment]
This has been completely revamped and these hooks no longer are used/required. Please see the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) for how to upgrade from auth <0.8.0 to v1.x.
