### ISSUE TITLE
restrictToOwner does not support multi patch, update and remove

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-authentication#228]
It also throws a weird error in https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-owner.js#L15 due to `id` being `null`.

**Comment by ekryski** [comment]
Ya we should be checking the method instead of assuming the id is present.

**Comment by petermikitsh** [comment]
When should I anticipate the arrival of the v0.8 release? Just noticed this bug.
