### ISSUE TITLE
Is there an Authenticated Event

### ISSUE THREAD

**Issue by imns** [feathersjs/feathers-authentication#235]
Is there an event that gets fired when a user is authenticated / unauthenticated?  I don't see anything in the docs about it.

My application state needs to change when a User's signs in and out.

**Comment by marshallswain** [comment]
You can create custom events for this: http://docs.feathersjs.com/real-time/events.html

**Comment by marshallswain** [comment]
If you need to only send the authenticated event to certain users, you'll need to use http://docs.feathersjs.com/real-time/filtering.html

**Comment by imns** [comment]
So, I'm assuming I would create an after `create` hook for the Authentication service and emit my custom event there?

**Comment by marshallswain** [comment]
Yeah.

**Comment by marshallswain** [comment]
You can access the app at `hook.app`

**Comment by imns** [comment]
Awesome, thanks for the quick replies @marshallswain.
