### ISSUE TITLE
Custom Authentication Hooks

### ISSUE THREAD

**Issue by imns** [feathersjs/feathers-authentication#236]
Is is possible to create custom authentication hooks?  I need to preform some actions after a user is authenticated and a hook seems like the appropriate thing to use.

If so, how would I go about doing it, since the authentication service is not created like other services it has me a little confused.

```
const authentication = require('feathers-authentication');

module.exports = function() {
    const app = this;
    let config = app.get('auth');

    app.configure(authentication(config));
};

```

**Comment by marshallswain** [comment]
The auth services are available for lookup the same as with other services.  So you can do `app.service('auth/local').after(...)` or `app.service('auth/token').after(...)` for example.

**Comment by marshallswain** [comment]
If you need to modify an OAuth flow, use the users service.

**Comment by imns** [comment]
Excellent, thank you!
