### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by tudurom** [feathersjs/feathers-authentication#24]
Using the example on the README page it gives me the following error when I try to log in:

```
TypeError: Cannot read property 'token' of undefined
   at verifyToken (/home/tudurom/squirrel/squirrel.server/node_modules/feathers-authentication/lib/index.js:166:17)
```

**Comment by marshallswain** [comment]
It looks like your request is missing a body, or it might be due to the missing `.use(bodyParser.json())` just before the `.use(bodyParser.urlencoded({ extended: true }))` in the server setup.

I'm updating the README.md right now.  I'll let you know when it's done.

**Comment by marshallswain** [comment]
I've updated the README with a short tutorial on getting up and running.  Let me know if you run in to anything else.  Thanks for your feedback.

**Comment by tudurom** [comment]
It works! Thank you very much! The problem was I was loading the modules in a random order.

**Comment by marshallswain** [comment]
You are welcome.  Have fun!
