### ISSUE TITLE
Responses hang when token.secret is undefined for local authentication

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-authentication#249]
If authentication config value `token.secret` is set to `null` or `undefined`, successful local authentication attempts will hang. Unsuccessful authentication attempts will return 401 as expected.

Probably should yell at the developer for improper usage, perhaps with some sort of warning message :)

**Comment by ekryski** [comment]
Coming in the next 0.8 release. 😄  Thanks for reporting @petermikitsh!

**Comment by ekryski** [comment]
This is now fixed in v1.x. If a token secret is falsey we toss an error on app startup.
