### ISSUE TITLE
0.8: Token Service errors on token auth using client

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#254]
On this line: https://github.com/feathersjs/feathers-authentication/blob/0.8/src/services/token.js#L144
```
jwt.sign(data, secret, options, (error, token) => {
```

If you pass in any of the following combinations, you get an error from the `jsonwebtoken` package:

`data.iss && options.issuer`
`data.sub && options.subject`
`data.exp && options.expiresIn`

**Comment by ekryski** [comment]
fixed with #225.
