### ISSUE TITLE
Add support for authenticating active users only

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers-authentication#259]
Hi,
I think it's not an uncommon scenario that user database contains both active and inactive users (=that can't login). It would be great that if authentication could allow only active users (like active=true in user database entry).

As far as I know, there is not easy way to do this now, right?

**Comment by marshallswain** [comment]
You can create hooks on either the auth/local or auth/token service that would allow you to control this, now.

**Comment by Mangatt** [comment]
Do you have any suggestion how to do that? I have tried to add param to hook, but without much success.

```javascript
app.service('auth/local').before({
	all(hook){
		hook.data.active=false;
	}
});
```

**Comment by daffl** [comment]
I'd probably add a `find` hook to the users service:

```js
app.service('users').before({
  find(hook) {
    hook.params.query.active = true;
  }
});
```

This will make sure that only active users are retrieved by `feathers-authentication`.

**Comment by ekryski** [comment]
Again, the 0.8.0 version of feathers-auth will make it easier for you to add your own custom lookup functionality for users by hooking into it or simply extending the auth services.

**Comment by ekryski** [comment]
This is now possible and much more flexible. You can simply [extend the verifier](https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier) for `feathers-authentication-local` (or any other provider) if you wish to query by some other factors. Additionally, you could still look up the user but reject with a custom error if the user is not "active".
