### ISSUE TITLE
Get user outside a service

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-authentication#261]
How to get current connected user outside a service ?

I have this code : 

```js
app.configure(hooks())
  .configure(rest())
  .configure(socketio())
  .use(actionsHandler)
  .configure(services)
  .configure(middleware);
```

And in my `actionsHandler` after login `req.feathers` = only `{ provider: 'rest' }` and `req.isAuthenticated()` = `false`

My auth config is the following:

```js
{
  auth: {
    idField: 'id'
  }
}
```

And I connect like this:
```js
    app.authenticate({
      type: 'local',
      email: data.email,
      password: data.password
    }).then(result => {
      console.log(app.get('token')); // -> the JWT
      console.log(app.get('user')); // -> the user

      return result;
    })
```

ps: The cookie is never after login

**Comment by daffl** [comment]
I am not sure what you mean? `app.get('user')` on the client seems to do what you are asking right?

On the server for each method call the user that makes it is stored in `params.user` (when the authentication hooks are set).

**Comment by bertho-zero** [comment]
I have 2 parts, one with feathers and another before that manages other actions (not REST), and I wish I could have access to the user connected when I am not in service and I do not have access to the hooks.

After login I have the current user, my goal is to be able to recover after a refresh of the page and the server side rendering which is enabled

**Comment by daffl** [comment]
This will be possible in the next version but for now you should be able to use the [decode-token](https://github.com/feathersjs/feathers-authentication/blob/passwordless/src/middleware/express/decode-token.js) and [populate-user](https://github.com/feathersjs/feathers-authentication/blob/passwordless/src/middleware/express/populate-user.js) Express middleware from that version.

**Comment by bertho-zero** [comment]
I saw [decode-token](https://github.com/feathersjs/feathers-authentication/blob/passwordless/src/middleware/express/decode-token.js#L11) Express middleware but I don't have ` req.feathers.token`, so I also looked in [token-parser](https://github.com/feathersjs/feathers-authentication/blob/passwordless/src/middleware/express/token-parser.js#L50) and [set-cookie](https://github.com/feathersjs/feathers-authentication/blob/passwordless/src/middleware/express/set-cookie.js#L35) middleware and I had not seen the option `cookie.enable`, I try it as soon as possible and put my back here

**Comment by marshallswain** [comment]
@bertho-zero, If you're feeling brave, you can also try installing the pre-release version of `feathers-authentication@0.8.0` and check out the [example folder in the `0.8.0` branch](https://github.com/feathersjs/feathers-authentication/tree/0.8/example) to see how to implement it.

**Comment by bertho-zero** [comment]
It works well in real-time but not in rest, I don't understand..


I have :
```js
app.authenticate({
      type: 'local',
      email: data.email,
      password: data.password
    }).then(result => {
      console.log(app.get('token')); // -> the JWT
      console.log(app.get('user')); // -> the user

      return result;
    })
```

and both `console.log` write `null`.

I continued to seek the cause

**Comment by bertho-zero** [comment]
I solved the problem with the following authentication config :
```js
...
local: {
  successHandler: authConfig => (req, res, next) => {
    delete res.data.user.password;
    next();
  }
...
}
```

Otherwise I lose the user and the token during the redirect, then I set the cookie with `js-cookie` in client side for remember session after page refresh, this is maybe due to `node-http-proxy`, I tested this:
```js
cookies: {
  enable: true,
  'feathers-jwt': {
    maxAge: 60 * 60 * 24 * 1000 // One day
  }
}
```

**Comment by bertho-zero** [comment]
I use it in this repo: https://github.com/bertho-zero/react-redux-universal-hot-example/

**Comment by bertho-zero** [comment]
I can connect, edit a client-side cookie and remain connected to refresh the page, but the socket that reconnects, he is not identified with the user.

Would you know how to reconnect the socket to the current user?

**Comment by marshallswain** [comment]
@bertho-zero I think this is what you need: https://github.com/feathersjs/feathers-authentication/issues/272#issuecomment-240937322

**Comment by bertho-zero** [comment]
Thanks, what I would like is not on a basic connection but a new connection after refresh the page.

I tried the same thing at `on.('connect', ...)` in vain, I've the following log in client:
```
socket.io-client:manager writing packet {"type":2,"data":["authenticate",{"type":"token","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNDcxOTY3NTg4LCJleHAiOjE0NzIwNTM5ODgsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYXV0aCJ9.EqkOQp5W62d1hHv7jRvlW1BICiA5UvQ91AfRiynhTw4"}],"options":{"compress":true},"nsp":"/"} +10ms
socket.io-parser encoding packet {"type":2,"data":["authenticate",{"type":"token","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNDcxOTY3NTg4LCJleHAiOjE0NzIwNTM5ODgsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYXV0aCJ9.EqkOQp5W62d1hHv7jRvlW1BICiA5UvQ91AfRiynhTw4"}],"options":{"compress":true},"nsp":"/"} +1ms
socket.io-parser encoded {"type":2,"data":["authenticate",{"type":"token","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNDcxOTY3NTg4LCJleHAiOjE0NzIwNTM5ODgsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYXV0aCJ9.EqkOQp5W62d1hHv7jRvlW1BICiA5UvQ91AfRiynhTw4"}],"options":{"compress":true},"nsp":"/"} as 2["authenticate",{"type":"token","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNDcxOTY3NTg4LCJleHAiOjE0NzIwNTM5ODgsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYXV0aCJ9.EqkOQp5W62d1hHv7jRvlW1BICiA5UvQ91AfRiynhTw4"}] +1ms
...
engine.io-client:socket socket receive: type "message", data "20["unauthorized",{}]" +11ms
socket.io-parser decoded 20["unauthorized",{}] as {"type":2,"nsp":"/","id":0,"data":["unauthorized",{}]} +1ms
socket.io-client:socket emitting event ["unauthorized",{}] +1ms
```

Yet this is the same token for the http connection when retrieve the page, I do this in the client:
```js
socket.on('connect', () => {
  app.authenticate();
});
```

And I've the following configuration:
```
auth: {
  user: {
    idField: 'id'
  },
  local: {
    successHandler: () => (req, res, next) => next // for login with rest provider, jump redirection
  },
  token: {
    secret: 'super secret'
  },
  cookies: {
    enable: true
  }
}
```
