### ISSUE TITLE
REST Middleware breaks local auth

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-authentication#262]
Using an empty REST middleware that calls next() breaks local authentication:

```
  .configure(rest(function (req, res, next) {
    next();
  }))
```

vs no middleware:

```
  .configure(rest())
```

When the middleware is added, a `404` response is returned. Response content is: `Cannot POST /auth/local`.

<img width="923" alt="screen shot 2016-08-06 at 2 16 09 pm" src="https://cloud.githubusercontent.com/assets/1571918/17459093/679dfe32-5be0-11e6-861e-8daff2da33a6.png">

**Comment by daffl** [comment]
Is what you want to accomplish the same thing as documented in http://docs.feathersjs.com/rest/readme.html#customizing-the-response-format?

The default formatter can be found in https://github.com/feathersjs/feathers-rest/blob/master/src/index.js#L6.

**Comment by petermikitsh** [comment]
Yeah, my use case is I need a special endpoint for one of my services that returns an XML document.

I tried defining a formatter right before `app.use('myCustomEndpoint', { get(id) { ... }});`` e.g.,

```
app
  .config(function (req, res, next) { ... })
  .use('myCustomEndpoint', { ... });
```

But that wasn't working for me.

**Comment by petermikitsh** [comment]
Okay, that helped, thanks! I ended up writing my own formatter:

```js
function (req, res, next) {
  if (!res.data) {
    next();
  }
  if (req && req.originalUrl && req.originalUrl.indexOf('myCustomEndpoint') === 0) {
    res.set('Content-Type', 'text/xml');
    res.end(res.data.xml);
  } else {
    res.format({
      'application/json': function () {
        res.json(res.data);
      }
    });
  }
};
```

A little tricky since it works similarly, but not exactly like, express middleware.

**Comment by daffl** [comment]
It is an Express middleware, I don't think there is any difference. I'm wondering if in your case you really just want to register a formatter after the service (so that the default never gets hit):

```js
app.use('/mycustomservice', myCustomService, function(res, res) {
  res.set('Content-Type', 'text/xml');
  res.end(res.data.xml);
});
```

**Comment by petermikitsh** [comment]
Yeah, that is much more what I was looking for since I didn't need to change the global formatter. Thanks again!
