### ISSUE TITLE
Use feathers-socketio? and rest&socket share session maybe? 

### ISSUE THREAD

**Issue by simonjoom** [feathersjs/feathers-authentication#269]
I think we should to use  express-session and no need anymore cookie-parser - > Since version 1.5.0, the cookie-parser middleware is no need

And add middleware fonctionnalities with socket-io 

why not use share sessions between rest and socket to get things working all together? 
why not use feathers-socketio instead socket?

see: http://stackoverflow.com/questions/25532692/how-to-share-sessions-with-socket-io-1-x-and-express-4-x

**Comment by daffl** [comment]
feathers-authentication does not use sessions. The Cookie parser is only for getting the JWT from a cookie which is usually only the case with server side rendering.

You can also already use your own Socket.io middleware as [documented here](http://docs.feathersjs.com/real-time/socket-io.html#configuration).

**Comment by simonjoom** [comment]
Thks for replying, yes i saw it that it 's not using sessions. 
Just can i ask why ? better to use only cookie? and if the user do not authorize to store cookie? 

I used localstore to keep the session logged because that... Is it important to let this part to the developper?

**Comment by daffl** [comment]
Well cookie-parser just passes the cookie request header so the name isn't necessarily wrong. The cookie is just one way to provide the JWT though. You can easily disable cookies and manage the tokens yourself (the [client](http://docs.feathersjs.com/clients/feathers.html) does that for you already).
