### ISSUE TITLE
Socker.js | Custom successHandler

### ISSUE THREAD

**Issue by JigsWeb** [feathersjs/feathers-authentication#271]
File: https://github.com/feathersjs/feathers-authentication/blob/0.8/src/middleware/sockets.js
Line: 25

When I authenticated a user, I want to remove his password, it is posssible to make a custom 'successHandler' ?

PS: I use FA for one days so be indulgent :D

**Comment by daffl** [comment]
I thought it does that already but you can modify the returned data yourself with a [hook](http://docs.feathersjs.com/hooks/readme.html) after the authentication service.

```js
app.service('auth/local').after(hook => {
  if(hook.result.data.user && hook.result.data.user.password) {
    delete hook.result.data.user.password;
  }
});
```
