### ISSUE TITLE
JWT is not sent after socket reconnection

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers-authentication#272]
I have stumbled upon strange behavior - after socket is disconnected and connected again, new realtime events does not contain JWT (hook.params.token) which renders all reconnect process useless (= you have to authorize user again manually).

What to do about this?

**Comment by daffl** [comment]
At the moment have to store the token and send the `authenticate` event. When using the client this can be done with calling `app.authenticate()` again after a disconnect just like when the application is loading initially. The next version should probably try to do this automatically.

**Comment by tkornblit** [comment]
I'm also running into this issue. I've even done the following:

```
this.app = feathers()
        .set("user", JSON.parse(localStorage.getItem('user')))
        .set("token", localStorage.getItem('token'))
        .configure(socketio(socket))
        .configure(hooks())
        .configure(authentication({storage: localStorage}))
```

Which I thought was going to be a clever hack.

The client-side hook picks it up successfully. But for some reason it's not available in the hook on the server side. 

Using app.authenticate isn't going to work for me because i'm using the `local` authentication option and not JWT.

Any ideas?

**Comment by Mangatt** [comment]
@tkornblit I have solved this issue with following code:

```javascript
const socket = io('http://localhost:3030/');

const app = feathers()
	.configure(hooks())
	.configure(socketio(socket))
	.configure(authentication({ storage: window.localStorage }));

socket.on('reconnect', () => {app.authenticate();});
```

Hope this helps.

**Comment by tkornblit** [comment]
Thanks mate. This was helpful.
--
Tom Kornblit
Founder of Sage <http://www.sagebots.com/>
Personal Blog <http://blog.tomkornblit.com/> | LinkedIn <https://www.linkedin.com/in/tomkornblit> | Twitter <https://twitter.com/tkornblit>

**Comment by marshallswain** [comment]
Closing this in favor of https://github.com/feathersjs/feathers-authentication-client/issues/2
