### ISSUE TITLE
passport auth question

### ISSUE THREAD

**Issue by gregbenner** [feathersjs/feathers-authentication#274]
Everything seems to work fine until the callback, which is set as `http://127.0.0.1:3030/auth/github/` on github
Not sure why it would say it's a 302 then redirect to `auth/failure` any tips?

Request URL:http://127.0.0.1:3030/auth/github/callback?code=a62ee27e72cf3a28de98&state=true
Request Method:GET
Status Code:302 Found
Remote Address:127.0.0.1:3030

**Comment by gregbenner** [comment]
`Request URL:https://bitbucket.org/site/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Ffullstack.dev%3A3030%2Fauth%2Fbitbucket%2Fcallback&scope=account&state=true&client_id=ZArF2EhraTsJpDeBwp
Request Method:GET
Status Code:302 
Remote Address:104.192.143.1:443
Response Headers
cache-control:max-age=0
content-language:en
content-length:0
content-type:text/html; charset=utf-8
date:Fri, 19 Aug 2016 16:28:48 GMT
etag:"d41d8cd98f00b204e9800998ecf8427e"
expires:Fri, 19 Aug 2016 16:28:48 GMT
last-modified:Fri, 19 Aug 2016 16:28:48 GMT
location:http://fullstack.dev:3030/auth/bitbucket/callback?state=true&code=yyqzryc2e9BVX5HAaE
server:nginx/1.6.2
status:302
strict-transport-security:max-age=31536000
vary:Accept-Language, Cookie
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-render-time:0.023885011673
x-request-count:208
x-served-by:app-104
x-static-version:d2de90cfe5a1
x-version:d2de90cfe5a1
Request Headers
:authority:bitbucket.org
:method:GET
:path:/site/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Ffullstack.dev%3A3030%2Fauth%2Fbitbucket%2Fcallback&scope=account&state=true&client_id=ZArF2EhraTsJpDeBwp
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate, sdch
accept-language:en-GB,en;q=0.8,en-US;q=0.6,en-CA;q=0.4
cache-control:no-cache
cookie:bb_session=zdqyden1a8s1lezx5cuhqoskmjolvvhb; csrftoken=HbQ7sUsZk7BultNcrQRzGu7kNVqZ5V6Q; _ga=GA1.2.256661883.1471545761; _gat_atl=1; __utmt_atl=1; __utma=254090395.256661883.1471545761.1471545763.1471623219.2; __utmb=254090395.9.10.1471623219; __utmc=254090395; __utmz=254090395.1471545763.1.1.utmcsr=duckduckgo.com|utmccn=(referral)|utmcmd=referral|utmcct=/; blocking-ads=true
dnt:1
pragma:no-cache
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Query String Parameters
view source
view URL encoded
response_type:code
redirect_uri:http://fullstack.dev:3030/auth/bitbucket/callback
scope:account
state:true
client_id:ZArF2EhraTsJpDeBwp
Name
 `

`Request URL:http://fullstack.dev:3030/auth/bitbucket/callback?state=true&code=yyqzryc2e9BVX5HAaE
Request Method:GET
Status Code:302 Found
Remote Address:127.0.0.1:3030
Response Headers
view source
Access-Control-Allow-Origin:*
Allow:GET,POST
Connection:keep-alive
Content-Length:70
Content-Type:text/html; charset=utf-8
Date:Fri, 19 Aug 2016 16:28:49 GMT
Location:/auth/failure
Set-Cookie:feathers-jwt=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
Vary:Accept, Accept-Encoding
X-Powered-By:Express
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-GB,en;q=0.8,en-US;q=0.6,en-CA;q=0.4
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:fullstack.dev:3030
Pragma:no-cache
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Query String Parameters
view source
view URL encoded
state:true
code:yyqzryc2e9BVX5HAaE`

`Request URL:http://fullstack.dev:3030/auth/failure
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:3030`

**Comment by gregbenner** [comment]
<img width="1079" alt="screen shot 2016-08-19 at 5 31 00 pm" src="https://cloud.githubusercontent.com/assets/1177690/17816776/d221ff90-6632-11e6-94b8-38c9a938c0ea.png">

**Comment by mcnamee** [comment]
Hi @gregbenner - I've had the same issue today.
When you start the feathers server - start it with `DEBUG=* npm start`. It'll log each step in the console to provide you more details.

My issue was that validation was failing, because I was using Facebook login, which wasn't filling in email and password (required fields) - so Feathers showed an auth fail.

**Comment by gregbenner** [comment]
Thanks @mcnamee I will give it a try.

**Comment by ekryski** [comment]
We fixed many issues so if you are still having trouble try upgrading to auth v1.0.0. Please refer to the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md). 😄
