### ISSUE TITLE
Duplicate Email should be rejected by Default

### ISSUE THREAD

**Issue by jaeko44** [feathersjs/feathers-authentication#281]
We need a rejectExistingEmail() hook function for this module.

**Comment by bertho-zero** [comment]
I created a [validateHook](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/api/hooks/index.js) with an [unique rule](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/api/utils/validation.js) for this, you can see its use [here](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/api/services/users/hooks.js).

Hoping I helped

**Comment by jaeko44** [comment]
nice
