### ISSUE TITLE
Mutliple 'user' models for authentication

### ISSUE THREAD

**Issue by ruddfawcett** [feathersjs/feathers-authentication#282]
Is it possible to have two models, both of which are not called `User` to login (sort of like two roles but split into models)?

If that is not possible, is it possible to have a single model not named `User` to login? Say my user model is named `Student` or something else? I can't seem to find any documentation on this.

**Comment by cvalarida** [comment]
I don't think it's possible to have two separate "User" models to log in (but I'm not an authority on this).

What you're looking for on the second bit is the `userEndpoint` option when you configure authentication (check it out in [the docs](https://docs.feathersjs.com/authentication/readme.html#options)).

You'll want to configure that endpoint in your services, of course.

If that doesn't make enough sense, I can give you examples (I just had to figure this all out myself).

**Comment by ekryski** [comment]
@ruddfawcett a fix is coming in 0.8 for this so that you can authenticate with any/multiple entities

**Comment by ruddfawcett** [comment]
Great, thanks @ekryski!

**Comment by alzab** [comment]
@ekryski Was this actually implemented? Documentation seems to be scarce on this point!
