### ISSUE TITLE
issuer doesn't work

### ISSUE THREAD

**Issue by elaijuh** [feathersjs/feathers-authentication#284]
```
  "auth": {
    "token": {
      "issuer": "abc",
      "secret": "ZJApt91sS3bPV275hfobvCTSJYEgv+1n09A8D4bGlqI9S+lq3oePV1Xwla52ZipAXgaj8X/t17/3Tl6UFi1cOQ=="
    },
    "local": {}
  }
```

this is how i config the auth, but seems the token name retrieved is still `feathers-jwt`
btw, i am using localstorage to save the token

**Comment by ekryski** [comment]
This is now fixed in auth v1.x. The only difference is you need to use `jwt` instead of `token`. Please see the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) for how to upgrade.
