### ISSUE TITLE
hashPassword in patch

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers-authentication#286]
This check https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/hash-password.js#L36-L39 is preventing patch methods if password is not defined in the data.

**Comment by marshallswain** [comment]
Yeah.  `hashPassword` should just hash a password if one is available.  I made a PR. 

cc: @ekryski, @daffl

**Comment by mcchrish** [comment]
An alternative for now is:
```js
const { hooks } = require('feathers-authentication');

// Your custom hashPassword hook
exports.myHashPassword = function(options) {
  const hashPassword = hooks.hashPassword(options);

  // Add any custom options
  return function(hook) {
    if(hook.data.password !== undefined) {
      // Call the hashPassword hook
      return hashPassword.call(this, hook);
    }
  };
}
```

Taken from http://docs.feathersjs.com/hooks/usage.html#customizing-built-in-hooks
