### ISSUE TITLE
User (Entity) needs to be updated on the socket after authentication

### ISSUE THREAD

**Issue by sunabozu** [feathersjs/feathers-authentication#293]
So here is the problem. 
1. I authenticate
2. I have a required role to create a particular resource, protected by the hook, and I create it successfully
3. I edit my database (both directly and through the client), removing the required role from the user document
4. I try to create the same resource and I succeed (<== problem)
5. I logout, authenticate again and now the hook is working, I can't create the resource

So it seems like it caches the user object from the database or (which is much worse) just checks the object sent by the user himself. In the later case it's a security flaw, since any user can assign himself any role on the client side.

**Comment by marshallswain** [comment]
@sunabozo, are you modifying the token payload at all?  As in, are you putting storing permissions in the token?  Where is the auth getting its stale data?

**Comment by sunabozu** [comment]
@marshallswain I don't touch the token. I use `restrictToRoles` in the list of the `before` hooks for my model. Particularly for the `create` method:

``` js
exports.before = {
  all: [],
  find: [],
  get: [],
  create: [
    authHooks.restrictToRoles({
      roles: ['admin']
    })
  ]
};
```
The `user` model has a `roles` field, where the roles are stored. So I modify that field for the current user and nothing else.
I hope I understood your questions correctly.

**Comment by marshallswain** [comment]
Yeah, looks like you understood what I was trying to say.  What hooks are you running before the `restrictToRoles` hook?

**Comment by marshallswain** [comment]
I recommend using Visual Studio Code's debugger and setting a breakpoint here: https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-roles.js#L32  To see if you're still getting stale data, somehow.  Using the populateUser hook just before this one should query the database for fresh data every time, unless you have some kind of cacheing mechanism in place.  Not sure what your db setup is.

**Comment by marshallswain** [comment]
Setting up VSCode is a one-line change with a generated app.  Just press the green play button to start the debugger for the first time and it will prompt you for a configuration type.  Choose node, then change the highlighted line to look like this:

![screen shot 2016-09-17 at 1 00 09 pm](https://cloud.githubusercontent.com/assets/128857/18610334/ce885298-7cd6-11e6-9a3e-61905ce37e80.jpg)

Then you can just open that file in your node_modules and set a break point on that line.  Run the query and it will stop at that point so you can inspect just like with Chrome debug tools.

**Comment by sunabozu** [comment]
it's the only hook I use for that model. Sorry, I can't use the VS Code at the moment, but I checked the sources and it seems like this hook [checks the roles on the object sent by the browser](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-roles.js#L35), not the actual resource in the database.

So the solution here is simple - I just need to use these hooks first:

```
verifyToken
populateUser
restrictToAuthenticated
```
Reading the documentation I didn't realise that I must use `restrictToRoles` in conjunction with other hooks. I think it should be mentioned explicitly [here](https://docs.feathersjs.com/authorization/bundled-hooks.html). Sorry if I misunderstood the whole concept, I'm new to Feathers.

**Comment by marshallswain** [comment]
I completely agree. If you don't mind creating a PR that would be very much
appreciated. If that's not an option for you, then maybe just open an issue
in the Feathers-docs repository. Glad you got it working.

**Comment by ekryski** [comment]
This may or may not be an issue with the new permissions. Will need to audit to see if we can reproduce with the new stuff.

**Comment by ekryski** [comment]
💯  this is an issue. We're working on a fix for this and this is the last major thing required for Auth 1.0  besides docs IMHO.

**Comment by jerfowler** [comment]
What is the best workaround for this? I've just been using `app.service('users').get(id).then()...` in all my hooks just to make sure I have the latest user info. 

Is there a way to force a silent reauthentication with the socket.io connection in the background after I update the user in a hook?
