### ISSUE TITLE
Unable to authenticate with passport-google-oauth20

### ISSUE THREAD

**Issue by EugeneZ** [feathersjs/feathers-authentication#295]
I can't seem to get Google OAUTH2 working. I thought it must be me, so I took the `feathers-oauth2-authentication` project from the [`feathers-demos`](https://github.com/feathersjs/feathers-demos/tree/master/examples/authentication/oauth2) repo, which uses GitHub, and ran it. It worked. I replaced the passport-github package with passport-facebook (which is very similar to Google's), replaced the link in `index.html`, changed `github` to `facebook` in the configuration object, and updated the ids. This also worked. I performed the same exact steps but with the `passport-google-oauth20` package. It gets as far as Google's page asking me for permission to see my public profile, etc, but when I approve, the callback that it redirects to forwards me to the failure page. Looking at the redirect, it looks like Google did the right thing and forwarded `state=true` and some sort of token, just like Facebook does. Any ideas?

**Comment by marshallswain** [comment]
@EugeneZ have you tried using the generator and letting it build the Google OAuth setup for you?

**Comment by EugeneZ** [comment]
I did not, but I just went and set it up. All I did was set up a new repo, babel (as per the guide), `feathers generate` with all defaults except google for auth and memory for db. Added my oauth ids to the config and added a link to `/auth/google` to `index.html`. No good, same exact problem... Google asks for password and then forwards to callback, which then forwards to failure.

**Comment by EugeneZ** [comment]
Ever had that thing where shortly after opening an issue you figure out the problem even though you thought you tried *everything* before opening it? Yeah. That. Sorry!

For those interested, turns out you have to enable the Google+ API from your API dashboard (I had to also enable the Gmail API, might be the permissions I'm requesting). See here: https://github.com/jaredhanson/passport-google-oauth/issues/46

**Comment by marshallswain** [comment]
Glad you got it worked out
