### ISSUE TITLE
Add option to use bcrypt

### ISSUE THREAD

**Issue by andrejunges** [feathersjs/feathers-authentication#300]
I know there is a way to pass it as a property when we initiate this module, but I don't think its fully compatible. When I tried to pass it, I got an error related to the provider not being a function.
Error line:
https://github.com/feathersjs/feathers-authentication/blob/master/src/index.js#L142

So it may be easier to the library itself provide a way to change the bcrypt implementation that's gonna be used.

**Comment by ekryski** [comment]
This is now possible and much more flexible. You can use the native `bcrypt` module by simply [extending the verifier](https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier) for `feathers-authentication-local` and implementing your own [`_comparePassword`](https://github.com/feathersjs/feathers-authentication-local/blob/master/src/verifier.js#L22-L47) function that uses bcrypt. In fact, you can use any hashing function you would like.

You will also need to pass your own `hash` function [as an option](https://github.com/feathersjs/feathers-authentication-local#hashpassword-hook) to the `hashPassword` hook.
