### ISSUE TITLE
RSA token secret

### ISSUE THREAD

**Issue by lontongcorp** [feathersjs/feathers-authentication#309]
Moved from main repo feathersjs/feathers#423

Using node-rsa, export it to keyfile, as default token secret rather than hardcode it in config file will be better option I think. Reduce unnecessary steps to create new (good) token, production ready, and rotating it in every x days/wk/mo will make it more secure.

**Comment by marshallswain** [comment]
Rotating the token secret will invalidate all existing token, but after we implement real refresh token support it won't really be an issue.

**Comment by daffl** [comment]
The new generator has a secret generator (see https://github.com/feathersjs/generator-feathers/blob/master/generators/secret/index.js) which I think is all we'll do for now.
