### ISSUE TITLE
[Question] Is there a way to verify a user with password?

### ISSUE THREAD

**Issue by nyjy85** [feathersjs/feathers-authentication#316]
I'm trying to verify user with their password.  This is for a reset-password functionality.  I required the user to submit their old password and new password.  The old is purely for verification and if it passes, then the service will update the user's password with the new one.  Is there a hook I can use in this library that will allow me to verify a user by their password? If not, what's the best way to go about implementing it?

**Comment by eddyystop** [comment]
You can see how [feathers-service-verify-reset](https://github.com/eddyystop/feathers-service-verify-reset) does it [here](https://github.com/eddyystop/feathers-service-verify-reset/blob/master/src/index.js#L310).

**Comment by daffl** [comment]
I think we can close this. As @eddyystop pointed out you can use the basic `bcrypt.compare` to compare passwords.
