### ISSUE TITLE
restrict-to-owner throws error when user id is 0

### ISSUE THREAD

**Issue by cgislason** [feathersjs/feathers-authentication#319]
I was doing some testing and created a test user in `feathers-memory` like this:
```
userService.create({
  email: 'test@example.com',
  password: 'password',
}).then((value) => {
  console.log('created user:', value);
});
```

Then when I tried to authenticate with `auth/local` I got the error: `The 'restrictToOwner' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.` I knew that I was only using the hook on those 4 service methods so I dug into the `restrict-to-owner` code and found this:
```
if (!hook.id) {
  throw new _feathersErrors2.default.MethodNotAllowed('The \'restrictToOwner\' hook should only be used on the \'get\', \'update\', \'patch\' and \'remove\' service methods.');
}
```

The `!hook.id` check fails when the id is 0 (or any other false value). This check should probably be more careful. (I worked around it by giving a proper id)

**Comment by daffl** [comment]
Can you submit a PR? Basically https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-owner.js#L15-L17 should instead look something like:

```js
    if (['get', 'update', 'patch', 'remove'].indexOf(hook.method) === -1) {
      throw new errors.MethodNotAllowed(`The 'restrictToOwner' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.`);
    }
```
