### ISSUE TITLE
Support authenticating with Username and Password via sockets

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#32]
Currently we only support authentication via sockets once you have your JWT. We should support being able to send the `username` and `password` attributes via sockets and receive a JWT in response.

**Comment by daffl** [comment]
That was one of the things I started on when looking into oAuth. The authentication routes (see https://github.com/feathersjs/feathers-authentication/blob/master/src/index.js#L41) should probably simply be their own service. That way we'd get SocketIO authentication for free. /cc @marshallswain

**Comment by marshallswain** [comment]
That's how I discovered this stuff about trading an unauthenticated socket for an authenticated one: 
```
socket = io('', {
  // Assuming you've already saved a token to localStorage.
  query: 'token=' + localStorage.getItem('featherstoken'),
  transports: ['websocket'], // optional, see below
  forceNew:true,             // optional, see below
});
```

**Comment by marshallswain** [comment]
Sounds good.

**Comment by ekryski** [comment]
This is done in the `decoupling` branch.
