### ISSUE TITLE
I checked out my new feathersjs app in another machine, created a new user but I can't log in!

### ISSUE THREAD

**Issue by paulophp** [feathersjs/feathers-authentication#320]
I tried many times and no success, in the other machine where I started the app it works fine!
What could cause this behavior?

Thank you guys, I love feathersjs!!!!

**Comment by paulophp** [comment]
Uncaught (in promise) Error: Could not find stored JWT and no authentication type was given(…)ExtendableBuiltin @ feathers.js:1379FeathersError @ feathers.js:1457NotAuthenticated @ feathers.js:1510(anonymous function) @ feathers.js:737

**Comment by daffl** [comment]
The errors says that no authentication token has been created yet. It means you will have to log in (e.g. with `app.authenticate({ type: 'local', email, password })` or the `login.html` from the chat guide) to create and store a new token.

**Comment by paulophp** [comment]
Yes this is what intrigues me,
I based my signup and login pages on the chat guide, it works with local storage auth perfectly in the machine OX I started the project, I create users, login in, do stuff with my logged id "socket events so cool", but when I checkedout a copy to work at home in a Ubuntu machine it creates the user "mongo works fine" but it always goes: Login Failed
Something went wrong and we weren't able to log you in. Please try again.

**Comment by paulophp** [comment]
I am guessing something about the local token, I don't know how it works, does it needs any permission?
I will try it in a docker, it is my last hope..

**Comment by paulophp** [comment]
The project is in a privet repository, but I made a zip file of it 1.2mb if anyone want to take a look I can send by e-mail, or past here any part of the code.

thanks!

**Comment by ekryski** [comment]
@paulophp which database are you using? Are you signing up and logging in again or trying to login using a user that you created on your other machine?

The reason I ask is if you are using NeDB then it stores things on disk so you'll have to "signup" the user again on your Ubuntu machine because they won't exist yet. Feathers really has nothing to do with the OS.

**Comment by paulophp** [comment]
@ekryski I am using mongodb since I started,
On the Ubuntu machine I signup a new user again, I removed the auth from the service so I can see that the user is being created on mongodb on the ubuntu machine just fine, but login simply does not work!

I did it twice even configuring default.json to a different mongodb database, created a new user again, checked it was created, but login always fail.

**Comment by paulophp** [comment]
I figured it out guys, I am really sorry for the trouble!
I messed with the user/hooks at some point and versioned it, so new users after that wasn't hashing passwords, so login would never work!

I am very thankful for you guys having created FeathersJs and helping Us understanding it!

Thank you all  and again I am sorry, this was not a real issue!

**Comment by ekryski** [comment]
@paulophp no problem. Glad you got it sorted! 😄
