### ISSUE TITLE
How to get user id in hooks?

### ISSUE THREAD

**Issue by evgenyboxer** [feathersjs/feathers-authentication#322]
Hey,

I was wondering, how do I get the user id? I do get the token which I can decode, but shouldn't the user id be also assigned to it?

**Comment by marshallswain** [comment]
Currently the userId is stored as id or _id inside the token payload, so once you verify the token you can grab it from the payload.

**Comment by daffl** [comment]
In the current version if you add the `populateUser` hook, the user will be in `params.user`.

**Comment by evgenyboxer** [comment]
Thanks! It worked 👍 

I used:

`
  create: [
    auth.verifyToken(),
    auth.populateUser(),
    addUserId(),
  ]
`
