### ISSUE TITLE
Need help to use feathers authentication storage in vue vuex

### ISSUE THREAD

**Issue by kieusonlam** [feathersjs/feathers-authentication#329]
I'm trying to intergrate feathers with vue + vuex. I got confused about define local storage for feathers authentication. You guys can take a look at my repo:

[https://github.com/kieusonlam/vue-feathers-wepack](https://github.com/kieusonlam/vue-feathers-wepack)

This file I created for feathers client
[vue-feathers-wepack/client/store/feathers.js](https://github.com/kieusonlam/vue-feathers-wepack/blob/master/client/store/feathers.js)
if i change storage to `localStorage` or `window.localStorage` i will get this error
```
window.localStorage is not defined
```
And here is the store i make for feathers authentication
[vue-feathers-wepack/client/store/modules/auth.js](https://github.com/kieusonlam/vue-feathers-wepack/blob/master/client/store/modules/auth.js)

**Comment by daffl** [comment]
That problem might occur if you are running your browser in private or incognito mode. Related: #135

**Comment by kieusonlam** [comment]
My problem is about server side rending, i solved it. Thank you for reply 👍 Good to know that problem too.

**Comment by andycaramba** [comment]
Hi @kieusonlam 
Could you explain how you solved this issue?

**Comment by kieusonlam** [comment]
Hi @andycaramba 

I just make it running on client side only by using `process.env` you can take a look at here.

https://github.com/kieusonlam/vue-feathers-wepack/blob/master/client/store/feathers.js

**Comment by andycaramba** [comment]
Thank you @kieusonlam
