### ISSUE TITLE
Auth 1.0

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#330]
If you wish to see what encompasses this issue install [Zenhub](https://www.zenhub.com/)

**Comment by gerwintown** [comment]
Zenhub would like authorization for access to private information concerning organizations I am apart of that have nothing to do with this project.  Is there any way to get some idea what this is about without going through that first?

**Comment by cklmercer** [comment]
Just wasted quite of bit of time following the migration guide, just to find out that some of the core packages are still incomplete/unpublished. Neither this library nor any of the supporting `v1` libraries mention this anywhere (that I noticed.)

**Comment by luke3butler** [comment]
@gerwintown Just to give you an idea, here's what that extension shows here as of 12/08/16

![auth 1.0 status](http://i.imgur.com/ke7Hm32.png)

**Comment by daffl** [comment]
Those are all closed now, only official docs are missing which will come with the release.
