### ISSUE TITLE
Meteor auth migration guide

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#334]
This is just something that I'm interested in doing, so if I've gotten busy and haven't done anything here in two months, please ping me and we might close it.  :)

The tutorial: https://themeteorchef.com/recipes/roll-your-own-authentication/
The GitHub repo: https://github.com/themeteorchef/roll-your-own-authentication/tree/master/code

And here's a basic MongoDB doc that Meteor would create should you choose to use their `accounts-password` package.

``` json
{
    "_id" : "66ksHBcY8FjTHMQ3E",
    "services" : {
        "password" : {
            "bcrypt" : "$2a$10$9tdaeMHSlo10Xbs3vrdJhuto5H1issxKIQkX7Cgk4TH0O0Qbyg8PC"
        },
        "email" : {
            "verificationTokens" : [
                {
                    "token" : "Vtr5tE1jNnDLtLBg9714RoisBm-F2Qu9nHgoAlgG64a",
                    "address" : "email@example.com",
                    "when" : ISODate("2016-09-09T13:19:15.403Z")
                }
            ]
        },
        "resume" : {
            "loginTokens" : [ 
                {
                    "when" : ISODate("2016-10-19T15:52:22.925Z"),
                    "hashedToken" : "h1dhwJAIgtM0/f7qxNL9KfyJhUDH6B0qio+BKGyTuaA="
                }, 
                {
                    "when" : ISODate("2016-10-27T16:07:22.361Z"),
                    "hashedToken" : "o318zSXsGBjt01IhbbnjbWaIjW2Uf+gyn4i3PwoZl6U="
                }
            ]
        }
    },
    "emails" : [ 
        {
            "address" : "email@example.com",
            "verified" : true
        }
    ],
    "profile" : {},
}
```

**Comment by ElegantSudo** [comment]
This looks awesome, let me know if you ever get around to it.

**Comment by MHerszak** [comment]
I just leave this here:

I am currently going through Meteors accounts-base, accounts-oauth, .. and I am getting kind a lost. There are many fragments bound to Meteor and are already available (in there own way) to Feathers. I am currently thinking about a simple hook type of system that obtains a Strategy and a token. Have you done any research on the requirements you could share?

**Comment by ElegantSudo** [comment]
I've looked into Feathers authentication and it's really straightforward.

There aren't any real "requirements", just read the docs and acclimate yourself.

The main reason Meteor developers get frustrated with it is because Meteor does practically everything for the developer, handicapping him to the system.

**Comment by MHerszak** [comment]
I ended up using `feathers-authentication-management`.

**Comment by ekryski** [comment]
I think I'm going to close this out. @marshallswain if you have the time and it becomes something you want to tackle, feel free to re-open. :)
