### ISSUE TITLE
App.authenticate uses wrong `this` reference

### ISSUE THREAD

**Issue by clapik** [feathersjs/feathers-authentication#341]
On this line, reference to `this` seems wrong - producing an Error.
It should be `app` instead.
https://github.com/feathersjs/feathers-authentication/blob/master/src/client/index.js#L30
Same for https://github.com/feathersjs/feathers-authentication/blob/master/src/client/index.js#L35

![image](https://cloud.githubusercontent.com/assets/3974885/20012736/04a5ebce-a2e3-11e6-81fc-27d96c5f333f.png)

**Comment by daffl** [comment]
If you call `app.authenticate` the `this` reference will be `app`. You can't call the method out of context however with something like

```js
var auth = app.authenticate;
auth();
```

It has to be `var auth = app.authenticate.bind(app);`

**Comment by clapik** [comment]
oh i see! thanks for the response!
