### ISSUE TITLE
Build 0.7.11 does not contain current code on NPMJS

### ISSUE THREAD

**Issue by joelkoz** [feathersjs/feathers-authentication#342]
I just pulled a new copy of feathers from npmjs via 'npm install', as I noticed a bug I had reported (#301) had been fixed.  Unfortunately, my local tests failed, and after a little investigation, I noticed that the "feathers-authentication/lib/hooks/restrict-to-owner.js" code does not appear to be from the same code that is in the master repo here on github.  I wonder if perhaps there was a transpiler failure, and the lib file did not get updated with the correct code prior to "npm publish."

**Comment by marshallswain** [comment]
You're right.  I just verified with a new install:

```json
{
  "name": "fcheck",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "feathers-authentication": "^0.7.11"
  }
}
```

It doesn't contain the code from that commit.

![screen shot 2016-11-10 at 5 45 06 pm](https://cloud.githubusercontent.com/assets/128857/20200270/8060a784-a76d-11e6-8873-a0da73f30d2e.jpg)

**Comment by daffl** [comment]
I republished a 0.7.12 and it should now contain the fix.

**Comment by ekryski** [comment]
@daffl what was the deal?

**Comment by daffl** [comment]
No idea. Maybe publishing failed and I didn't notice.

**Comment by marshallswain** [comment]
That's just what the doctor ordered.  @joelkoz you should be able to use it, now.  Thanks for alerting us!

```js
{
  "name": "fcheck",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "feathers-authentication": "^0.7.12"
  }
}
```

![screen shot 2016-11-10 at 9 09 08 pm](https://cloud.githubusercontent.com/assets/128857/20204103/036494c6-a78a-11e6-8df8-587f9b517fdd.jpg)
