### ISSUE TITLE
Navigating to /auth/<provider> twice redirects to /auth/failed

### ISSUE THREAD

**Issue by stofstik** [feathersjs/feathers-authentication#344]
### Steps to reproduce
- Use feathers-cli to generate a \<provider> auth app no local
- Add \<provider> credentials to config/
- Navigate to /auth/\<provider>
- Authorize application
- Navigate to /auth/\<provider>

### To reset
- Remove user tokens from \<provider>
- Remove user from feathers app database
- Navigate to /auth/\<provider>

### Expected behavior
- Navigate to /auth/success again with token 

### Actual behavior
- Redirects to /auth/failed

### System configuration
```
dependencies": {
    "body-parser": "^1.15.2",
    "compression": "^1.6.2",
    "cors": "^2.8.1",
    "feathers": "^2.0.2",
    "feathers-authentication": "^0.7.12",
    "feathers-configuration": "^0.3.3",
    "feathers-errors": "^2.5.0",
    "feathers-hooks": "^1.6.1",
    "feathers-mongoose": "^3.6.1",
    "feathers-rest": "^1.5.2",
    "feathers-socketio": "^1.4.2",
    "mongoose": "^4.6.8",
    "passport": "^0.3.2",
    "passport-github": "^1.1.0",
    "passport-github-token": "^2.1.0",
    "serve-favicon": "^2.3.0",
    "winston": "^2.3.0"
}

**Comment by pyrostrex** [comment]
This happened to me. It turns out, I was using rethinkdb that uses `id` instead of `_id` and all I had to do is to add `"idField": "id"` to config/default.json and config/production.json under `"auth"` section and now it works perfectly.

**Comment by stofstik** [comment]
Mongo uses _id though. Tried setting `"idField": "id"` explicitly but still redirects to auth/failure.

**Comment by ekryski** [comment]
This is now fixed in auth v1.x. Please see the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) for how to upgrade.
