### ISSUE TITLE
Payload limiting on `app.get('user')`?

### ISSUE THREAD

**Issue by leebenson** [feathersjs/feathers-authentication#354]
There seem to be two options for limiting 'user' object fields:

**1. Payload**
i.e. the stuff that goes into the JWT token, set on `token: { payload { /* set here */ }}` in the call to `.authentication` on the server.

**2. Using 'after' hooks**
i.e. `hooks.remove('password')`

So far, so good.

Except `app.get('user')` on the client side seems to return the _full_ user object, minus only the password field. If there are any other private fields returned by the service (in my case, using `knex`) then those are still exposed.

Is there a way to limit what the client sees via `app.get('user')`?

This isn't so much for security in my case, and more to limit bandwidth to data that I'll actually use. I have a lot of normalised statistical stuff in my user tables that aren't really relevant to send down the wire.

**Comment by daffl** [comment]
That's why auth 1.0 client is doing a separate `get` to get the user (with all the hooks). I recommend upgrading to 1.0-beta (see https://github.com/feathersjs/feathers-authentication/blob/master/docs/new-1.0-features.md).

**Comment by leebenson** [comment]
great, I'll do that. Thanks @daffl
