### ISSUE TITLE
How to reconnect socket with cookie after page refresh ?

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-authentication#372]
Hi,

How to automatically connect the socket using the `accessToken` in the cookie after refreshing the page? I use version 1 of feathers-authentication.

It would be practical to be able to:
```js
app.io.use(authentication.socket.authenticate());
```

**Comment by marshallswain** [comment]
Right now you have to call `feathersClient.authenticate()` to make this happen.  Sockets are flagged as authenticated from the server side once they pass validation.

**Comment by bertho-zero** [comment]
It's perfectly fine

**Comment by bertho-zero** [comment]
Finally I created this socket.io middleware: https://gist.github.com/bertho-zero/5cdeabb77be98bc159b1e5d75c6af429

It is used like this:
```js
app.io.use(socketAuth(app));
```

If I remove this line ([gist#L17](https://gist.github.com/bertho-zero/5cdeabb77be98bc159b1e5d75c6af429#file-socketauth-js-L17)) I have an error from here: https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L38
