### ISSUE TITLE
cordova google-plus signUp with id_token

### ISSUE THREAD

**Issue by HedCET** [feathersjs/feathers-authentication#373]
i'm using [EddyVerbruggen/cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) in cordova, this cordova package provide ```id_token``` & how can i signUp using this ```id_token``` ?

*  using ```passport-google-id-token``` npm package (i don't know how to integrate it)
*  inside hook (like ```password``` send ```id_token``` from client) & http request to https://www.googleapis.com/oauth2/v3/tokeninfo with ```id_token``` to verify it in server, [meteor integration](https://github.com/sujith3g/meteor-cordova-google-plus/blob/master/server/cordova_g_plus.js)

**Comment by HedCET** [comment]
i saw #169, how i use ```passport-google-id-token``` for google ? is this possible ?

**Comment by ekryski** [comment]
@HedCET yes it should work the exact same was as outline in #169 except that the params sent from the client should be the ones that are described in [`passport-google-id-token`](https://github.com/themikenicholson/passport-google-id-token#configure-strategy).

**Comment by HedCET** [comment]
@ekryski is there any example ?

**Comment by HedCET** [comment]
server

```
'use strict';

const authentication = require('feathers-authentication');

const FacebookStrategy = require('passport-facebook').Strategy;
const FacebookTokenStrategy = require('passport-facebook-token');

const GoogleStrategy = require('passport-google-oauth20').Strategy;
// const GoogleTokenStrategy = require('passport-google-token').Strategy;
const GoogleTokenStrategy = require('passport-google-id-token').Strategy;

module.exports = function() {
  const app = this;

  let config = app.get('auth');

  config.facebook.strategy = FacebookStrategy;
  config.facebook.tokenStrategy = FacebookTokenStrategy;

  config.google.strategy = GoogleStrategy;
  config.google.tokenStrategy = GoogleTokenStrategy;

  app.set('auth', config);

  app.configure(authentication(config));
};
```

client

```
    app = feathers(),
    socket = io();

  app
    .configure(feathers.socketio(socket))
    .configure(feathers.hooks())
    .configure(feathers.authentication({
      storage: window.localStorage
    }));

  app
    .authenticate({
      google_id: '108367951653523343594',
      id_token: '...',
      strategy: 'google-id-token'
    })
    .then(function(response) {
      console.log(response);
    })
    .catch(function(error) {
      console.log(error);
    });
```

**Comment by HedCET** [comment]
i can't get the correct way of using it, pls help me

**Comment by marshallswain** [comment]
@HedCET Maybe post what you have done in a repo.  Since we are really busy (Feathers is built in our spare time), we need you to help us help you as much as possible.  :)

**Comment by marshallswain** [comment]
I might also add that without the extra effort on your part it kinda turns into a 1-on-1 training, which we can definitely do, but not for free since the time cost is high on our part.

**Comment by HedCET** [comment]
i think its the issue with feathers-authentication-client@^1.0.0
https://github.com/HedCET/Torrent-Alert-FEATHERS/blob/master/src/services/authentication/index.js

**Comment by HedCET** [comment]
@ekryski can u pls help its not working

[config.json]{https://github.com/HedCET/Torrent-Alert-FEATHERS/blob/master/config/default.json}
```
{
  "auth": {
    "facebook": {
      "clientID": "clientID",
      "clientSecret": "clientSecret",
      "scope": ["email", "public_profile"]
    },
    "failureRedirect": false,
    "google": {
      "clientID": "731987698101-thavlbcphk9v1kco7l7bl3q70dph819m.apps.googleusercontent.com",
      "clientSecret": "JVs09s23ytqnolXkU-HEvBgU",
      "scope": ["profile"]
    },
    "google-id-token": {
      "clientID": "731987698101-thavlbcphk9v1kco7l7bl3q70dph819m.apps.googleusercontent.com",
      "clientSecret": "JVs09s23ytqnolXkU-HEvBgU"
    },
    "secret": "FEATHERS_AUTH_SECRET",
    "successRedirect": false
  },
  "host": "localhost",
  "nedb": "../data/",
  "port": 3000,
  "public": "../public/"
}
```
[authentication config @ hook]{https://github.com/HedCET/Torrent-Alert-FEATHERS/blob/master/src/services/authentication/index.js#L32}
```
  app
    .configure(authentication(app.get('auth')))
    .configure(jwt())
    .configure(local())
    // .configure(oauth1())
    .configure(oauth2({
      name: 'google-id-token',
      Strategy: GoogleTokenStrategy
    }));
```

[index.html](https://github.com/HedCET/Torrent-Alert-FEATHERS/blob/master/public/index.html#L70)

```
  app.authenticate({
    id_token: '...',
    strategy: 'google-id-token'
  }).then(function(res) {
    console.log('response', res);

    return app.passport.verifyJWT(res.accessToken);
  }).catch(function(e) {
    console.log(e);
  });
```

**Comment by ekryski** [comment]
@HedCET which version of the plugins are you using? You might want to try upgrading to v1.0.0. Looks like your config is slightly off. Likely it was from the generator. Please check [the migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) on how to update your config file.

It looks like everything else is correct. What is the error you are getting? I can't really help with just "It's not working". 😁 

You can also try turning on debug mode. Lots of logs get spit out.

```
DEBUG=feathers-authentication* npm start
```
