### ISSUE TITLE
what does app.service('authentication').remove(...) mean?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-authentication#379]
In the example we see there are two methods available for `app.service('authentication')`: 

```js
app.service('authentication').hooks({
  before: {
    create: [
      // You can chain multiple strategies
      auth.hooks.authenticate(['jwt', 'local'])
    ],
    remove: [
      auth.hooks.authenticate('jwt')
    ]
  }
});
```

From `feathers-authenticate-client` I understand that the `create` method actually means calling `app.authencate(...)` from the client-side:

[https://github.com/feathersjs/feathers-authentication-client/blob/master/src/passport.js#L139](https://github.com/feathersjs/feathers-authentication-client/blob/master/src/passport.js#L139)

But I cannot find where the `remove` method of `app.service('authentication')` is called. I guess it's for `app.logout()` from the client-side, right?

**Comment by marshallswain** [comment]
I believe you are correct.  If you have some sort of stateful token blacklisting, you could implement it there.  I wondered the same thing, but I haven't read that part of the code, yet.

**Comment by beeplin** [comment]
You mean the `remove` method is for some possible customized behavior for `app.logout()`? But in fact I didn't see `app.logout()` calling the `remove` method. That's why I am puzzled.

**Comment by marshallswain** [comment]
The tests have the answer:  https://github.com/feathersjs/feathers-authentication/blob/0d1653fabd9745dd7b703c6acd2d65a734a44b0e/test/service.test.js#L102

There is also a middleware that listens for that method and calls logout.

**Comment by beeplin** [comment]
So the remove method just verify token, and is not necessarily used with logout(). It is only because we don't have a "verify" method so we chose "remove" to do this. -- is it correct?

**Comment by beeplin** [comment]
got it. thanks!
