### ISSUE TITLE
Missing code in example app

### ISSUE THREAD

**Issue by heymartinadams** [feathersjs/feathers-authentication#383]
Here: https://github.com/feathersjs/feathers-authentication/blob/master/example/app.js
Line 11: `const auth = require('../lib/index');`
Missing `/lib` folder.

**Comment by marshallswain** [comment]
@heymartinadams lib is actually a compiled folder.  I think you run `npm run compile` to get it in place.

**Comment by heymartinadams** [comment]
Gotcha, @marshallswain. Unfortunately, I wasn’t able to get it compiled. The npm command `"compile": "rimraf -rf lib/ && babel -d lib/ src/"` threw the following error.

`ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/martinadams/swifty/feathers-authentication/.babelrc" at 0, attempted to resolve relative to "/Users/martinadams/swifty/feathers-authentication"`

**Comment by marshallswain** [comment]
That's one of the devDependencies of `feathers-authentication`: https://github.com/feathersjs/feathers-authentication/blob/master/package.json#L67

Have you installed this directly from the repo?  It doesn't sound like you've installed from npm.  You probably need to `cd node_modules/feathers-authentication && npm install`.

**Comment by daffl** [comment]
If you run just the example, change

```js
const auth = require('../lib/index');
```

to

```js
const auth = require('feathers-authentication');
```

**Comment by heymartinadams** [comment]
Thank you, @daffl and @marshallswain.

Unfortunately, I’m having trouble migrating to feathers-authentication 1.0. Would any of you perhaps be willing to take a look at it? It’s a private repo, so I’ll invite you to it if you like. Built entirely on feathersJS (which is awesome, by the way :)

**Comment by marshallswain** [comment]
Absolutely.  I can offer a couple minutes.  My email's in my profile.

**Comment by heymartinadams** [comment]
Thank you, @marshallswain!
