### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by jiangts** [feathersjs/feathers-authentication#386]
I'm trying to migrate to feathers-authentication 1.0.x and followed the migration guide. However, it wasn't clear how to re-write the login page. I tried posting to `/authentication` but it returned the a json with 

    { accessToken: "SOME_TOKEN" }

Any tips on how to do this, and on setting redirects in general?

**Comment by marshallswain** [comment]
@jiangts `/authentication` is a regular Feathers service, so to get redirects, you'll need to create a separate Express middleware that calls `app.authenticate()` internally to get a token, then redirects and sends whatever you want back to the user.

**Comment by jiangts** [comment]
Maybe I'm missing some functionality in Express, but how do I redirect the client to say, `/app/` AND send a token back to the client? (sure, I can put it in a query param but this doesn't sound like the best idea security wise).

Also, will this be smoothly integrated into feathers-client-authentication as it was previously? (or maybe it was just integrated into the feathers-cli scaffold). I remember it magically kind of just worked when I posted to `/auth/local` before :).

**Comment by marshallswain** [comment]
What's the exact workflow you want to happen?  You authenticate with an Ajax request then handle the response on the client?  Or you want to post to a page and have a full redirect and page load?  There are a few ways to handle it.  The Ajax request works the most seamlessly with the feathers client.

**Comment by jiangts** [comment]
Aha, I think I might've been confused by the experience on feathers 0.7.x and feathers-client. In the feathers scaffold, /login.html doesn't include feathers-client yet /app/index.html just calls app.authenticate().then(showViewFn) and a JWT magically appeared in my localStorage. 

It seems that the login.html page now needs to include feathers-client and do a client side redirect to /app/ to get the same experience. Does that sound right?

**Comment by marshallswain** [comment]
You can definitely redirect if you prefer to do it.  Using Single Page App-style page routing will make it so you don't have to call `app.authenticate()` again when the next page loads.  Socket auth is stateful on the server.  Since doing a full redirect, whether on the client on the server, will disconnect the socket, you would have to call `app.authenticate()` to have an authenticated socket again.

**Comment by ekryski** [comment]
Dammit. I'll get those docs up to date by Monday for sho!

**Comment by jiangts** [comment]
Thanks so much! Shall I leave this open and you can close it when the docs are updated?

**Comment by tjme** [comment]
Similarly, is there any chance that feathers-chat will be updated in line with 1.0, as that might help clarify?

**Comment by marshallswain** [comment]
This is now implemented in the feathers-chat repo, auk branch.  The client examples will be updated one at a time.  The Feathers Vuex Chat example is already finished here: http://github.com/feathersjs/feathers-chat-vuex
