### ISSUE TITLE
can modify selected fields only

### ISSUE THREAD

**Issue by binarytracer** [feathersjs/feathers-authentication#397]
***using feathers-cli: 1.2.7***
Ive created a feathers application via ***feathers-cli*** .....  **all green** ... **done**.
so currently im on the feathers-authentication < 1.x, where i all all the hooks here, [cool legacy hooks](https://github.com/feathersjs/feathers-legacy-authentication-hooks),  can be utilize.

Now, is there a way / future plan / incoming stuff, that describes ``` ... allowing authorize users, to edit only specified fields in a document ... ```?

If no, how can I make it?

**Comment by eddyystop** [comment]
You would use before hooks for that.

**Comment by binarytracer** [comment]
i think ill can do this by,

```js
hooks = {
 before: {
    update: [
      ... /* roles related hooks here */, 
      controlPerFieldHook
    ]
 }
};

function controlPerFieldHook(hook, next){

  ... /* logic here */
 if( user.roles === "limited"){
   ... /* strip fields */
}

 next();
}
```
is there any better implementation than this?

**Comment by daffl** [comment]
You got it. A custom hook is definitely the way to go.

For more advanced permissions you can also have a look at https://github.com/feathersjs/feathers-permissions which is currently under development.

**Comment by binarytracer** [comment]
thanks @daffl. 
I think we need to upgrade first to **feathers-authentication >= 1.x** before using the **feathers-permissions.**
