### ISSUE TITLE
Authentication with an existing database with existing hashed (md5) passwords

### ISSUE THREAD

**Issue by swina** [feathersjs/feathers-authentication#398]
I am using a feathers client and server app.
Clients need to authenticate to an existing db (mysql) with passwords hashed (md5)
Using local authentication (email+password) and trying with the auth/local endpoints (with a corrected sequelize user model) I can't get authenticated. 
If I try to run the users endpoint (with no authentication required) I get user data correctly.
I suppose that this is due to different password hash algorithm that fails the authentication on db.
Any help is appreciated.

**Comment by MidnightP** [comment]
I sort of have the same issue. Would be interesting to learn what kind of hashing feathers uses and if there are some options for it.

**Comment by guyspronck** [comment]
You should create a custom verifier for local, see here: https://github.com/feathersjs/feathers-authentication-local#verifier

To answer @MidnightP: feathers uses bcrypt by default, which you would know if you took some time to read the readme.

**Comment by swina** [comment]
Thank you, I know that feathers uses bcrypts, I was just looking for if someone else has previuosly worked on it and how has been solved. I will look inside in order to develop a custom verifier. 
Thanks

**Comment by ekryski** [comment]
@swina see my answer here: https://github.com/feathersjs/feathers-authentication/issues/289#issuecomment-269734463

That should do it. I'm working on expanding the documentation to show this. Going to close this issue but feel free to comment if you have trouble.
