### ISSUE TITLE
Jwt default config

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers-authentication#401]
Now we have this default jwt config. How can I remove `subject` and `audience` options? As I see I can only extend them.
```
jwt: {
    header: { typ: 'access' }, // by default is an access token but can be any type
    audience: 'https://yourdomain.com', // The resource server where the token is processed
    subject: 'anonymous', // Typically the entity id associated with the JWT
    issuer: 'feathers', // The issuing server, application or resource
    algorithm: 'HS256', // the algorithm to use
    expiresIn: '1d' // the access token expiry
  }
```

**Comment by ekryski** [comment]
Any reason you want to do that? It's recommended that you fill those out with your own options as they are used to verify the authenticity of a JWT.

**Comment by sylvainlap** [comment]
Why do you force the subject to `anonymous` ? Shoudn't it be set with the entity id ?

**Comment by ekryski** [comment]
@sylvainlap we don't force it to anonymous. See my comment above. It can be overridden in either your config or adding a `before` hook on the `authentication` service to set `hook.params.jwt.subject = userId`.

We've been thinking about moving that by default into the core authentication service but haven't gotten around to it yet. PRs welcome 😄

**Comment by ekryski** [comment]
I'm going to close this as it's been over a month and no response. @kozzztya feel free to let us know if there is anything else or feel free to open a new issue if you are having trouble overriding the option.

**Comment by loris** [comment]
The problem is that it makes it pretty hard to upgrade from `v0.*` to `v.1+`. We do have a lot of never expiring tokens (safe because dedicated to very specific actions) in the wild without `aud` since it was not required back then.

**Comment by loris** [comment]
@ekryski by the way, I can't make this work `hook.params.jwt.subject = userId` in the `authentication` `before` hook (as of `v1.2.6`) because `hook.params.jwt` is undefined. I would like to have dynamic `expiresIn` option.

**Comment by alkurbatov** [comment]
Hello, feathers team.

>It can be overridden in either your config or adding a before hook on the authentication service to set hook.params.jwt.subject = userId.
I was wondering how this could be done in feathers. The suggested method works well at least in my code:
`function injectJWTSub() {
  return function (hook) {
      hook.params.jwt = hook.params.jwt || {}
      hook.params.jwt.subject = hook.data.username

    return hook
  }
}
`
which is called before authentication.hooks.authenticate(config.strategies).

However JWT verification reports than 'sub' is different from the one in the jwt config (still anonymous).

@ekryski could you please clarify the correct way specify the JWT subject during authentication?
