### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by elfey** [feathersjs/feathers-authentication#406]
https://github.com/feathersjs/feathers-authentication/blob/0d1653fabd9745dd7b703c6acd2d65a734a44b0e/src/utils.js#L17

Expected `noTimestamp`

Observed `noTimetamp`

**Comment by daffl** [comment]
[Defintely](https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback), good catch. Fix incoming shortly.

**Comment by daffl** [comment]
Fixed via #415
