### ISSUE TITLE
Make JWT data more configurable

### ISSUE THREAD

**Issue by elfey** [feathersjs/feathers-authentication#407]
We're currently stuck with a few limited options for the JWT token.

It would be great if we had full control over what goes in. For example, the ability to add our own custom fields and choose what field authentication places the userId in (i.e. `sub`).

JWT data is usually application specific, so it would make sense to allow that data to be configurable.

Ideally we'd be able to pass in a JSON object and the JWT data would be set to that JSON object. This would make everything malleable and controllable by the developer.

**Comment by daffl** [comment]
Upgrading to [version 1.0](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) you have full control over what payload gets put into the token. More details [can be found here](https://github.com/feathersjs/feathers-authentication/blob/master/docs/new-1.0-features.md#more-flexible-tokens).
