### ISSUE TITLE
v1.0 is removed from npm?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-authentication#408]
![image](https://cloud.githubusercontent.com/assets/13058150/22327274/5a43c214-e3f1-11e6-8e9a-80ba6a70863d.png)

**Comment by eddyystop** [comment]
We did not expect people to start using v1 in production when it was still a release candidate. We'll find a way to prevent this in the future.

The result is the channels are heavy with questions.

We've decided to return npm to v0.7 to stop more people going down the v1 route by default.

v1 is stable. ekryski is working on freeing up time to finish permissions and docs. Keep using v1 if you're happy with it. It will be returned to npm shortly.

**Comment by marshallswain** [comment]
You can still install it from npm using the version number.  It's just no longer the default, for a little while.

**Comment by daffl** [comment]
Wbat @eddyystop said. You can always install 1.x with

```
npm install feathers-authentication@pre
```

or

```
npm install feathers-authentication@^1.0.2
```

And any `^1.0` dependency in the `package.json`.

**Comment by beeplin** [comment]
got it, thanks, guys~ lookibg forward to the final permissions and docs.

**Comment by jcyh0120** [comment]
I had I question about version. It seems the code on github is different from the code from npm with the same version tag. Is it because the package delivered to npm was compiled by babel?

**Comment by marshallswain** [comment]
@jcyh0120 yep, it's pre-compiled.
