### ISSUE TITLE
Passwordless auth

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers-authentication#409]
Hi,

I'm about to deep dive into implementing a passwordless auth flow and was wondering if you had any starting pointers, tips or code snippets from the top of your head that would speed things up for me. I want:

1. "Login" link shows email input if no session is present
2. Submitting email sends a 1 hour login token
3. Clicking the link logs the user in for 30 days

That's it. Does feathers-auth make any assumptions about the presence of password? Am I better off implementing this flow completely from scratch or is feathers-authentication/feathers-authentication-management useful? 

Feel free to close this issue since it's not really an issue.

**Comment by marshallswain** [comment]
Only that feathers-authentication-management ought to help with putting this together.

**Comment by buildog** [comment]
@ekryski , @marshallswain any feathers-authentication-management example for SMS (https://github.com/feathersjs/feathers-authentication/issues/7) (short token) would be valuable too, I'm not sure that would work as from the doc:

_The user must be identified when the short token is used, making the short token less appealing as an attack vector._

**Comment by exppro** [comment]
This is not a big deal to make it by hand. The node-mailer may easy used for transport. I'd like to store user shema in mongo with email, sendedAt, verifiedAt, validBefore:Number, validateLink records. 
validateLink is just auto generated ObjectId by mongo (with salt), send it to user and then compare expiriedBefore < verifiedAt - sendedAt

**Comment by ekryski** [comment]
This is definitely doable. You can either do it custom as @Viskazz described or use `feathers-authentication-management`. [Visit the repo](https://github.com/feathersjs/feathers-authentication-management) for links to guides and docs.

So I think we're pretty covered here. Going to close to keep issues triaged and current.

**Comment by rhythnic** [comment]
https://github.com/rhythnic/feathers-passwordless-auth-example

**Comment by daffl** [comment]
Thank you @rhythnic. Can you add it to https://github.com/feathersjs/feathers-docs/edit/master/ecosystem/readme.md ?
