### ISSUE TITLE
how to disable service for external usage in version 1.0

### ISSUE THREAD

**Issue by chuan137** [feathersjs/feathers-authentication#410]
There used to be a disable hook in version 0.7. And I can't find it in the legacy hooks package. What is then the standard method for this functionality?

**Comment by daffl** [comment]
The `disable` hook is not part of `feathers-authentication` and can still be used the same way through the `feathers-hooks-common`package.

```js
const commonHooks = require('feathers-hooks-common');

const disableExternal = commonHooks.disable('external');
```

**Comment by chuan137** [comment]
I see, I was looking for it in the feathers-legacy-authentication-hooks package.
