### ISSUE TITLE
Request body 'token' parameter disappears

### ISSUE THREAD

**Issue by Alendorff** [feathersjs/feathers-authentication#420]
Using feathers-authentication 0.7.12.
In feathers-authentication\lib\middleware\express.js I found this code:
```javascript
    // Check the body next if we still don't have a token
    if (req.body.token) {
      token = req.body.token;
      delete req.body.token;
    }
```
And same for req.params. I wanted to ask why you are removing the token from everywhere? I tried to use a `token` field in POST body for my custom middleware, and I was confused a bit when all the time the token disappeared on server-side . Is there some security reason or ... ?

**Comment by daffl** [comment]
This was a bug in v0.x. If this is an issue I'd recommend trying to [upgrade to v1.0](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md).

**Comment by Alendorff** [comment]
Alright then, let's close it.
