### ISSUE TITLE
Error is not thrown if token that is provided is invalid

### ISSUE THREAD

**Issue by elfey** [feathersjs/feathers-authentication#421]
If an invalid `feathers-jwt` token exists in the `localStorage` of a browser and `app.authenticate()` is called, the `Promise` on the client side *always* resolves, whether or not the token was valid on the server.

I'm assuming that this is because an error isn't thrown on the server side when authentication fails via the JWT authentication strategy.

This has obvious implications on the client side, because now error handling has to be done via `.then` as opposed to `.catch`.

Again, the Promise *always* ends up resolving whether or not the JWT token that is passed to the server is valid.

**Comment by daffl** [comment]
I think we should move this issue to https://github.com/feathersjs/feathers-authentication-client. Either way, you are right, an invalid JWT shouldn't resolve. I'd have to double check why that is.

**Comment by ekryski** [comment]
This shouldn't be happening. I will look into this a bit but @elfey it would help a ton if you can post a reproducable example or a PR with a breaking test. We do have tests to test this case already that are passing. https://github.com/feathersjs/feathers-authentication-client/blob/master/test/integration/rest.test.js#L88-L132

**Comment by elfey** [comment]
Will do, I'll get an example in here within the next few days.

**Comment by elfey** [comment]
After speaking with Marshall and doing some more thorough debugging, it looks like this actually isn't a problem of feathers; it's a problem specific to my project.
