### ISSUE TITLE
Auth redirect issue

### ISSUE THREAD

**Issue by exppro** [feathersjs/feathers-authentication#425]
Sorry, im noob. I have this folder structure on server:

```
 |_src/ ...with services, middleware inside, etc..
 |_public/
     |_ css/
     |_ js/
     |_ views/
          |_ operator/
          |_ not-auth-conent/
```

I'm attempting to redirect success auth to /operator folder like this:
```
app.get('/auth/success', function (req, res) {
  res.sendFile(path.resolve(__dirname, '/views/operator/operator.html'));
});
```

There is no issue with 'not-auth-content' htmls, which i can render with res.render() via ejs engine. And paths looks like localhost/operator, localhost/whatever. I.e. without 'view'. But redirect not working at all. 
I dont want to use config successRedirect option to ../../../views/operator/operator.html cause it's open server folder structure. That's the problem with res.sendFile ? I have a same small app w\o feathers (only express) and redirects works well.

**Comment by marshallswain** [comment]
@exppro I don't see anything that would cause a problem, there.  You should be able to go to `/auth/success` and see your `operator.html` file even without logging in.  If that's not the case, could you post a stripped down version of your repo that we could check?

**Comment by ekryski** [comment]
@exppro did you get it sorted? I'm going to assume yes and close this out. Feel free to let us know if not.
