### ISSUE TITLE
Authentication over socket.io never answers

### ISSUE THREAD

**Issue by PierBover** [feathersjs/feathers-authentication#428]
When using rest everything works fine, but when doing `authenticate(...)` from the client using socket.io the promise never resolves or rejects.

We can see in the logs that the requests are indeed reaching the server at `/socket.io/?EIO=3&transport=websocket&sid=4dYbvCOb3Bkrw_mWAABM` and queries are being done on the DB... but in the client nothing happens.

This is how we configure feathers client:
```
const socket = io('https://XXXX.com');

const client = Feathers()
.configure(hooks())
.configure(socketio(socket))
.configure(FeathersAuth({
	storage: localStorage,
	path: '/auth/local'
}));

socket.io.engine.on('upgrade', function(transport) {
	console.log('transport changed');
	client.authenticate();
});
```

Then: 
```
const options = {
	strategy: 'local',
	username,
	password
};

FeathersClient.authenticate(options).then((response) => {
	console.log("Authenticated!");
}).catch((error) => {
	console.log("Authentication error", error);
});
```

Any idea what might be happening?

**Comment by daffl** [comment]
Please send the versions of the server and client packages you are using (`npm ls feathers-authentication`).

**Comment by PierBover** [comment]
We are using `0.1.9` in the client and `0.7.12` in the server.

**Comment by PierBover** [comment]
@daffl pointed out via Slack that I need to use `feathers-authentication@0.7.x/client` and not `feathers-authentication-client`
