### ISSUE TITLE
`hook.params.provider` is not set when calling `client.authenticate()`

### ISSUE THREAD

**Issue by huafu** [feathersjs/feathers-authentication#432]
When calling `client.authenticate()` in the client (here I'm using `socket.io`), the `authenticate.create` service method is called on the server, but `hook.params.provider` is `undefined` while I think it should be set, even tho the `client.authenticate()` is triggering this service call thru a custom socket event. Same for `client.logout()`.

I am using `1.0.2` version of `feathers-authentication`.

**Comment by ekryski** [comment]
Agreed. Thanks for the issue. I'll try and tackle that one quickly.

**Comment by marshallswain** [comment]
Fixed in #459

**Comment by daffl** [comment]
Going to close this we'll release shortly.

**Comment by IamCarbonMan** [comment]
Any update on this? It's been several months and this is preventing me from being able to do

    commonHooks.when(hook => hooks.params.provider, commonHooks.discard("password"))

which is pretty necessary for proper security.

**Comment by daffl** [comment]
This has been released in v1.2.0 (see https://github.com/feathersjs/feathers-authentication/blob/master/CHANGELOG.md#v120-2017-03-23)

**Comment by IamCarbonMan** [comment]
I'm using 1.2.7 and still having the same issue.

**Comment by daffl** [comment]
@marshallswain Any thoughts?

**Comment by IamCarbonMan** [comment]
My setup is definitely not the standard feathers-cli generated app, so it might be something else. The server is a single file, here it is in a [gist](https://gist.github.com/IamCarbonMan/f1374ecb0fb6d1adb8fd57158d55fad5). The actual error I get in the browser when calling client.authenticate is "cannot read property provider of undefined", suggesting that hook.params is itself undefined for some reason.

**Comment by daffl** [comment]
You have a typo in https://gist.github.com/IamCarbonMan/f1374ecb0fb6d1adb8fd57158d55fad5#file-server-js-L16. It should be `hook.params.provider` not `hooks.params.provider` (hence the error you were getting).
