### ISSUE TITLE
Passwordfeld in auth.local does not work as expected

### ISSUE THREAD

**Issue by longntp** [feathersjs/feathers-authentication#435]
My password field in DB is not "password" as usual. It saves nested inside another object (just call it "something")
So my default.json file is like below right?, I can not find any documents mentions about that case. Sorry if I missed anything.
`
"local": {
      "usernameField": "username",
      "passwordField": "services.something"
    },
`

**Comment by daffl** [comment]
v0.7.x `passwordField` does not support the dot notation. You will have to [upgrade to v1.0.0](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md).
