### ISSUE TITLE
Not useful error message on NotAuthenticated error

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-authentication#436]
When logging in with wrong credentials we get a `NotAuthenticated` error but the message just says `Error` which is not a very helpful text to display:

![screen shot 2017-03-06 at 12 51 35 pm](https://cloud.githubusercontent.com/assets/338316/23629289/1c6e3d86-026c-11e7-9cd4-b9712009e744.png)

`feathers-authentication` @1.x

**Comment by ekryski** [comment]
I noticed that over here as well. I'll look into it today.

**Comment by ekryski** [comment]
@daffl which way were you logging in? I was getting it when the JWT was expired or when using a custom verifier the credentials didn't exist in the DB.

**Comment by daffl** [comment]
Local auth with the wrong username or password.

**Comment by daffl** [comment]
It looks the `NotAuthenticated` error is getting passed an object somewhere that doesn't have a `message` property which will then just default to `Error` in https://github.com/feathersjs/feathers-errors/blob/master/src/index.js#L26.

**Comment by ekryski** [comment]
Closing in favour of tracking here: https://github.com/feathersjs/feathers-authentication-local/issues/10
