### ISSUE TITLE
createJWT throws 'secret must provided'

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-authentication#437]
The doc says `app.passport.createJWT(payload, options)` will pull from config automatically, but I'm getting `secret must provided` error when calling `app.passport.createJWT(payload)`

**Comment by marshallswain** [comment]
@whollacsek please show your config and let us know the version numbers of the auth plugins used.

**Comment by whollacsek** [comment]
Looking at the source code of `createJWT` (https://github.com/feathersjs/feathers-authentication/blob/master/src/utils.js) the app config is not loaded, so I'm using `hook.app.service('authentication').create({})` instead.

**Comment by Mattchewone** [comment]
@whollacsek You config should look something similar to this:
```
  "authentication": {
    "secret": "<TOKEN>",
    "strategies": [
      "jwt",
      "local"
    ],
    "path": "/authentication",
    "service": "users"
  },
```

**Comment by whollacsek** [comment]
@Mattchewone I didn't know it's necessary to setup `"strategies": [
      "jwt",
      "local"
    ]` can you point me to the docs about this?

**Comment by Mattchewone** [comment]
I may be leading you down the wrong path @whollacsek I was reading the v1 docs - https://github.com/feathersjs/feathers-authentication/tree/master

If you are not using that then you can ignore my comment.

**Comment by whollacsek** [comment]
@Mattchewone I'm on v1, but the doc doesn't talk about setting `"strategies": [ "jwt", "local" ]` in the configs

**Comment by Mattchewone** [comment]
@whollacsek The strategies is just a preference for doing this:
```
const config = app.get('authentication');
auth.hooks.authenticate(config.strategies);
```

Looking at the authenticate init method strategies are not being used, I guess as each strategy needs to be initialised separately.

Do you have your config and your authenticate configuration?

**Comment by daffl** [comment]
The docs are wrong. `app.passport.createJWT` and `app.passport.verifyJWT` needs options passed.
