### ISSUE TITLE
setCookie express middleware only works inside hooks

### ISSUE THREAD

**Issue by HenriBeck** [feathersjs/feathers-authentication#438]
Apparently, the middleware checks if it's being called by a hook though I think that it should be possible to pass it to app.get() too.

Example: https://gist.github.com/HenriBeck/fa1fa401b8193da765e207fa4e4ca750

https://github.com/feathersjs/feathers-authentication/blob/master/src/express/set-cookie.js#L27

This block is never run because res.hook is undefined and no cookie is set.

**Comment by marshallswain** [comment]
Can you help clarify what the goal is in this issue?  We want cookies to be ignored by the API server.  It can set cookies, because that helps with SSR, but we don't want a cookie to get consumed directly by any Feathers service.  That opens up the service to CSRF attacks.

**Comment by HenriBeck** [comment]
[This line](https://gist.github.com/HenriBeck/fa1fa401b8193da765e207fa4e4ca750#file-authentication-js-L53) does nothing. It doesn't set the cookie as you would expect. 

That's because in the middleware it checks if it has been called after a service method.

**Comment by HenriBeck** [comment]
Closing as it's the same as #389
