### ISSUE TITLE
Readme incorrect and maybe docs to

### ISSUE THREAD

**Issue by genyded** [feathersjs/feathers-authentication#440]
The readme has:
```javascript
import localstorage from 'feathers-localstorage'
```
... but that is never referenced anywhere else (and for us our linters also fail). 'window.localStorage' is used though and we'd fix the readme but it's unclear to us which which one should be used or if it matters. Also, what if the browser does not support localStorage?

**Comment by marshallswain** [comment]
I think we can remove the line you've posted, above.  You can use any storage engine that implements the [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API).  For example, if your app needs to access localStorage while in Private Browser Mode, you can use https://github.com/localForage/localForage to fill that need.

**Comment by genyded** [comment]
We commented it out for now, but yes - one or the other should be used in the code and maybe a note added to clarify that any can be used.

**Comment by marshallswain** [comment]
The docs will cover the clarification.  I'll just remove that line for now.

**Comment by genyded** [comment]
Cool and thanks as usual!

**Comment by marshallswain** [comment]
done in https://github.com/feathersjs/feathers-authentication/commit/766305441663470eda6d0d095e5d37d575f5b223

**Comment by marshallswain** [comment]
Thanks @genyded!  Every detail counts heaps.
