### ISSUE TITLE
Another readme incorrect and maybe docs to

### ISSUE THREAD

**Issue by genyded** [feathersjs/feathers-authentication#441]
Trying to execute the (client) code as is from the readme fails (even if #440 is addressed) because apparently hooks are required for auth but they are not imported (or configured) per the readme code:

```
Error: It looks like feathers-hooks isn't configured. It is required before running feathers-authentication
```

**Comment by marshallswain** [comment]
It looks like the hooks plugin is used in the README.  Am I looking at the wrong branch?  I'm in `legacy` in the screenshot, below.

![screen shot 2017-03-09 at 3 37 54 pm](https://cloud.githubusercontent.com/assets/128857/23773895/691bf46a-04de-11e7-9775-13124a9ad753.jpg)

**Comment by genyded** [comment]
You're in the right place, but that is the SERVER code, we're talking about the client code just below it:
```javascript
import io from 'socket.io-client';
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import socketio from 'feathers-socketio/client';
import localstorage from 'feathers-localstorage';
import authentication from 'feathers-authentication/client';

const socket = io('http://localhost:3030/');
const app = feathers()
  .configure(socketio(socket)) // you could use Primus or REST instead
  .configure(hooks())
  .configure(authentication({ storage: window.localStorage }));

app.authenticate({
  type: 'local',
  'email': 'admin@feathersjs.com',
  'password': 'admin'
}).then(function(result){
  console.log('Authenticated!', result);
}).catch(function(error){
  console.error('Error authenticating!', error);
});
```

**Comment by genyded** [comment]
OK maybe we we're in the wrong place... whereever we copied and pasted from did not the hooks, but we see they are there now. Sorry.
