### ISSUE TITLE
How to authenticate SPA? More precisely how does the redirect works? 

### ISSUE THREAD

**Issue by DaviTeodoro** [feathersjs/feathers-authentication#451]
Guys, I do not know if it's the right place to ask, but I can not get my head around this. I've been looking for some explanation around, but couldn't find any, so here it goes:

I have a SPA (vuejs) totally decoped from my rest-api (feathersjs) and I just using <s>oauth0</s> feathers-authentication-oauth2 for authentication (google and facebook)
Currently my stream looks like:

1)
```
+--------------------+               +----------------+
| JS Single Page App | - redirect -> | OAuth Provider | - user enters credentials
+--------------------+               +----------------+
```
2)

```
+----------------+                                   +----------+
| OAuth Provider | - redirect with temporary code -> | REST API |
+----------------+                                   +----------+
```
3)

```
+----------+                                      +----------------+
| REST API | - request access token using code -> | OAuth Provider |
+----------+ <- return access token ------------- +----------------+
```

What should I do now? My current understanding is that I should redirect the user upon receiving the access token to a page that will load the JS single page app again. It is that correct? If so, how do I do it? I cant understand how this process works. Thank you

**Comment by beanmoss** [comment]
So your user provider is OAuth and not Feathers?

**Comment by DaviTeodoro** [comment]
I think I expressed myself wrong. I'm using feathers-authentication to generate the JTW. But I'm not using the local method, just google and facebook. With the local method I just need to send a post request to the correct endpoint and wait for a promisse holding the JWT, then I would store it in my SPA and use it in the subsequent requests. 
My problem is with the google/facebook methods. Because in the client-side I have a link or a redirect to my authentication providers endpoint (ie. /auth/facebook), but I dont know how to send the JWT back to the SPA. It is not a big problem, I think, but it is my first time doing it, and I'm little confused.

**Comment by daffl** [comment]
What version are you using? Basically with oAuth what you have to do is enabled cookies, hit the auth endpoint, redirect back to your app and then call `app.authenticate()` (with no arguments) for auth to try to get the JWT from the cookie the oAuth flow has set for you.

**Comment by DaviTeodoro** [comment]
Hello David , I'm using "feathers-authentication": "^1.1.1", "feathers-authentication-jwt": "^0.3.1" and "feathers-authentication-oauth2": "^0.2.3". I noticed that with version > 0.8.0 the redirection changed but can't figure out how to setup it correct.

**Comment by DaviTeodoro** [comment]
OK, @marshall did help me to implement a custom handler that redirect JWT to the custom url in a different domain. 
The handler: 
``` javascript
const jwt = require('jsonwebtoken');

module.exports = function (options, jwtOptions) {
  const { secret } = options;
  if (!secret) {
    throw new Error(`You must provide a 'secret' attribute to the popups middleware options.`);
  }

  return function (req, res, next) {
    if (req.feathers && req.feathers.payload) {
      jwt.sign(req.feathers.payload, secret, jwtOptions, (err, token) => {
        if (err) {
          console.log(`Couldn't create JWT`, err);
        }
        // res.send(template);
        res.redirect(`${options.github.successRedirect}?token=${token}`);
      });
    }
  };
};
```

Now you have to use it in the authentication.js

```javascript
'use strict';

const authentication = require('feathers-authentication');
const jwt = require('feathers-authentication-jwt');
const oauth2 = require('feathers-authentication-oauth2');
const GithubStrategy = require('passport-github');
const handlePopups = require('./popups-middleware');

module.exports = function () {
  const app = this;
  const config = app.get('authentication');
  const jwtConfig = app.get('jwt');

  config.github.Strategy = GithubStrategy;
  // Add the handler to the github auth config
  config.github.handler = handlePopups(config, jwtConfig);

  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(oauth2(config.github));

  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};
``` 
That is it.

**Comment by ekryski** [comment]
@marshallswain you and I talked about putting the token in querystring by default when redirecting, did you have a PR planned for that?

**Comment by marshallswain** [comment]
@ekryski I was thinking of always using the query string, but I had a conversation with @daffl and he fixed my thinking.  I'm focusing on another PR for auth right now, but I'll get to this after it.

**Comment by marshallswain** [comment]
Here's a simplified OAuth handler: https://gist.github.com/marshallswain/3c9e5b3b177b977468b5b711b6254f67
