### ISSUE TITLE
Question: When is userId set?

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-authentication#453]
The migration doc says:
> [By default the payload for your JWT is simply your entity id (ie. `{ userId }`).](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md#customizing-jwt-payload)

I've been grep'ing around for a while and l couldn't find the related code. (I searched for `userId`, `entity`, `_id`)

Is the doc wrong?

I'm looking for this because when I call `app.service('/authentication').create({payload: {userId: _id}, jwt: {expiresIn: '10m'}})` I have to specify the payload part (`{payload: {userId: _id}`) otherwise the `userId` will not be set.

**Comment by daffl** [comment]
Are you able to make this call from the client or is it on the server?

Normally the user id is set in a `before` `/authentication` hook as the migration document shows:

```
// Authenticate the user using the a JWT or
// email/password strategy and if successful
// return a new JWT access token.
app.service('authentication').hooks({
  before: {
    create: [
      auth.hooks.authenticate(['jwt', 'local']),
      customizeJWTPayload()
    ]
  }
});
```

The `local` strategy will take the username and password submitted to `/authentication`, look it up in the database, verify the password and will then update the payload for the JWT that is created accordingly.

**Comment by whollacsek** [comment]
I'm calling this on the server side, I only use the `jwt` strategy.
So strategies other than `local` will not insert the `userId` into jwt payload?

**Comment by whollacsek** [comment]
Hum ok I just realized that it doesn't make any sense to have the jwt strategy insert the `userId` automatically, since I'm calling the authentication endpoint on the server side there's no way for it to get the userId by it self.
