### ISSUE TITLE
1.0 authentication service hooks don't run when client uses feathers-socketio

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#455]
The authentication service hooks don't get hit when I use the `feathers-socketio` transport.  In the example, below, the hook only runs if I use `feathers-rest`.

```js
app.service('authentication').hooks({
  before: {
    create: [function (hook) {
      // OOPS, this only runs during requests from feathers-rest
      console.log(hook);
    }]
  },
  after: {
    create: [authHook(options)]
  }
});
```

**Comment by ekryski** [comment]
Really? I'll see if I can reproduce. We've been using auth with an app that was exclusively using sockets and those hooks were being run. Maybe related to #432?

**Comment by marshallswain** [comment]
@ekryski yeah.  They do run as long as authentication passes.  I'm currently working on a PR that will hopefully fix this.  

The problem is that we manually call authenticate [here](https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L83) before creating a token [here](https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L130).  I'm hoping I can adapt it to use the authenticate hook, so we can hit those hooks before auth is attempted.

**Comment by marshallswain** [comment]
You can reproduce this pretty easily by setting up a simple logging before hook on `authentication`, then botching your password in local auth.  Switch back to the correct password and it'll hit, but it's out of order when compared to `feathers-rest` auth.
