### ISSUE TITLE
Add event filtering by default (socket.io)

### ISSUE THREAD

**Issue by johncrisostomo** [feathersjs/feathers-authentication#460]
"authentication created" events are propagated to everyone (with the accessToken), even with logged out users. I think this should be filtered/silenced by default.

**Comment by marshallswain** [comment]
@johncrisostomo That definitely needs to be addressed.  Which version of `feathers-authentication` are you reporting on?

**Comment by johncrisostomo** [comment]
@marshallswain v1.1.1. Thanks @daffl for #461 , I am closing this now and I'll remove the custom filter from my project.
