### ISSUE TITLE
how can I logout using local authentication?

### ISSUE THREAD

**Issue by pedrommuller** [feathersjs/feathers-authentication#465]
This is a question rather than an issue:

I'd like to know if there is a specific endpoint to do a log out from the API like "/logout" if not how can I implement the logout method in the server?

M mental map is like having a simple link (href="/logout") on the client side like I mentioned earlier do the procedure and then redirect to the homepage "/"

I've been looking for that in the documentation and I didn't find anything.

Thanks!

**Comment by marshallswain** [comment]
Hi @pedrommuller, If you start an app with the feathers-cli pre-release generator (`npm install -g feathers-cli@pre`), you'll be able to use the `feathers-authentication-client`.  The two new plugins together include a logout implementation.  The new client plugin actually sets up `app.logout()` to interact with the server to accomplish this.

**Comment by ekryski** [comment]
I'll add that it doesn't do anything other than discard your `accessToken` on the client, and trigger a log out event on the server. If you wanted to ensure the JWT access token can't be used before it expires you would need to manually blacklist it yourself.

**Comment by ekryski** [comment]
Going to close this as I think @marshallswain answered, but @pedrommuller feel free to comment if that's not the case and we can re-open. 😄

**Comment by marshallswain** [comment]
@ekryski kind of touched on this, but it's also important to note that the `/authentication` service has a remove method.  It's what handles the `logout` on the server side.  You can customize the behavior by adding before and after hooks on it:

```js
// on the server
app.service('authentication').hooks({
  before: {
    remove: [
      function (hook) {
        // Customize the logout flow in hooks
      }
    ]
  },
  after: {
    remove: [
      function (hook) {
        // Customize the logout flow in hooks
      }
    ]
  },
  error: {
    remove: [
      function (hook) {
        // Customize the logout flow in hooks
      }
    ]
  }
});
```
