### ISSUE TITLE
app.authenticate not working

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-authentication#466]
According to docs, https://docs.feathersjs.com/v/auk/api/authentication/server.html#appauthenticatedata, `app.authenticate(data)` can be used to generate a jwt.

In my app, I tried to use this fonction:
```
// create accessToken
    const accessToken = await app.authenticate({
      strategy: 'local',
      email: user.email,
      password,
    });
```

As a result, accessToken seems to be a function...

I'm using feathers-authentication v1.2.0

**Comment by corymsmith** [comment]
`authenticate` returns a promise and the result is an object like: 
```
{
    accessToken: "<ACCESS TOKEN>"
}
```

**Comment by sylvainlap** [comment]
Actually, `authenticate` do not return a promise.

Here is an example, with `feathers-authentication` v1.2.0:

I created this middlware:

```
module.exports = (app) => (req, res, next) => {
  return app.authenticate({
    strategy: 'local',
    email: 'toto@example.com',
    password: 'pass'
  })
  .then(token => {
    console.log(token)
    return next()
  })
  .catch(next)
}
```

When I hit the endpoint, I got this error:

```
{
  "name": "GeneralError",
  "message": "app.authenticate(...).then is not a function",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}
```

**Comment by sylvainlap** [comment]
I tried to debug with vscode, and `app.authenticate` seems to be set by:

passport/lib/authenticator.js:
```
Authenticator.prototype.authenticate = function(strategy, options, callback) {
  return this._framework.authenticate(this, strategy, options, callback);
};
```

`app.authenticate` seems to be the same as `passport.authenticate`.

**Comment by marshallswain** [comment]
Oh wow.  I'm not sure how I did that.  I must have gotten my wires crossed with the client while I was writing the docs the other day.  Good grief.

So the real docs for `app.authenticate` are currently here: http://passportjs.org/docs/authenticate

I know where to spend my next couple of hours in the docs.  😇

**Comment by corymsmith** [comment]
I also read the issue wrong, I thought you were trying to call authenticate using feathers-authentication-client

**Comment by marshallswain** [comment]
@ekryski and I have decided to pull `app.authenticate` from the documentation.  Since there is no reason to call app.authenticate on the server, ever.  If the server needs to authenticate with another server, it should use the `feathers-authentication-client`.  The `app.authenticate()` method will only be useful for creating custom transport plugins (alternatives to feathers-socketio and feathers-rest).  We will actually be renaming the method to `app._authenticate` to denote that it's more of a "private" API.  Later, when we are ready to add documentation for creating custom Transports and auth plugins, we will add it to the docs as part of that phase.

There are two ways of creating JWT:
1. The `app.passport.createJWT()` method allows you to manually create a JWT and bypass the authentication.  On the server, it's more likely that you'd use this method for any custom tokens you need to create, for whatever obscure reason.
2. The `app.service('/authentication').create()` method runs through the same process as calling the `.authenticate()` method from the client.  The authorization service is basically the public endpoint for login and logout.

**Comment by marshallswain** [comment]
Thanks @sylvainlap for discovering the problem.

**Comment by kajallogic** [comment]
authentication.js

const authentication = require('feathers-authentication');
const jwt = require('feathers-authentication-jwt');
const local = require('feathers-authentication-local');
const express=require('express');
const feathers=require('@feathersjs/feathers');
const app=express(feathers());

module.exports = function () {
  const app = this;
  const config = app.get('authentication');
  
  
  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local());

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)

 
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};



src/service/users/users.hooks.js

const { authenticate } = require('feathers-authentication').hooks;
const commonHooks = require('feathers-hooks-common');
const { restrictToOwner } = require('feathers-authentication-hooks');
const { hashPassword } = require('feathers-authentication-local').hooks;

const restrict = [
  authenticate('jwt'),
  restrictToOwner({
    idField: 'id',
    ownerField: 'id'
  })
];

module.exports = {
  before: {
    all: [],
    find: [ authenticate('jwt') ],
    get: [  ],
    create: [hashPassword() ],
    update: [ ...restrict, hashPassword() ],
    patch: [ ...restrict, hashPassword() ],
    remove: [ ...restrict ]
  },

  after: {
    all: [
      commonHooks.when(
        hook => hook.params.provider,
        commonHooks.discard('password')
      )
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

localhost:3030/users/
After runing the about authentication in postman i am getting below error
{
    "name": "NotAuthenticated",
    "message": "jwt malformed",
    "code": 401,
    "className": "not-authenticated",
    "data": {
        "name": "JsonWebTokenError",
        "message": "jwt malformed"
    },
    "errors": {}
}


anybody can tell me the flow of authentication??
