### ISSUE TITLE
OAuth guides

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#470]
These are the guides we need for OAuth (all I can think of):

- [ ] OAuth through redirect.  (Navigating to `/auth/github`)
- [ ] OAuth through a popup window where both Web client and API server are on the **same domain**.
- [ ] OAuth through a popup window on where the Web client and API server are on **different domains**
  - [ ] https://github.com/feathersjs/feathers-authentication-oauth1/issues/6
  - [ ] https://github.com/feathersjs/feathers-authentication-oauth2/issues/7
- [ ] Token-based OAuth, like [`passport-github-token`](https://github.com/ghaiklor/passport-github-token)
- [ ] React Native OAuth with deep linking
  - [ ] https://github.com/feathersjs/feathers-authentication-oauth1/issues/7
  - [ ] https://github.com/feathersjs/feathers-authentication-oauth2/issues/8
- [ ] Customizing the OAuth payload.  

Seems like some of this might exist, already.  I'm planning on aggregating it all out into the Guides section of the docs, since it doesn't really qualify as API docs.

**Comment by ekryski** [comment]
@marshallswain is that where you want to put it? In guides? I think that's where it should go and I believe we already have an issue for this over there. Doesn't really make sense to have multiple issues for the same thing....

On the note of the guides I have a bunch of drafts already locally. I will try and publish them in the next couple days.

**Comment by marshallswain** [comment]
I didn't see any issues for it, and thought we might as well put it here instead of creating matching issues in each repo.  I think it's a good idea to make them a continuation of the Chat Guide, but keep them in a separate OAuth section, outside the Chat Guide.

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-docs #452](https://github.com/feathersjs/feathers-docs/issues/452) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ekryski** [comment]
Yup on the blog it is!
