### ISSUE TITLE
app.authenticate error : UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): * Error *

### ISSUE THREAD

**Issue by RileyDavidson-Evans** [feathersjs/feathers-authentication#476]
### Steps to reproduce
using react native :
app.authenticate on the client

### Expected behavior
Promise is returned with token or error

### Actual behavior
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): * Error *

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
Which module versions and React Native versions?

**Comment by RileyDavidson-Evans** [comment]
react native : 
`"dependencies": {
    "body-parser": "^1.17.1",
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.1",
    "feathers-errors": "^2.6.3",
    "feathers-hooks": "^1.8.1",
    "feathers-localstorage": "^1.0.0",
    "feathers-memory": "^1.1.0",
    "feathers-rest": "^1.7.1",
    "feathers-socketio": "^1.5.2",
    "localstorage-memory": "^1.0.2",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.2",
    "socket.io-client": "^1.7.3"
  },`

server : 
`"dependencies": {
    "body-parser": "^1.17.1",
    "compression": "^1.6.2",
    "cors": "^2.8.3",
    "feathers": "^2.1.1",
    "feathers-authentication": "^0.7.12",
    "feathers-configuration": "^0.3.3",
    "feathers-errors": "^2.6.3",
    "feathers-hooks": "^1.8.1",
    "feathers-mongoose": "^3.6.2",
    "feathers-rest": "^1.7.1",
    "feathers-socketio": "^1.5.2",
    "mongoose": "^4.9.3",
    "passport": "^0.3.2",
    "passport-facebook": "^2.1.1",
    "passport-facebook-token": "^3.3.0",
    "passport-google-oauth20": "^1.0.0",
    "passport-google-token": "^0.1.2",
    "serve-favicon": "^2.4.2",
    "winston": "^2.3.1"
  },`

**Comment by marshallswain** [comment]
You have a module version mismatch.  You should be using `feathers-authentication-client` in your RN app and `feathers-authentication` version ^1.2.1 on the server.  Can you try that out and report back?

**Comment by daffl** [comment]
I think @marshallswain identified the problem. The issue with the bad error message is also being tracked in https://github.com/feathersjs/feathers-authentication-local/issues/10.

**Comment by ekryski** [comment]
Sounds good. Going to close until further notice, to keep things curated. @RileyDavidson-Evans let us know if that doesn't solve your problem and we can re-open.
