### ISSUE TITLE
Incompatible old client dependency

### ISSUE THREAD

**Issue by vwong** [feathersjs/feathers-authentication#479]
I have been using 1.0.2 of this package along with `feathers-authentication-client` 0.3.1, and recently updated to the latest 1.2.1.

My Google authentication strategy broke with the upgrade, and I think I've managed to narrow it down to #433 that added an older (perhaps incompatible?) version of `feathers-authentication-client` 0.1.10.

Do you know why an older version is referenced?

**Comment by marshallswain** [comment]
Hi, @vwong. The version that's referenced is actually a lower version number, but a newer package.  The latest authentication package uses the `feathers-authentication-client`, which now has it's own repository.  Can you share the error you are seeing.  I might be able to point you in the right direction.

**Comment by daffl** [comment]
That doesn't make any sense. It says the [latest version](https://github.com/feathersjs/feathers-authentication-client/releases) is 0.3.1 and that's the one that should be used no? I made a PR for this in #480. No idea why Greenkeeper didn't catch that.

**Comment by vwong** [comment]
@marshallswain Are you implying that 0.1.10 is a more recent version than 0.3.1?

@daffl That seems to be the fixed required, but somehow I don't seem to be able to test it.  I updated `package.json` with:

```
-    "feathers-authentication": "^1.0.2",
-    "feathers-authentication-client": "^0.3.1",
+    "feathers-authentication": "git://github.com/feathersjs/feathers-authentication.git#a77b557942a4ef1f1647ed85fd4ab51f88902fe5",
````

and despite having the correct package in `node_modules`, I end up with the following when trying to execute `node /webpack/output/file.js`

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'feathers-authentication'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/webpack/output/file.js:148:18)
    at __webpack_require__ (/webpack/output/file.js:20:30)
```

Can you provide pointers on how I might be able to test #480?

**Comment by daffl** [comment]
You will not be able to test dependencies directly from GIT since they have a compile step. You can clone the repository, check out the PR branch and then `npm link` in the repo folder as well as `npm link feathers-authentication` in the project folder. I'm pretty confident it's the right fix though and will get it out right away.

**Comment by vwong** [comment]
Ah, the compile step would've explained it.  I think I'll just wait for a new version...  Thanks!

**Comment by vwong** [comment]
Just thought I'd chime in to say that the latest version works now (had to change a few other things, but that's unrelated to this change). Thanks!

**Comment by marshallswain** [comment]
@vwong Nope.  Sorry.  I thought this was related to the change from `feathers-authentication/client` to `feathers-authentication-client`.
