### ISSUE TITLE
hook.params.user

### ISSUE THREAD

**Issue by marcpaskell** [feathersjs/feathers-authentication#483]
It would appear that (via socket.io) once authenticated the user object isnt updated on the hooks.params until a full refresh/re-auth?

**Comment by ekryski** [comment]
Thanks! Yup, duplicate of #293

**Comment by marcpaskell** [comment]
Thanks @ekryski - any idea when #293 will be ready?

**Comment by marshallswain** [comment]
@marcpaskell We're closing out a release, currently.  This will come as a patch release.  We have some prioritizing to do, but this is pretty important.
