### ISSUE TITLE
How to verify JWT in feathers issued by another feathers instance ?

### ISSUE THREAD

**Issue by JigSawFr** [feathersjs/feathers-authentication#484]
Hello,
I've a little question,
I've setup an feathers instance to allow LDAP auth and return JWT if success.
And now i've setup another feathers instance (for a different service),
I wanted to protect routes of second instance with JWT of first instance.
But i don't know how to do it without building another auth service (so duplicated...).
Do you have some clue ?
Thank you

**Comment by marshallswain** [comment]
The simplest way would be to go ahead and register the auth plugin on the other server.  You can disable external access to the `/authentication` endpoint using a hook.  As long as you have the same `secret` and `jwt` config on both servers, you'll be able to use the `feathers-authentication-jwt` plugin and the `authenticate('jwt')` hook.

**Comment by JigSawFr** [comment]
Okay thank you, what i need to write in hook to disable access ?

**Comment by marshallswain** [comment]
https://docs.feathersjs.com/api/hooks-common.html#disallow
