### ISSUE TITLE
app.get('auth') vs app.get('authentication')

### ISSUE THREAD

**Issue by brenmcnamara** [feathersjs/feathers-authentication#497]
Maybe I'm not understanding the code, but it seems that `app.get(<something>)` fetches from the relevant config file in the `/config` directory.

In the documentation [here](https://docs.feathersjs.com/api/authentication/server.html#default-options), it suggests the name of this config should be 'auth' for the authentication config. In addition, the code in feathers-authentication-local and feathers-authentication-jwt make the assumption that their configs can be fetched using app.get('auth'). However, when using the generator to generate the authentication service:

```feathers generate authentication```

The config file is modified to have an "authentication" config, not "auth". Is this correct?

**Comment by marshallswain** [comment]
I believe the modules default location needs to be updated.

**Comment by ekryski** [comment]
Yes this was changed in the generator but was never update in the auth modules. I think because the generator is set up to pass the auth configs explicitly this wasn't caught sooner. I have PRs coming.
