### ISSUE TITLE
Multi-factor Local Auth

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#5]
There are few different ways to define multi-factor. For this first release we are talking about typically a text message with a pin code or an email confirmation with a unique token.

A more robust version can come that uses TOTP and I've created issue #130 to track that.

**Comment by ekryski** [comment]
Technically this should be possible using https://github.com/feathersjs/feathers-authentication-management. I have yet to try it out but will report back!

**Comment by ekryski** [comment]
This is supported by `feathers-authentication-management` and is already used in production by people. We're going to look at tighter integration in #393 so future progress will be tracked there or in https://github.com/feathersjs/feathers-authentication-management/issues itself.
