### ISSUE TITLE
passport log failure

### ISSUE THREAD

**Issue by mmahalwy** [feathersjs/feathers-authentication#505]
Currently, I am getting 500 errors when doing oauth2 login with Google. That's fine, but I cannot tell what the error is! There is no logs or errors being flashed.

Haven't done anything custom other than the generator.

**Comment by marshallswain** [comment]
The easiest way to see the error is to comment out the `handler` middleware, restart the server, and try again.  That should allow you to see the raw error.

**Comment by ekryski** [comment]
or turn on debug logs. https://docs.feathersjs.com/guides/advanced/debugging.html

**Comment by marshallswain** [comment]
This is not an error with `feathers-authentication`, so I'm closing it.  Feel free to reopen, if needed.
