### ISSUE TITLE
Support async storage for React Native

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#51]
In the client code we currently store the JWT and the current user in localstorage. React native has async storage instead so we should provide an abstraction.

**Comment by daffl** [comment]
We could make a token storage service. That way a user can use whichever one they need.

**Comment by ekryski** [comment]
Ya I was just going to create an abstraction called `storage` that determines which system you are on and just gets used. I was thinking the user would be unaware of it so they shouldn't have to make any decisions about what to use.

**Comment by ekryski** [comment]
This is reliant on https://github.com/feathersjs/feathers-localstorage.

**Comment by ekryski** [comment]
Working in v0.4.0. Closed by #76
