### ISSUE TITLE
[example] CustomStrategy using passport-custom

### ISSUE THREAD

**Issue by kfern** [feathersjs/feathers-authentication#516]
Hi!

Could I create a custom passport strategy using passport-custom? How? Any basic example?

[https://www.npmjs.com/package/passport-custom: ](https://www.npmjs.com/package/passport-custom) This module lets you authenticate using custom logic.

Thanks in advance

**Comment by kfern** [comment]
https://github.com/feathersjs/feathers-docs/issues/787

**Comment by zusamann** [comment]
@kfern I added an example here feathersjs/feathers-docs#787

**Comment by kfern** [comment]
@zusamann Thanks 🎉💃
