### ISSUE TITLE
Support client usage in NodeJS

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#52]
In the client code we currently store the JWT and the current user in localstorage. NodeJS doesn't have this so we could just store it in memory or find a localstorage alternative for Node.

**Comment by marshallswain** [comment]
https://www.npmjs.com/package/localstorage-memory

**Comment by ekryski** [comment]
@marshallswain beauty! That's perfect.

**Comment by marshallswain** [comment]
Also, this: https://www.npmjs.com/package/detect-node

**Comment by ekryski** [comment]
Once we convert over to using https://github.com/feathersjs/feathers-localstorage or https://github.com/feathersjs/feathers-memory for storing the token and user on the "client" this should work.

**Comment by ekryski** [comment]
Working in v0.4.0. Closed by #76
