### ISSUE TITLE
Provider is undefined when using restrictToRoles

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/feathers-authentication#525]
This might be related to https://github.com/feathersjs/feathers-authentication/issues/432, however i'm using feathers-rest.

### Steps to reproduce
server is using these hooks for user model:
```javascript
const auth = require('feathers-authentication').hooks;
const { restrictToOwner,restrictToRoles } = require('feathers-authentication-hooks');

    get: [
      auth.authenticate('jwt'),
      restrictToRoles({
         roles: ['admin'],
         fieldName: 'group',
         idField: 'id',
         ownerField: 'id',
         owner: true
      }),
      custom_method()
    ],
```

client is calling normally with:
`this.api.service('users').get(payload.userId)`

### Expected behavior
`hook.params.provider` should be set to "rest" when checking inside of `custom_method()`

### Actual behavior
provider is undefined. When i comment out the line for restrictToRoles, it works as expected.

### System configuration (latest as of 13.06.2017)
feathers-2.1.2
feathers-rest-1.7.2
feathers-authentication-1.2.4
feathers-authentication-client-0.3.2
feathers-hooks-2.0.1
feathers-commons-0.8.7
feathers-hooks-common-3.5.1

**Comment by eikaramba** [comment]
i just saw that i posted this to the wrong repo. i'm very sorry, it is sometimes really confusing with all these repositories. should i move it?

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-authentication-hooks #19](https://github.com/feathersjs/feathers-authentication-hooks/issues/19) via [**ZenHub**](https://www.zenhub.com/)
