### ISSUE TITLE
Cannot read property 'user' of undefined - lib\socket\update-entity.js:26:104

### ISSUE THREAD

**Issue by jerfowler** [feathersjs/feathers-authentication#529]
Getting the following error:

error: Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'user' of undefined
    at `local-path`\node_modules\feathers-authentication\lib\socket\update-entity.js:26:104
    at Array.forEach (native)
    at Object.updateEntity (`local-path`\node_modules\feathers-authentication\lib\socket\update-entity.js:24:26)

Looks to be an issue when assigning socketEntity:

feathers-authentication/src/socket/update-entity.js
```JavaScript
Object.keys(socketMap).forEach(socketId => {
    const socket = socketMap[socketId];
    const socketEntity = (socket.feathers && socket.feathers[authConfig.entity]) || socket.request.feathers[authConfig.entity];
\\...
```
I would change that to:

```JavaScript
Object.keys(socketMap).forEach(socketId => {
    const socket = socketMap[socketId];
    const feathers = socket.feathers || socket.request.feathers;
    const socketEntity = feathers && feathers[authConfig.entity];
\\...
```
I'll try and submit a pull request... if I can find the time!

**Comment by TimIsOverpowered** [comment]
I can confirm that I get this error every patch that is sent out
