### ISSUE TITLE
LogoutTimer not being cleared correctly

### ISSUE THREAD

**Issue by wnxhaja** [feathersjs/feathers-authentication#532]
I recently upgraded my feathers authentication from v1.2.2 to v1.2.4.

I am calling `app.authenticate()` on my client and expecting for the jwt expiry to update. I get the updated jwt token with the new expiry.  But still I am being logout by the server because jwt token expires.

I look up the changelog and I found this fix [#449](https://github.com/feathersjs/feathers-authentication/pull/499). It is now using `long-timeout` in setting the logoutTimer but still using the old way of clearing timeout [here](https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L106). Then I change to `lt.clearTimeout(logoutTimer)` and it is now properly clearing the timeouts.

**Comment by marshallswain** [comment]
@wnxhaja thank you for reporting this issue.  Would you be able to make a PR with your changes?

**Comment by wnxhaja** [comment]
Sure!

**Comment by daffl** [comment]
Closed via #534
