### ISSUE TITLE
Error options.service does not exist after initial auth setup

### ISSUE THREAD

**Issue by franzherzog** [feathersjs/feathers-authentication#535]
### Steps to reproduce
* feathers generate authentication
* select Username + Password (Local)
* use a name different than the default "users"
* proceed with generator

after finish
* npm start
throws error:
***options.service does not exist***

# workaround
* open /path/to/project/config/default.json
* change service name manual

{
...
  "authentication": {
....
    "local": {
      "entity": "user",
      "service": "users",   ***<<<<<<<<<<<<<<<<<<< change to whatever your service is called***
      "usernameField": "email",
      "passwordField": "password"
    },
.....
  "nedb": "../data"
}

### System configuration

Linux Node v6.9
"feathers-authentication": "^1.2.6",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.4.3",

**Comment by marshallswain** [comment]
Does the generator still create a `/users` service?

**Comment by franzherzog** [comment]
nope, the service is generated like intended. On 26 Jun 2017 7:34 am, Marshall Thompson <notifications@github.com> wrote:Does the generator still create a /users service?

**Comment by franzherzog** [comment]
edit: yes the service for authentication is created but its not called the "/user" service any more because we changed the default name in the generator.

**Comment by marshallswain** [comment]
I see.  I'm going to move this to the `generator-feathers` repo, so we can get the generator fixed.

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/generator-feathers #236](https://github.com/feathersjs/generator-feathers/issues/236) via [**ZenHub**](https://www.zenhub.com/)
