### ISSUE TITLE
whats the official way to open cors in feather ?

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers-authentication#536]
whats the official way to open cors in feather ?
I get this error when i try to ping feahterjs server. 

![image](https://user-images.githubusercontent.com/1026325/27718851-a4644518-5d1c-11e7-97c5-d5eb993fe54c.png)

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
You can just use the CORS middleware: https://github.com/expressjs/cors, which works for feathers-rest.  CORS is not relevant for feathers-socketio.

**Comment by jpca999** [comment]
thanks  @marshallswain for the reply, but do you think this is a CORS error ?
I'm using React NAtive expo. 
I'm not sure sure if its a CORS issue but it should be.

**Comment by marshallswain** [comment]
There's not enough visible information to figure it out.  "Unhandled promise" might be giving a clue there, but it's really not enough to know.
