### ISSUE TITLE
email in lower case ?

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers-authentication#538]
Currently how it works is system recoganizes as diffent email for both follownig cases. 
e@email.com  E@email.com 

I think it woudl be nice if it converts to small caps before it saves to the db. 

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
You can do that already with a [before hook](https://docs.feathersjs.com/api/hooks.html), specifically using the [lowercase](https://docs.feathersjs.com/api/hooks-common.html#lowercase) common hook.
