### ISSUE TITLE
Connection without password

### ISSUE THREAD

**Issue by Clowning** [feathersjs/feathers-authentication#541]
Hey, 

Currently, i'm coding a mobile app with a facebook login, everything is handle on my application, but i don't know what i can do after get user facebook information to register it into my feathers API. 

I just want to send personal information with the token and that Feathers return me a JWT to allow users to interact with the API. 

But I can't found anythings about that, do you have any idea ? It's my first time with a facebook login with a mobile application so i'm lost haha!

Thanks (And sorry for my english!)

**Comment by marshallswain** [comment]
@Clowning, take a look at the `feathers-authentication-oauth2` plugin and use the `passport-facebook-token` strategy from npm.  I think you might even be able to copy over the setup from a new `feathers-cli` app with Facebook Auth and just swap out the strategy.

Also, maybe @ekryski or @corymsmith knows of an example application.

**Comment by Clowning** [comment]
Hey @marshallswain, thanks a lot, i've tried to install this passport, everything is installed but i've this error : "info: error: authentication - Method: create: Failed to fetch user profile".

I've set my App ID and Secret Key and pass a valid Facebook Token :/ 

Do you have any idea about that?

**Comment by Clowning** [comment]
Ok my bad ! It's working! Thanks a lot :-) !

**Comment by marshallswain** [comment]
I'm glad you got it working.
