### ISSUE TITLE
Checking hook.params.headers.authorization

### ISSUE THREAD

**Issue by ramosquito5** [feathersjs/feathers-authentication#552]
### Steps to reproduce

When authenticating with rest I check if the client is sending his jwt, and as such I check
`hook.params.headers.authorization`

When authenticating with socket.io I tried to do the same.

### Expected behavior
checking `hook.params.headers.authorization` would have the jwt.

### Actual behavior
`hook.params.headers.authorization` is undefined, the jwt is under `hook.params.headers.Authorization` note the A of authorization.
I modified my code to make it work but i think it should be the same for all cases that have the authentication

### System configuration

feathers --version
2.1.1

**Comment by marshallswain** [comment]
This is the correct behavior.  Authentication over socket.io and primus doesn't happen with headers.  It works by sending messages to `authenticate`.  You can see the code here: https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L150.

Let me know if you're interested in making header support work.

**Comment by baljeet** [comment]
https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L150 

This repo is unavailable now, is there any other repo that i can refer.
