### ISSUE TITLE
Documentation not understanding

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers-authentication#563]
I am trying to access protected endpoints with http requests.

I do not understand this passage in the documentation:

> If you are not using the feathers-authentication-client and you have registered this module server side then you can simply include the access token in an Authorization header.

Where should I register this on the server and how?

Sam

**Comment by marshallswain** [comment]
Yeah.  That line is hurt by a bit of ambiguity.  This line is talking about how to connect from the client.  So, on the client, you can either use the feathers-authentication-client or just connect manually with Ajax.  If you decide to use your favorite Ajax library, just pass the JWT in the Authorization header when you want to perform an authenticated request to the server.

**Comment by idealley** [comment]
Actually it is not... it is under Direct usage:

> Direct Usage

> Using a HTTP Request

> If you are not using the feathers-authentication-client and you have registered this module server side then you can simply include the access token in an Authorization header.

Thus I do not understand why I would need a client module on the server and if it is necessary how to register it. I have tried few versions but I am getting errors :(

**Comment by marshallswain** [comment]
It is not what?

You use the client package any time you want to connect to another server.  It doesn't matter if the client is a web browser or a Node.js application.

> I am trying to access protected endpoints with http requests.

From where to where?

**Comment by idealley** [comment]
It seems that this passage of the documentation is about Direct calls to an API endpoint that is protected. 

I have generated an auth in my api with `feathers generate authentication` which added some boiler plate to my API. 

now I am trying to call the `/authentication` endpoint to get a JWT token in order to call protected endpoints.

If I send a payload with post man as follow:

```
{
  "strategy": "local",
  "email": "<email>",
  "password": "<password>"
}
```
I get

```
{
    "name": "BadRequest",
    "message": "Missing credentials",
    "code": 400,
    "className": "bad-request",
    "data": {
        "message": "Missing credentials"
    },
    "errors": {}
}
```

if I send the same payload but with the stategy `jwt` I get:

```
{
    "name": "NotAuthenticated",
    "message": "No auth token",
    "code": 401,
    "className": "not-authenticated",
    "data": {},
    "errors": {}
}
```

Then I found the passage I mentioned in the doc.

I do not know what to do.

Sorry for being unlcear

**Comment by marshallswain** [comment]
You might be missing a header.  I clarified the docs just now.  

Set `Content-Type` to `application/json`.

**Comment by idealley** [comment]
I have it.

**Comment by idealley** [comment]
This is the passage I am speaking of:
https://docs.feathersjs.com/api/authentication/jwt.html#direct-usage

**Comment by marshallswain** [comment]
Set a before hook on the `authentication` service on the server and inspect that the email and password are both making it into the request.

Double check your `feathers-authentication-local` config to make sure you haven't changed the `usernameField` and `passwordField` to something besides `email` and `password`.

**Comment by idealley** [comment]
So I have set up a quick  look and I get an object data with the values I sent
```
{ data:
   { strategy: 'jwt',
     email: 'test@test.com',
     password: 'password' },
```
for the local strategy I have:

```
    "local": {
      "entity": "user",
      "service": "users",
      "usernameField": "email",
      "passwordField": "password"
    }
```

**Comment by marshallswain** [comment]
Can you post your `authentication.js` file?

**Comment by idealley** [comment]
```
const authentication = require('feathers-authentication');
const jwt = require('feathers-authentication-jwt');
const local = require('feathers-authentication-local');

const test = require('./hooks/test').test;



module.exports = function () {
  const app = this;
  const config = app.get('authentication');


  
  app.configure(authentication(config));

  app.configure(jwt());
  app.configure(local(config.local));

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  app.service('authentication').hooks({
    before: {
      create: [
        test(),
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};

```

**Comment by marshallswain** [comment]
Looks fine.  What are the strategies in your config?

**Comment by idealley** [comment]
```
    "strategies": [
      "jwt",
      "local"
    ],
```

**Comment by marshallswain** [comment]
Your config looks fine.  How about your user.hooks file?

**Comment by idealley** [comment]
```
module.exports = {
  before: {
    all: [],
    find: [ authenticate('jwt') ],
    get: [ ...restrict ],
    create: [ hashPassword() ],
    update: [ ...restrict, hashPassword() ],
    patch: [ ...restrict, hashPassword() ],
    remove: [ ...restrict ]
  },

  after: {
    all: [
      commonHooks.when(
        hook => hook.params.provider,
        commonHooks.discard('password')
      )
    ], ...
```

I did not restrict the create, in order to be able to create users. I am storing them in a mongo db. By the way I have noticed that now the password is not hashed on create... thus I cannot create new users. 

I have those installed:
```
 "feathers-authentication": "^1.2.7",
    "feathers-authentication-client": "^0.3.3",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
```

**Comment by idealley** [comment]
I am testing with both users some that have a hashed password and others that don't. Same results.

**Comment by marshallswain** [comment]
Message me in the Feathers Slack and we'll pair on this.

**Comment by idealley** [comment]
Thanks to @marshallswain  and his precious help. 

We discovered that I had an environement variable called `password` that was messing up the `default.json` configuration file. The `passwordField` was taking the value of the environment variable and not the string "password"

The solution was quite easy, escaping the `"password"` with two backslashes `"\\password"`

This solved the authentication issue as well as the password hashing issue.
