### ISSUE TITLE
Custom tokenEndpoint failing

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-authentication#57]
When I use a custom token endpoint, e.g. `/login` or `/token`, registering the before hook seems to throw an error. I'm pretty sure it's [this line here](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/token/index.js#L119).

Should it be instead: `const tokenService = app.service(options.tokenEndpoint);` ?

**Comment by marshallswain** [comment]
Thanks!  Good find.

**Comment by marshallswain** [comment]
The fix for this is published to npm as version `0.2.2`

**Comment by bedeoverend** [comment]
@marshallswain thanks!

**Comment by ekryski** [comment]
@marshallswain thanks for fixing. I'll be writing tests for this stuff today.
