### ISSUE TITLE
typo in jwt default options

### ISSUE THREAD

**Issue by bnielsen1965** [feathersjs/feathers-authentication#570]
There is what I assume is a type in the default jwt options...
https://github.com/feathersjs/feathers-authentication/blob/master/src/options.js#L17

It reads...
header: { typ: 'access' },

Perhaps it is meant to read...
header: { type: 'access' },

I haven't noticed anything broken in authentication but this looks like a bug waiting to pop out.

**Comment by daffl** [comment]
This is actually correct. JWT options have some strange abbreviations. Follow-up fix in the generator in https://github.com/feathersjs/generator-feathers/pull/281
