### ISSUE TITLE
userEndpoint problem in sub-app

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-authentication#63]
For example, I have a user service handling user login
```
/api/user/auth/local
```

In another service, which is mounted as sub-app, I want to verify the user, the path is 
```
/api/riddle
```

The problem is, how can I set the userEndpoint of the hook in /api/riddle like this
```
        authHooks.populateUser({userEndpoint: '../user'}),
```

**Comment by wuyuanyi135** [comment]
Probably in my case I should use middleware and jwt to protect the sub-apps.
For example I can mount a middleware using jwt at `/private-api` and mount the apps requiring authentication as its sub apps.

**Comment by ekryski** [comment]
@wuyuanyi135 Ya again, you could do what you are hoping to do when this issue is closed https://github.com/feathersjs/feathers/issues/216.

Currently you can pass a custom `userEndpoint` to the `populateUser` hook but that won't work for sub apps.
