### ISSUE TITLE
Find "query" is replaced by token

### ISSUE THREAD

**Issue by fastlorenzo** [feathersjs/feathers-authentication#64]
Hello, 
In : feathers-authentication/src/client/hooks.js 
`export let populateSocketParams = function() {
  return function(hook) {
    if (hook.params.token) {
     ** hook.params.query = {
        token: hook.params.token
      };**
    }
  };
};`

You should create a new object and keep the existing params, otherwise every param query passed to the 'find' action is replaced by the token only.

Thanks :+1:

**Comment by daffl** [comment]
@ekryski Is there a reason for adding the token to the query? Shouldn't it be already set on the socket?

**Comment by fastlorenzo** [comment]
A way to fix it could be using the object.assign call

Lorenzo Bernardi

**Comment by marshallswain** [comment]
I think this might be related to this issue: https://github.com/feathersjs/feathers/issues/224

**Comment by marshallswain** [comment]
Oh.  it's on the query.  nm.

**Comment by fastlorenzo** [comment]
Changing 
`hook.params.query = { token: hook.params.token };`
to
`hook.params.query = Object.assign({}, hook.params.query, {
        token: hook.params.token
      });`
fixes the issue.
Could you integrate the fix or should I create a pull request ?

**Comment by marshallswain** [comment]
Would you mind creating a PR?  Thanks.

**Comment by ekryski** [comment]
@fastlorenzo thanks for the PR. Let me review. I think it's likely that it's my bad but I want to make sure it doesn't break anything. I haven't had time to write all the tests that I've needed to.

**Comment by fastlorenzo** [comment]
@ekryski sure, no issue :+1:

**Comment by fastlorenzo** [comment]
PS: maybe you should also use the Object.assing for the following line in the same file : 
`19: hook.params.headers = {`

**Comment by ekryski** [comment]
@fastlorenzo ya I think you are right on the headers part. I actually think @daffl might be right and that for sockets we don't need to set the token each time. `hook.params.query` and `hooks.params.data` are the only things sent to the server by feathers-client but in the case of sockets because it is a persistent connection we should already have the token on server side.

**Comment by fastlorenzo** [comment]
Indeed, and I think sending the token each time in the query can be an issue, for example if you want to filter the query using a parameter named `token`.

**Comment by fastlorenzo** [comment]
@ekryski I quickly checked by removing the token to be sent in each request and it look ks like it's working, as @daffl said.
I'll create another pull request for that so you can check it.

**Comment by fastlorenzo** [comment]
I added the proposed changes in my PR

**Comment by daffl** [comment]
That probably means that we don't need `populateSocketParams` at all anymore right? Besides that, the PR looks great, thank you for your help!

**Comment by ekryski** [comment]
@fastlorenzo I'll take a look. Yes, currently `token` gets filtered out of the query on the server side so that will need to be addressed.

@daffl you are right that is no longer needed.

**Comment by ekryski** [comment]
I've issued a new PR (#67) that addresses all this and adds some more tests.

**Comment by ekryski** [comment]
Close by #65 and #67.
