### ISSUE TITLE
How to forbid get and find on the userEndpoint?  

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-authentication#66]
Hello
I don't want `get` and `find` service exposed to the user because it will list usernames. I tried to use hook but after disabling `find` the authentication process failed: because it need the user service to populate username. Is there any suggestion to block these services?

**Comment by daffl** [comment]
You can use the [disable hook](http://docs.feathersjs.com/hooks/bundled.html#disableproviders) and disable `external` access for those methods.

**Comment by wuyuanyi135** [comment]
Thank you.
