### ISSUE TITLE
Password-less Local Auth with Email / SMS

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#7]
Be able to send an email or text with an auth link.

**Comment by ekryski** [comment]
I'm working on this right now actually and it's coming along nicely.

**Comment by daniel79** [comment]
Would be good to have option to implement own authentication provider (for example instead of using 'local' we clould use 'myServiceName')

**Comment by pierretasci** [comment]
I kind of mimicked something like this in my own app where I create a wrapper service that handles auth requests in place of the token service provided by this repo. If the user is new or logging in, it redirects to an email login service (using passwordless) that handles the email and redirect workflow.

When the user clicks the email link, it attempts to authenticate again using the token in the email. This request is again sent to the wrapper but this time it forwards it to the token service. It isn't super pretty but it gets this done while still using JWT tokens as the primary logged in auth scheme.

Hope that helps.

**Comment by ekryski** [comment]
Wow time flies. I've been busy fixing bugs and writing tests. I have a stashed branch with passwordless auth working. Might need a couple tweaks due to the updates that just landed in auth but I'm hoping to have something up soon.

**Comment by daffl** [comment]
Related to https://github.com/feathersjs/feathers-authentication/pull/96

/cc @ccummings

**Comment by philippnagel** [comment]
@ekryski Any progress on your implementation? Just asking before implementing everything myself.

**Comment by ekryski** [comment]
See https://github.com/feathersjs/feathers-authentication-management. I haven't tried it yet but will next week. I believe it is very close to release. Feel free to give it a go and report any issues on that repo.

cc/  @eddyystop

I'm going to close this as that is the going to be the repo for account confirmation, password reset, etc. going forward.

**Comment by rhythnic** [comment]
I created an example repo for doing passwordless auth with `feathers-authentication-management`.

https://github.com/rhythnic/feathers-passwordless-auth-example
