### ISSUE TITLE
User doesn't get populated after authentication with databases that don't use _id 

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#71]
The `populateUser()` hook gets called automatically by the `token` service after a token create. Because this hook has `_id` as the default `idField` ([See this line](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/populate-user.js#L7)) when you generate an app using a database that doesn't use the `_id` field (Postgres, MySQL, etc) the user silently doesn't get populated.

You can pass the `idField` option to `app.configure(authentication({ idField: 'id' }))` and it will work but it's not immediately apparent how to fix this.

**Comment by ekryski** [comment]
I'm not sure how to approach this. We could try and infer the database type the user is using but that is going to be way complex and probably have undesired consequences.

Maybe if the user isn't found we throw an error? I can't think of a case where the user shouldn't be found using the id from the auth token. @daffl thoughts?

**Comment by fastlorenzo** [comment]
Maybe you could explicitly require the idField option to be set or document ?

**Comment by ekryski** [comment]
Working in v0.4.0. Closed by #76
