### ISSUE TITLE
Authentication not worked with hooks.remove('password')

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-authentication#82]
When I try to login `POST http://localhost:3030/auth/local`, I get an error:
```json
{
  "name": "GeneralError",
  "message": "data and hash arguments required",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}
```

In this situation, I have one hook for `users` service:
```javascript
exports.after = {
  all: [],
  find: [
    hooks.remove('password')
  ],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
}
```

When i remove 
```javascript 
hooks.remove('password')
```
from after find hook, authentication is worked!

This is because the `auth` service [uses](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/local/index.js#L29) method `.find()` in `users` service.

**Comment by ekryski** [comment]
@kulakowka yes it's because of this issue https://github.com/feathersjs/feathers-hooks/issues/48

There's a PR open for it: https://github.com/feathersjs/feathers-hooks/pull/51. Will be merge shortly :smile:

**Comment by ekryski** [comment]
feathers-hooks@1.2.0 now fixes this. As an example, say we want to only remove the password if it is an external call (ie. over sockets or http(s)):

```js
exports.after = {
  all: [hooks.remove('password', hook => hook.params.provider)]
};
```

**Comment by ekryski** [comment]
We're going to make one more change so that you don't even need to do that.

**Comment by kulakowka** [comment]
@ekryski it's cool! :beer::beer:
