### ISSUE TITLE
Username response ?

### ISSUE THREAD

**Issue by naptiv** [feathersjs/feathers-authentication#84]
I just get the id and token as response on authenticate using postegres 
If I try to `app.logout()` I also get a `TypeError: storage.remove is not a function`

```
import io from 'socket.io-client';
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import socketio from 'feathers-socketio/client';
import storage from 'feathers-memory';
import localstorage from 'feathers-localstorage';
import authentication from 'feathers-authentication/client';

const socket = io('localhost:3030');
const api = feathers()
  .configure(socketio(socket)) // you could use Primus or REST instead
  .configure(hooks())
  .use('storage', localstorage())
  .configure(authentication());

  api.io.on('connect', function(){
      console.log("connection....");
      api.authenticate({
        type: 'local',
        'email': 'user@email.com',
        'password': '1234'
      }).then(function(result){
          console.log(result);
      }).catch(function(error){
        console.error('Error authenticating!', error);
      });
  });


  api.io.on("authenticated", function(result){

    console.log("user is :");
    api.user().then(function(user){
      console.log(user);
    })
 
  });

  api.io.connect();

```

I've also tried with `.configure(authentication({ idField: 'id' })); `

**Comment by ekryski** [comment]
@naptiv Two questions:

- which version for feathers-authentication are you using? We had pushed an update yesterday morning that fixed the response on auth to include the user.
- Where are you using the client? The browser?

**Comment by naptiv** [comment]
- feathers-authentication@0.4.0 
- yep browser.

Btw, I had to change `.use('storage', localstorage({"storage":memory}))` as I got a `ReferenceError: window is not defined at new LocalStorage` @feathers-localstorage/lib/index.js:32:41

**Comment by ekryski** [comment]
@naptiv I've verified that the user does come back with Postgres. Using feathers-authentication@0.4.0. You need to set the `idField` to `'id'` at the root of your auth config section. So:

```js
{
  "host": "localhost",
  "port": 3030,
  "postgres": "postgres://postgres:@localhost:5432/test",
  "public": "../public/",
  "auth": {
    "idField": "id",
    "token": {
      "secret": "a secret"
    },
    "local": {}
  }
}
```

**Comment by ekryski** [comment]
@naptiv let's track that other bug in https://github.com/feathersjs/feathers-localstorage/issues/3. I have some questions there.
