### ISSUE TITLE
App level auth routes for multiple sub-routes

### ISSUE THREAD

**Issue by startupthekid** [feathersjs/feathers-authentication#90]
I have an application with multiple mounted subapps, all feathers apps, that I need to provide authentication on. Each subapp is different; one uses `feathers-rest`, another `feathers-socketio`, and so on. By the current model, because I set `app.use(rest())` and `app.use(hooks())`, on the subapps, not the parent app, I can't configure authentication on the parent level, even with something like this:

```
app
	.use('/api', apiRoutes)
	.use('/analytics', analyticsRoutes)
	.use('/authentication', authRoutes)
  .use('/payment', paymentRoutes)
  .configure(authentication({
    userEndpoint: '/api/users',
    token: {
      secret: config.JWT_SECRET
    },
    local: {
      usernameField: 'email'
    },
    facebook: {
      clientID: config.FACEBOOK_APP_ID,
      clientSecret: config.FACEBOOK_APP_SECRET,
      strategy: FacebookStrategy,
      tokenStrategy: FacebookTokenStrategy,
      permissions: {
        scope: ['email', 'public_profile']
      }
    }
  }));
```

where the authentication is configured after all the services have been registered. Am I stuck with setting up auth on each individual subapp or is there a way I can do it all one and done?

**Comment by daffl** [comment]
Currently probably yes. I think we'll need to be able to register services at the parent app level via https://github.com/feathersjs/feathers/issues/216 for this to be possible.

**Comment by startupthekid** [comment]
Ok that's not terrible. That'd be nice if services were registered at the parent level, but not a huge deal for now. Also response time is just stellar.
