### ISSUE TITLE
populateUser can pull defaults from config, if available.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#91]
Use `app.get to see if there's a default value provided in the config, already.  This will work for `userEndpoint` and `passwordField`.

**Comment by ekryski** [comment]
This already happens. It's just not released yet. See https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/populate-user.js#L15

**Comment by marshallswain** [comment]
:+1:
