### ISSUE TITLE
populateUser: allow option to populate without db call.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#92]
If only the id is needed, we can offer the option to only use it on the hook.params.user and skip the call to the db.  Not sure what the API should look like.

**Comment by ekryski** [comment]
Well, you already have the id returned alongside the token when you authenticate so were you thinking that you would not want the user populated in the successful auth response?

**Comment by marshallswain** [comment]
In one of my apps, all I want in `hook.params.user` is `{_id: <id>}`, so I want populate user to only populate that much into `hook.params.user`.

**Comment by marshallswain** [comment]
That's for the majority of the services.  For a couple of them I still need the full user.

**Comment by ekryski** [comment]
Thinking about this a bit more and after revising the hooks I would say that if you just want the `id` then just write a quick custom hook? It's not really `populateUser` anymore then is it?

I guess the other option would be to pass on option like `{idOnly: true}` or something which just grabs the id from the token payload. Personally, I feel like that is maybe a bit more custom to your app so it should probably just be a custom hook. Open to being proven wrong though...

**Comment by marshallswain** [comment]
This is sort of a micro-optimization, anyway.  Closing.
