### ISSUE TITLE
Bundled hooks should pull from auth config to avoid having to pass duplicate props.

### ISSUE THREAD

**Issue by naptiv** [feathersjs/feathers-authentication#93]
I runned into an issue @https://github.com/feathersjs/feathers-react-native-chat/issues/5 

As I learned I had to set the config for auth to use `id` instead of `_id` when using pg, via : 

`  "auth": {
        "idField" : "id"
    }
`

Howerver using hook still require to set the correct id : 

`create: [auth.setUserId({sourceProp:'id',destProp: 'sentBy'})]`

**Comment by ekryski** [comment]
So it's not working for you with those changes?

**Comment by naptiv** [comment]
It's work if I set the sourceProp, but as I already set the config it should take care itself.

**Comment by ekryski** [comment]
Ah I get it! Ya I think @harangue made the same observation. I'm going to rephrase the issue title.

**Comment by ekryski** [comment]
Closed in v0.6.0 by https://github.com/feathersjs/feathers-authentication/pull/109.
