### ISSUE TITLE
Client should store token string and not the token object

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-authentication#95]
I thought I had fixed this but it looks like you need to reference `hook.params.token.value` in https://github.com/feathersjs/feathers-authentication/blob/master/src/client/hooks.js#L22.

**Comment by PhilWhitehurst** [comment]
It doesn't send the token when using a service over io sockets am I missing something. I want to authorise a service but it is looking for an authorisation header that isn't sent with a socket.

**Comment by ekryski** [comment]
@PhilWhitehurst it definitely should. Can you post a link to your code so that we can see what might be going on? Alternatively, take a look at this fully working example for a comparison. https://github.com/feathersjs/feathers-chat
